/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, July 9, 2014 at 7:50:46 PM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol _UIGlintyStringViewDelegate
@required
-(void)glintyAnimationDidStart;
-(void)glintyAnimationDidStop;
-(void)glintyFadeOutAnimationDidStop;
-(void)glintyFadeInAnimationDidStop;
-(void)glintyAnimationDidStart;
-(void)glintyAnimationDidStop;
-(void)glintyFadeOutAnimationDidStop;
-(void)glintyFadeInAnimationDidStop;
@end
