/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CDSnapshot_WAChatSession_ : _CDSnapshot {
	BOOL hidden; 
	BOOL removed; 
	short sessionType; 
	int contactABID; 
	int flags; 
	int messageCounter; 
	int unreadCount; 
	id contactJID; 
	id lastMessageText; 
	id partnerName; 
	id savedInput; 
	id groupInfo; 
	id lastMessage; 
	id properties; 
	id groupMembers; 
	id messages; 
	double lastMessageDate; 
}
@end