/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CDSnapshot_WAContact_ : _CDSnapshot {
	int abUserID; 
	int sort; 
	id firstName; 
	id fullName; 
	id imageHash; 
	id indexName; 
	id tokens; 
	id section; 
	id phones; 
}
@end