/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CDSnapshot_WAPhone_ : _CDSnapshot {
	id label; 
	id phone; 
	id whatsAppID; 
	id contact; 
	id favorite; 
	id status; 
}
@end