/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _CDSnapshot_WAMessage_ : _CDSnapshot {
	BOOL isFromMe; 
	short childMessagesDeliveredCount; 
	short filteredRecipientCount; 
	int flags; 
	int groupEventType; 
	int messageStatus; 
	int messageType; 
	int sort; 
	id fromJID; 
	id pushName; 
	id stanzaID; 
	id text; 
	id toJID; 
	id broadcast; 
	id chatSession; 
	id groupMember; 
	id lastSession; 
	id mediaItem; 
	id parentMessage; 
	id childMessages; 
	id words; 
	double messageDate; 
}
@end