/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _WAContactPopupOS7 : WAContactPopup {
	UIImage* _bottomArrow; 
	UIView* _viewBody; 
	UIImage* _pinImage; 
}
-(void)setImageTag:(int)arg1;
-(void)drawRect:(CGRect)arg1;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(void).cxx_destruct;
-(void)setAnnotation:(id)arg1;
-(id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2;
@end