/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:25 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _WADownloadProgressArcLayer : CALayer {
}
@property (assign,nonatomic,@dynamic) float progress; 
+(BOOL)needsDisplayForKey:(id)arg1;
@end