/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _WAImageMessageContainerView : UIView {
	NSDate* _date; 
}
@property (nonatomic,retain) NSDate* date; 				//@synthesize date=_date - In the implementation block
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)setDate:(id)arg1;
-(id)accessibilityValue;
-(void).cxx_destruct;
@end