/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:13 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIGestureRecognizerDelegate.h>

@interface _WAImageToImageTransitionDefaultGestureRecognizerDelegate : NSObject <UIGestureRecognizerDelegate> {
	WAImageToImageTransitionNavigationController* _parentController; 
}
@property (assign,nonatomic) WAImageToImageTransitionNavigationController* parentController; 				//@synthesize parentController=_parentController - In the implementation block
-(BOOL)gestureRecognizerShouldBegin:(id)arg1;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(void)setParentController:(id)arg1;
@end