/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:13 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _WANoBlurNavigationBar : UINavigationBar {
	UIView* _grayBackgroundView; 
}
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end