/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol ABNewPersonViewControllerDelegate
@required
-(void)newPersonViewController(id):arg1 didCompleteWithNewPerson(*):arg2 ;
-(void)newPersonViewController(id):arg1 didCompleteWithNewPerson(*):arg2 ;
@end
