/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MFMailComposeViewControllerDelegate.h>
#import <ABDisabledControllerDelegate.h>
#import <ProblemInputControllerDelegate.h>

@interface AboutViewController : UIViewController <MFMailComposeViewControllerDelegate, ABDisabledControllerDelegate, ProblemInputControllerDelegate> {
	UITableView* _tableViewButtons; 
	UIView* _viewDivider; 
	UIView* _viewLogoContainer; 
	UIImageView* _imageLogo; 
	UIImageView* _imageWP; 
	UILabel* _labelTitlePortrait; 
	UILabel* _labelVersionPortrait; 
	UIView* _viewTableHeader; 
	UILabel* _labelTitleLandscape; 
	UILabel* _labelVersionLandscape; 
	UIView* _footerView; 
	UILabel* _labelCopyright; 
}
@property (nonatomic,retain) UITableView* tableViewButtons; 				//@synthesize tableViewButtons=_tableViewButtons - In the implementation block
@property (nonatomic,retain) UIView* viewDivider; 				//@synthesize viewDivider=_viewDivider - In the implementation block
@property (nonatomic,retain) UIView* viewLogoContainer; 				//@synthesize viewLogoContainer=_viewLogoContainer - In the implementation block
@property (nonatomic,retain) UIImageView* imageLogo; 				//@synthesize imageLogo=_imageLogo - In the implementation block
@property (nonatomic,retain) UIImageView* imageWP; 				//@synthesize imageWP=_imageWP - In the implementation block
@property (nonatomic,retain) UILabel* labelTitlePortrait; 				//@synthesize labelTitlePortrait=_labelTitlePortrait - In the implementation block
@property (nonatomic,retain) UILabel* labelVersionPortrait; 				//@synthesize labelVersionPortrait=_labelVersionPortrait - In the implementation block
@property (nonatomic,retain) UIView* viewTableHeader; 				//@synthesize viewTableHeader=_viewTableHeader - In the implementation block
@property (nonatomic,retain) UILabel* labelTitleLandscape; 				//@synthesize labelTitleLandscape=_labelTitleLandscape - In the implementation block
@property (nonatomic,retain) UILabel* labelVersionLandscape; 				//@synthesize labelVersionLandscape=_labelVersionLandscape - In the implementation block
@property (nonatomic,retain) UIView* footerView; 				//@synthesize footerView=_footerView - In the implementation block
@property (nonatomic,retain) UILabel* labelCopyright; 				//@synthesize labelCopyright=_labelCopyright - In the implementation block
-(void)setTableViewButtons:(id)arg1;
-(void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
-(void)probleminputControllerDidCancel:(id)arg1;
-(void)setImageLogo:(id)arg1;
-(void)updateLayoutToOrientation:(int)arg1;
-(void)setViewDivider:(id)arg1;
-(void)setViewLogoContainer:(id)arg1;
-(void)setImageWP:(id)arg1;
-(void)setLabelTitlePortrait:(id)arg1;
-(void)setLabelVersionPortrait:(id)arg1;
-(void)setViewTableHeader:(id)arg1;
-(void)setLabelTitleLandscape:(id)arg1;
-(void)setLabelVersionLandscape:(id)arg1;
-(void)setLabelCopyright:(id)arg1;
-(void)contactUsAction;
-(void)openFAQAction;
-(void)abDisabledViewControllerDidCancel:(id)arg1;
-(id)helperTitleForABDisabledViewController:(id)arg1;
-(id)helperTextForABDisabledViewController:(id)arg1;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)viewDidLayoutSubviews;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void).cxx_destruct;
-(void)setFooterView:(id)arg1;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
@end