/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAInfoInputViewControllerDelegate.h>

@interface AddContactInfoViewController : UINavigationController <WAInfoInputViewControllerDelegate> {
	WAInfoInputViewController* _infoInputViewController; 
	id<AddContactInfoViewControllerDelegate> _addInfoDelegate; 
	void* _displayedPerson; 
	int _propertyType; 
	NSString* _propertyValue; 
}
@property (assign,nonatomic) id<AddContactInfoViewControllerDelegate> addInfoDelegate; 				//@synthesize addInfoDelegate=_addInfoDelegate - In the implementation block
@property (nonatomic,copy) void* displayedPerson; 				//@synthesize displayedPerson=_displayedPerson - In the implementation block
@property (assign,nonatomic) int propertyType; 				//@synthesize propertyType=_propertyType - In the implementation block
@property (nonatomic,retain) NSString* propertyValue; 				//@synthesize propertyValue=_propertyValue - In the implementation block
-(id)initWithPerson:(void*)arg1 delegate:(id)arg2;
-(void)setPropertyType:(int)arg1;
-(void)infoInputViewControllerDidCancel:(id)arg1;
-(void)infoInputViewControllerDidFinish:(id)arg1;
-(void)setAddInfoDelegate:(id)arg1;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
-(void)setPropertyValue:(id)arg1;
@end