/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AVAudioPlayerDelegate
@optional
-(void)audioPlayerDidFinishPlaying(id):arg1 successfully(BOOL):arg2 ;
-(void)audioPlayerDecodeErrorDidOccur(id):arg1 error(id):arg2 ;
-(void)audioPlayerBeginInterruption(id):arg1 ;
-(void)audioPlayerEndInterruption(id):arg1 withOptions(unsigned):arg2 ;
-(void)audioPlayerEndInterruption(id):arg1 withFlags(unsigned):arg2 ;
-(void)audioPlayerEndInterruption(id):arg1 ;
@end
