/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>
#import <ProblemInputControllerDelegate.h>
#import <WAPhoneNumberTextFieldDelegate.h>

@interface ChangeNumberInputController : UIViewController <UITextFieldDelegate, ProblemInputControllerDelegate, WAPhoneNumberTextFieldDelegate> {
	id<ChangeNumberInputControllerDelegate> _delegate; 
	CountryInfo* _selectedCountry1; 
	CountryInfo* _selectedCountry2; 
	NSString* _oldPhoneNumber; 
	NSString* _newPhoneNumber; 
	NSString* _contextFailReason; 
	WAOverlayView* _overlayView; 
	UITableView* _tableViewInput; 
	UIView* _viewInput1; 
	UIView* _viewInputFieldsContainer1; 
	UILabel* _labelPhoneInput1; 
	UIView* _viewCCodeContainer1; 
	UILabel* _labelPlusSign1; 
	UILabel* _labelCCode1; 
	UITextField* _textFieldCode1; 
	UIImageView* _imageCodeBg1; 
	UIView* _viewPhoneNumberContainer1; 
	WAPhoneNumberTextField* _textFieldPhone1; 
	UIImageView* _imagePhoneBg1; 
	UIView* _viewInput2; 
	UIView* _viewInputFieldsContainer2; 
	UILabel* _labelPhoneInput2; 
	UIView* _viewCCodeContainer2; 
	UILabel* _labelPlusSign2; 
	UILabel* _labelCCode2; 
	UITextField* _textFieldCode2; 
	UIImageView* _imageCodeBg2; 
	UIView* _viewPhoneNumberContainer2; 
	WAPhoneNumberTextField* _textFieldPhone2; 
	UIImageView* _imagePhoneBg2; 
}
@property (nonatomic,retain) UITableView* tableViewInput; 				//@synthesize tableViewInput=_tableViewInput - In the implementation block
@property (nonatomic,retain) UIView* viewInput1; 				//@synthesize viewInput1=_viewInput1 - In the implementation block
@property (nonatomic,retain) UIView* viewInputFieldsContainer1; 				//@synthesize viewInputFieldsContainer1=_viewInputFieldsContainer1 - In the implementation block
@property (nonatomic,retain) UILabel* labelPhoneInput1; 				//@synthesize labelPhoneInput1=_labelPhoneInput1 - In the implementation block
@property (nonatomic,retain) UIView* viewCCodeContainer1; 				//@synthesize viewCCodeContainer1=_viewCCodeContainer1 - In the implementation block
@property (nonatomic,retain) UILabel* labelPlusSign1; 				//@synthesize labelPlusSign1=_labelPlusSign1 - In the implementation block
@property (nonatomic,retain) UILabel* labelCCode1; 				//@synthesize labelCCode1=_labelCCode1 - In the implementation block
@property (nonatomic,retain) UITextField* textFieldCode1; 				//@synthesize textFieldCode1=_textFieldCode1 - In the implementation block
@property (nonatomic,retain) UIImageView* imageCodeBg1; 				//@synthesize imageCodeBg1=_imageCodeBg1 - In the implementation block
@property (nonatomic,retain) UIView* viewPhoneNumberContainer1; 				//@synthesize viewPhoneNumberContainer1=_viewPhoneNumberContainer1 - In the implementation block
@property (nonatomic,retain) WAPhoneNumberTextField* textFieldPhone1; 				//@synthesize textFieldPhone1=_textFieldPhone1 - In the implementation block
@property (nonatomic,retain) UIImageView* imagePhoneBg1; 				//@synthesize imagePhoneBg1=_imagePhoneBg1 - In the implementation block
@property (nonatomic,retain) UIView* viewInput2; 				//@synthesize viewInput2=_viewInput2 - In the implementation block
@property (nonatomic,retain) UIView* viewInputFieldsContainer2; 				//@synthesize viewInputFieldsContainer2=_viewInputFieldsContainer2 - In the implementation block
@property (nonatomic,retain) UILabel* labelPhoneInput2; 				//@synthesize labelPhoneInput2=_labelPhoneInput2 - In the implementation block
@property (nonatomic,retain) UIView* viewCCodeContainer2; 				//@synthesize viewCCodeContainer2=_viewCCodeContainer2 - In the implementation block
@property (nonatomic,retain) UILabel* labelPlusSign2; 				//@synthesize labelPlusSign2=_labelPlusSign2 - In the implementation block
@property (nonatomic,retain) UILabel* labelCCode2; 				//@synthesize labelCCode2=_labelCCode2 - In the implementation block
@property (nonatomic,retain) UITextField* textFieldCode2; 				//@synthesize textFieldCode2=_textFieldCode2 - In the implementation block
@property (nonatomic,retain) UIImageView* imageCodeBg2; 				//@synthesize imageCodeBg2=_imageCodeBg2 - In the implementation block
@property (nonatomic,retain) UIView* viewPhoneNumberContainer2; 				//@synthesize viewPhoneNumberContainer2=_viewPhoneNumberContainer2 - In the implementation block
@property (nonatomic,retain) WAPhoneNumberTextField* textFieldPhone2; 				//@synthesize textFieldPhone2=_textFieldPhone2 - In the implementation block
@property (nonatomic,retain) UIImageView* imagePhoneBg2; 				//@synthesize imagePhoneBg2=_imagePhoneBg2 - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)showOverlay:(id)arg1;
-(void)deviceCheckFinishedWithResult:(id)arg1;
-(void)deviceCheckFailedWithError:(id)arg1;
-(void)doneAction:(id)arg1;
-(void)validateUserInput;
-(void)performSameDeviceCheck;
-(void)composeEmail:(id)arg1;
-(void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
-(void)probleminputControllerDidCancel:(id)arg1;
-(void)phoneNumberTextFieldDidChange:(id)arg1;
-(void)showAndReleaseGenericAlert:(id)arg1;
-(void)showAndReleaseAppStoreAlert:(id)arg1;
-(void)showAndReleaseContactSupportAlert:(id)arg1;
-(void)setTextFieldCode2:(id)arg1;
-(void)phoneNumberNormalized:(id)arg1 userInfo:(id)arg2;
-(void)phoneNumberNormalizationFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)validateOldPhoneNumber;
-(void)formatCode1Field;
-(void)formatCode2Field;
-(void)setImageCodeBg1:(id)arg1;
-(void)setImageCodeBg2:(id)arg1;
-(void)setImagePhoneBg1:(id)arg1;
-(void)setImagePhoneBg2:(id)arg1;
-(void)code1ChangedAction:(id)arg1;
-(void)code2ChangedAction:(id)arg1;
-(void)resizeInputViews;
-(void)proceedToAuthCodeRequest;
-(void)setTableViewInput:(id)arg1;
-(void)setViewInput1:(id)arg1;
-(void)setViewInputFieldsContainer1:(id)arg1;
-(void)setLabelPhoneInput1:(id)arg1;
-(void)setViewCCodeContainer1:(id)arg1;
-(void)setLabelPlusSign1:(id)arg1;
-(void)setLabelCCode1:(id)arg1;
-(void)setTextFieldCode1:(id)arg1;
-(void)setViewPhoneNumberContainer1:(id)arg1;
-(void)setTextFieldPhone1:(id)arg1;
-(void)setViewInput2:(id)arg1;
-(void)setViewInputFieldsContainer2:(id)arg1;
-(void)setLabelPhoneInput2:(id)arg1;
-(void)setViewCCodeContainer2:(id)arg1;
-(void)setLabelPlusSign2:(id)arg1;
-(void)setLabelCCode2:(id)arg1;
-(void)setViewPhoneNumberContainer2:(id)arg1;
-(void)setTextFieldPhone2:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
-(id)initWithDelegate:(id)arg1;
@end