/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIVideoEditorControllerDelegate.h>
#import <UIActionSheetDelegate.h>
#import <UINavigationControllerDelegate.h>
#import <MFMessageComposeViewControllerDelegate.h>
#import <MFMailComposeViewControllerDelegate.h>
#import <ForwardPickerDelegate.h>
#import <SinglePersonPickerDelegate.h>
#import <PhoneInputViewControllerDelegate.h>
#import <WAGroupComposerDelegate.h>
#import <WAChatSessionCellDelegate.h>
#import <ABNewPersonViewControllerDelegate.h>
#import <ABPeoplePickerNavigationControllerDelegate.h>
#import <AddContactInfoViewControllerDelegate.h>
#import <ABDisabledControllerDelegate.h>
#import <PhoneConfirmationControllerDelegate.h>

@interface ChatListViewController : WATableViewController <UIVideoEditorControllerDelegate, UIActionSheetDelegate, UINavigationControllerDelegate, MFMessageComposeViewControllerDelegate, MFMailComposeViewControllerDelegate, ForwardPickerDelegate, SinglePersonPickerDelegate, PhoneInputViewControllerDelegate, WAGroupComposerDelegate, WAChatSessionCellDelegate, ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate, AddContactInfoViewControllerDelegate, ABDisabledControllerDelegate, PhoneConfirmationControllerDelegate> {
	id _prepareToSendVideoFileCompletionHandler; 
	NSManagedObjectID* _groupToRegisterOnServer; 
	UIBarButtonItem* _barButtonCompose; 
	UIBarButtonItem* _barButtonEditBegin; 
	UIBarButtonItem* _barButtonEditDone; 
	UIBarButtonItem* _barButtonDeleteAll; 
	WAActivityLabel* _activityLabel; 
	UIView* _viewSearchInProgress; 
	void* _addressBook; 
	NSMutableDictionary* _chatViewControllers; 
	BOOL _viewIsActive; 
	NSString* _selectedChatJID; 
	int _numberOfRows; 
	NSArray* _searchResults; 
	NSOperationQueue* _searchQueue; 
	BOOL _moreResultsComing; 
	NSString* _messageText; 
	NSMutableArray* _contactPhones; 
	NSMutableArray* _contactEmails; 
	NSManagedObjectID* _contactID; 
	NSString* _stringForSizingDeleteButton; 
	WAChatSession* _selectedChatSessionForMoreOptions; 
	WAChatsTableView* _tableViewChats; 
	UITableView* _tableViewNoChats; 
	UIView* _viewHelperText; 
	UIWebView* _labelHelperTop; 
	UILabel* _labelHelperBottom; 
	UIView* _viewChatButtons; 
	WAChatButton* _buttonBroadcast; 
	WAChatButton* _buttonGroupChat; 
}
@property (nonatomic,retain) WAChatsTableView* tableViewChats; 				//@synthesize tableViewChats=_tableViewChats - In the implementation block
@property (nonatomic,retain) UITableView* tableViewNoChats; 				//@synthesize tableViewNoChats=_tableViewNoChats - In the implementation block
@property (nonatomic,retain) UIView* viewHelperText; 				//@synthesize viewHelperText=_viewHelperText - In the implementation block
@property (nonatomic,retain) UIWebView* labelHelperTop; 				//@synthesize labelHelperTop=_labelHelperTop - In the implementation block
@property (nonatomic,retain) UILabel* labelHelperBottom; 				//@synthesize labelHelperBottom=_labelHelperBottom - In the implementation block
@property (nonatomic,retain) UIView* viewChatButtons; 				//@synthesize viewChatButtons=_viewChatButtons - In the implementation block
@property (nonatomic,retain) WAChatButton* buttonBroadcast; 				//@synthesize buttonBroadcast=_buttonBroadcast - In the implementation block
@property (nonatomic,retain) WAChatButton* buttonGroupChat; 				//@synthesize buttonGroupChat=_buttonGroupChat - In the implementation block
-(void)leaveSearchMode;
-(id)startChatWithSession:(id)arg1 highlightedMessage:(id)arg2 activateKeyboard:(BOOL)arg3 pushImmediately:(BOOL)arg4 animated:(BOOL)arg5;
-(void)chatStorageDidLoadDatabase:(id)arg1;
-(void)processSendURL:(id)arg1;
-(void)forwardFileAtURL:(id)arg1;
-(void)leaveEditMode;
-(void)chatStorage:(id)arg1 didUpdateChatSession:(id)arg2;
-(void)chatStorageDidUpdateChatSessionList:(id)arg1;
-(void)enterEditModeAction:(id)arg1;
-(void)leaveEditModeAction:(id)arg1;
-(void)deleteAllAction:(id)arg1;
-(void)fontSizeDidChange:(id)arg1;
-(id)startChatWithContact:(id)arg1 JID:(id)arg2 pushImmediately:(BOOL)arg3 animated:(BOOL)arg4;
-(void)phoneConfirmationControllerDidFinish:(id)arg1;
-(void)phoneConfirmationControllerDidCancel:(id)arg1;
-(void)xmppConnectionDidBeginConnect:(id)arg1;
-(void)xmppConnectionDidConnect:(id)arg1;
-(void)xmppConnectionDidDisconnect:(id)arg1;
-(void)purgeViewControllers;
-(void)phoneInputViewController:(id)arg1 didFinishWithCountryCode:(id)arg2 phoneNumber:(id)arg3;
-(void)formatTitle;
-(void)phoneInputViewControllerDidCancel:(id)arg1;
-(void)abDisabledViewControllerDidCancel:(id)arg1;
-(void)singlePersonPickerDidCancel:(id)arg1;
-(void)singlePersonPicker:(id)arg1 didSelectAction:(id)arg2;
-(void)singlePersonPicker:(id)arg1 didSelectContact:(id)arg2;
-(void)hideActivity;
-(void)addContactInfoViewControllerDidCancel:(id)arg1;
-(void)addContactInfoViewControllerDidFinish:(id)arg1;
-(void)chatStorage:(id)arg1 willDeleteChatSession:(id)arg2;
-(void)chatStorage:(id)arg1 didDeleteChatSessionsAtIndexes:(id)arg2;
-(void)chatStorage:(id)arg1 didDeleteMessagesInSession:(id)arg2;
-(void)chatStorage:(id)arg1 didUpdateMessage:(id)arg2;
-(id)backItemTitleForViewController:(id)arg1;
-(id)shortViewControllerTitle;
-(void)formatHelperText;
-(id)topHelperHTMLStringWithFont:(id)arg1;
-(void)startNewChat;
-(void)startGroupChat;
-(void)searchFinishedWithUserInfo:(id)arg1;
-(id)searchQueue;
-(void)composeAction:(id)arg1;
-(void)showActivity:(id)arg1;
-(void)startSearch;
-(void)layoutTopButtons;
-(void)hideSearchBarIfNecessary;
-(void)showTooltipIfNeeded;
-(void)setTableViewChats:(id)arg1;
-(void)setTableViewNoChats:(id)arg1;
-(void)setViewHelperText:(id)arg1;
-(void)setLabelHelperTop:(id)arg1;
-(void)setLabelHelperBottom:(id)arg1;
-(void)setViewChatButtons:(id)arg1;
-(void)setButtonBroadcast:(id)arg1;
-(void)setButtonGroupChat:(id)arg1;
-(id)chatViewControllers;
-(void)removeFileAtURL:(id)arg1;
-(void)showChatAfterSendingExternalMediaWithMessage:(id)arg1 error:(id)arg2;
-(void)prepareExternalVideoFileForSending:(id)arg1 completion:(id)arg2;
-(void)startChatFromURLWithJID:(id)arg1;
-(void)sendSMSInviteTo:(id)arg1;
-(void)sendEmailInviteTo:(id)arg1;
-(id)visibleCellWithJid:(id)arg1;
-(void)requestConfirmationToDeleteGroupChatSession:(id)arg1 atIndexPath:(id)arg2;
-(void)inviteContacts;
-(void)openBroadcasts;
-(void)sendExternalMediaAtURL:(id)arg1 toContact:(id)arg2;
-(void)startChatFromURLWithContactDict:(id)arg1;
-(void)showGroupOptionsForChatSession:(id)arg1;
-(void)showKnownContactOptionsForChatSession:(id)arg1;
-(void)showUnknownContactOptionsForChatSession:(id)arg1;
-(void)updateMuteStateOfCellForChatSession:(id)arg1;
-(void)emailChatHistoryForChatSession:(id)arg1 withMailComposeViewController:(id)arg2;
-(void)promptForConfirmationToClearChatSession:(id)arg1;
-(void)addNewPersonFromChatSessionToContacts:(id)arg1;
-(void)addNumberFromChatSessionToExistingContact:(id)arg1;
-(void)dismissPickerAndContinueWithPerson:(void*)arg1;
-(void)forwardPicker:(id)arg1 didSelectContact:(id)arg2;
-(void)forwardPickerDidCancel:(id)arg1;
-(id)forwardPicker:(id)arg1 confirmationTextForContact:(id)arg2;
-(void)groupComposer:(id)arg1 didFinishWithContacts:(id)arg2 media:(id)arg3;
-(void)groupComposer:(id)arg1 didFinishWithContacts:(id)arg2 subject:(id)arg3 picture:(id)arg4;
-(void)groupComposerDidCancel:(id)arg1;
-(void)chatSessionCellShowMoreOptions:(id)arg1;
-(BOOL)isCachedViewControllerAvailableForChatSession:(id)arg1;
-(void)composeBroadcastMessage;
-(void)broadcastAction:(id)arg1;
-(void)groupChatAction:(id)arg1;
-(id)startChatWithContact:(id)arg1 JID:(id)arg2 animated:(BOOL)arg3;
-(void)jumpToAllChatsFromViewController:(id)arg1;
-(void)forwardMessages:(id)arg1 toContact:(id)arg2 JID:(id)arg3;
-(void)xmppConnection:(id)arg1 networkStatusChanged:(id)arg2;
-(void)xmppConnection:(id)arg1 chatStateChanged:(id)arg2 forJID:(id)arg3;
-(id)tableViewSessions;
-(void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void*)arg2;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
-(id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
-(void)applicationDidEnterBackground:(id)arg1;
-(void)didReceiveMemoryWarning;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(id)uniqueIdentifier;
-(void)searchDisplayControllerDidEndSearch:(id)arg1;
-(void)searchDisplayControllerWillBeginSearch:(id)arg1;
-(void)searchDisplayControllerWillEndSearch:(id)arg1;
-(BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
-(void)videoEditorControllerDidCancel:(id)arg1;
-(void)videoEditorController:(id)arg1 didSaveEditedVideoToPath:(id)arg2;
-(void)videoEditorController:(id)arg1 didFailWithError:(id)arg2;
-(void).cxx_destruct;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
-(void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
-(void)peoplePickerNavigationControllerDidCancel:(id)arg1;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
-(void)updateUI;
@end