/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAChatStorageDelegate.h>
#import <WAContactsStorageDelegate.h>
#import <WASyncManagerDelegate.h>
#import <XMPPConnectionDelegate.h>

@interface ChatManager : NSObject <WAChatStorageDelegate, WAContactsStorageDelegate, WASyncManagerDelegate, XMPPConnectionDelegate> {
	NSString* _registrationURL; 
	NSString* _codeRequestURL; 
	NSString* _sameDeviceCheckURL; 
	NSString* _bingAPIKey; 
	NSString* _googleAPIKey; 
	NSString* _fsqClientID; 
	NSString* _fsqClientSecret; 
	NSArray* _pushSounds; 
	SoundEffect* _incomingSoundEffect; 
	SoundEffect* _outgoingSoundEffect; 
	NSString* _phoneNumber; 
	NSString* _countryCode; 
	NSString* _deviceToken; 
	NSString* _currentStatus; 
	struct {
		unsigned int verificationInProgress:1;
		unsigned int needReloadAddressBook:1;
		unsigned int playOfflineMessageSound:1;
		unsigned int vibrateEnabled:1;
		unsigned int soundsEnabled:1;
		unsigned int showMessagePreview:1;
		unsigned int connectionProblemAlertShown:1;
		unsigned int popupMenuVisible:1;
	} flags; 
	NSMutableArray* _statusList; 
	NSMutableSet* _chatSessionsToRefresh; 
	NSMutableSet* _groupChatsToRefresh; 
	NSMutableSet* _delegates; 
	XMPPConnection* _connection; 
	WAChatStorage* _storage; 
	WACloudBackup* _cloudBackup; 
	WAContactsStorage* _contactsStorage; 
	WASyncManager* _syncManager; 
	WAPlaceIconCache* _placeIconCache; 
	WAProfilePictureCache* _profilePictureCache; 
	ALAssetsLibrary* _assetsLibrary; 
	int _connectionAttempts; 
	UIAlertView* _connectionUnavailableAlertView; 
	UIAlertView* _networkUnavailableAlertView; 
	int _newMessagesCounter; 
	long _lockTime; 
	CTCallCenter* _callCenter; 
	NSMutableSet* _placeCache; 
	NSDate* _gOverQueryLimitDate; 
	NSThread* _addressBookThread; 
	NSThread* _chatThread; 
	void* _workerAddressBook; 
	void* _sharedAddressBook; 
	NSMutableDictionary* _contactColors; 
	NSMutableArray* _shortWeekdaySymbols; 
	NSMutableArray* _weekdaySymbols; 
	NSMutableDictionary* _lastNotificationTimeForChat; 
	NSDictionary* _iCloudStats; 
	NSMutableArray* _pushStatsValues; 
	id _blockToPerformAfterDisconnecting; 
	NSNumberFormatter* _numberFormatter; 
	NSDateFormatter* _dateFormatterShortStyle; 
	NSDateFormatter* _dateFormatterMediumStyle; 
	NSDateFormatter* _dateFormatterMediumStyleNoYear; 
	NSDateFormatter* _timeFormatter; 
	NSDateFormatter* _dateTimeFormatter; 
	NSByteCountFormatter* _bcFormatter; 
	NSCalendar* _sharedCalendar; 
	NSMutableDictionary* _silentPushMessages; 
	int _backgroundPushMessageCount; 
	BOOL _usingSilentPush; 
	NSMutableSet* _navigationBarHintHistory; 
	CLLocation* _lastKnownLocation; 
}
@property (nonatomic,copy) NSString* phoneNumber; 				//@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,copy) NSString* countryCode; 				//@synthesize countryCode=_countryCode - In the implementation block
@property (nonatomic,retain) NSString* deviceToken; 				//@synthesize deviceToken=_deviceToken - In the implementation block
@property (nonatomic,retain) NSString* currentStatus; 				//@synthesize currentStatus=_currentStatus - In the implementation block
@property (nonatomic,copy) NSString* bingAPIKey; 
@property (nonatomic,copy) NSString* googleAPIKey; 
@property (nonatomic,copy) NSString* fsqClientID; 
@property (nonatomic,copy) NSString* fsqClientSecret; 
@property (nonatomic,copy) NSMutableArray* statusList; 				//@synthesize statusList=_statusList - In the implementation block
@property (nonatomic,copy) NSMutableSet* navigationBarHintHistory; 				//@synthesize navigationBarHintHistory=_navigationBarHintHistory - In the implementation block
@property (nonatomic,copy) XMPPConnection* connection; 				//@synthesize connection=_connection - In the implementation block
@property (nonatomic,copy) WAChatStorage* storage; 				//@synthesize storage=_storage - In the implementation block
@property (nonatomic,copy) WACloudBackup* cloudBackup; 				//@synthesize cloudBackup=_cloudBackup - In the implementation block
@property (nonatomic,copy) WAContactsStorage* contactsStorage; 				//@synthesize contactsStorage=_contactsStorage - In the implementation block
@property (nonatomic,copy) WASyncManager* syncManager; 				//@synthesize syncManager=_syncManager - In the implementation block
@property (nonatomic,copy) ALAssetsLibrary* assetsLibrary; 
@property (assign,nonatomic) BOOL vibrateEnabled; 
@property (assign,nonatomic) BOOL chatSoundsEnabled; 
@property (assign,nonatomic) BOOL showMessagePreview; 
@property (assign,nonatomic) BOOL verificationInProgress; 
@property (assign,nonatomic) BOOL needReloadAddressBook; 
@property (nonatomic,copy) BOOL popupMenuVisible; 
@property (assign,nonatomic) int newMessagesCounter; 				//@synthesize newMessagesCounter=_newMessagesCounter - In the implementation block
@property (nonatomic,retain) NSDate* gOverQueryLimitDate; 				//@synthesize gOverQueryLimitDate=_gOverQueryLimitDate - In the implementation block
@property (nonatomic,retain) CLLocation* lastKnownLocation; 				//@synthesize lastKnownLocation=_lastKnownLocation - In the implementation block
@property (nonatomic,copy) void* sharedAddressBook; 
+(id)colorPalette;
+(id)sharedManager;
-(void)resetAuthInfo;
-(void)unregisterAllDelegates;
-(void)startAddressBookThread;
-(void)initializeChat;
-(void)resetStatusMessages;
-(void)setVibrateEnabled:(BOOL)arg1;
-(void)setChatSoundsEnabled:(BOOL)arg1;
-(void)setShowMessagePreview:(BOOL)arg1;
-(void)resetColors;
-(id)profilePictureCache;
-(void)setNewMessagesCounter:(int)arg1;
-(id)fullPhoneNumber;
-(id)sizeStringFromLongLong:(long long)arg1;
-(void)chatStorageDidLoadDatabase:(id)arg1;
-(void)checkNeedsReloadData;
-(void)setDeviceToken:(id)arg1;
-(void)receivedSilentPushForCompoundMessageId:(id)arg1;
-(void)receivedBackgroundPushNotification;
-(void)silentPushForCompoundMessageIdExpired:(id)arg1;
-(void)backgroundPushExpired;
-(void)setVerificationInProgress:(BOOL)arg1;
-(void)postPhoneChangeNotification;
-(void)chatStorage:(id)arg1 didFailWithError:(id)arg2;
-(void)chatStorage:(id)arg1 didReceiveMessage:(id)arg2;
-(void)chatStorage:(id)arg1 didUpdateChatSession:(id)arg2;
-(void)chatStorageDidUpdateChatSessionList:(id)arg1;
-(void)chatStorageDidDeleteChatSessions:(id)arg1;
-(void)reloadFavorites;
-(void)contactsStorageDidGenerateFavorites:(id)arg1;
-(id)localizedStringWithFormat:(id)arg1 number:(id)arg2;
-(void)contactsStorageDidUpdateFavorites:(id)arg1;
-(void)contactsStorageDidFailToGenerateFavorites:(id)arg1;
-(void)contactsStorageDidUpdateStatus:(id)arg1;
-(void)syncManager:(id)arg1 didFinishSyncWithResult:(id)arg2;
-(void)addContactFromABRecord:(void*)arg1 addressBook:(void*)arg2 whatsAppID:(id)arg3;
-(void)contactsStorageDidUpdateContacts:(id)arg1;
-(void)xmppConnectionDidBeginConnect:(id)arg1;
-(void)xmppConnectionDidConnect:(id)arg1;
-(void)xmppConnectionDidDisconnect:(id)arg1;
-(id)sharedCalendar;
-(BOOL)callWarningShown;
-(void)initiateCall:(id)arg1;
-(void)chatStorage:(id)arg1 didAddMessages:(id)arg2;
-(void)sameDeviceCheckForPhone:(id)arg1 countryCode:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5;
-(void)setCountryCode:(id)arg1 phoneNumber:(id)arg2;
-(void)requestAuthCodeWithDelegate:(id)arg1 method:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;
-(void)registerWithAuthCode:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;
-(void)setCurrentStatus:(id)arg1;
-(void)saveStatusList;
-(void)deleteAllStatusMessages;
-(void)enableContactsSync;
-(void)resetContactsSync;
-(id)messageTimestampStringFromDate:(id)arg1;
-(void)chatStorageDidUpdateBlacklist:(id)arg1;
-(void)menuControllerDidHideMenu:(id)arg1;
-(id)mapsURLsForCoordinate:(struct )arg1 address:(id)arg2;
-(id)routeURLsForSourceLocation:(id)arg1 destCoordinate:(struct )arg2 destAddress:(id)arg3;
-(void)getPresenseForChatSession:(id)arg1;
-(void)chatStorage:(id)arg1 willDeleteChatSession:(id)arg2;
-(void)chatStorage:(id)arg1 didDeleteChatSessionsAtIndexes:(id)arg2;
-(void)chatStorage:(id)arg1 didDeleteMessagesInSession:(id)arg2;
-(void)mediaUploadFailedForMessage:(id)arg1;
-(id)UIDelegateForMessage:(id)arg1;
-(void)chatStorage:(id)arg1 didUpdateMessage:(id)arg2;
-(void)mediaDownloadFailedForMessage:(id)arg1 withError:(id)arg2 autodownload:(BOOL)arg3;
-(void)updateChatSessionWithContactData:(id)arg1;
-(BOOL)profilePicsEnabled;
-(id)contactForJID:(id)arg1;
-(BOOL)isRecipientExists:(id)arg1;
-(id)profilePictureFromOriginal:(id)arg1 cropped:(id)arg2;
-(id)jpegDataForProfilePicture:(id)arg1;
-(id)thumbnailForProfilePicture:(id)arg1;
-(id)jpegDataForProfileThumbnail:(id)arg1;
-(void)sendLocalNotificationForMessage:(id)arg1 fromUser:(id)arg2;
-(void)disableProfilePics;
-(void)mergeChanges:(id)arg1;
-(void)receiveChatMessages:(id)arg1;
-(BOOL)showGenericServiceConnectionErrorAlwaysShowError:(BOOL)arg1;
-(id)chatTimestampFromDate:(id)arg1;
-(BOOL)isDelegateRegistered:(id)arg1;
-(void)reloadDataFromABRecord:(void*)arg1 whatsAppID:(id)arg2;
-(void)xmppConnection:(id)arg1 networkStatusChanged:(id)arg2;
-(void)xmppConnection:(id)arg1 chatStateChanged:(id)arg2 forJID:(id)arg3;
-(void)xmppConnection:(id)arg1 presenceChanged:(id)arg2;
-(id)chatThread;
-(void)xmppConnection:(id)arg1 lastActivityChanged:(id)arg2 forJID:(id)arg3;
-(void)xmppConnection:(id)arg1 statusChanged:(id)arg2 forMessageWithStanzaID:(id)arg3 fromJID:(id)arg4 data:(id)arg5;
-(void)xmppConnection:(id)arg1 stateChanged:(id)arg2;
-(void)xmppConnectionDidAuthenticate:(id)arg1;
-(void)xmppConnectionDidNotAuthenticate:(id)arg1;
-(void)xmppConnection:(id)arg1 passwordChanged:(id)arg2;
-(void)xmppConnection:(id)arg1 subjectChanged:(id)arg2 forGroup:(id)arg3 name:(id)arg4 ujid:(id)arg5 timestamp:(id)arg6 offlineStorage:(BOOL)arg7;
-(void)xmppConnection:(id)arg1 profilePictureChangedFor:(id)arg2 identifier:(id)arg3 author:(id)arg4 name:(id)arg5 timestamp:(id)arg6;
-(void)xmppConnection:(id)arg1 profilePictureUploadRequestFor:(id)arg2 timestamp:(id)arg3;
-(void)xmppConnection:(id)arg1 statusChanged:(id)arg2;
-(id)addressBookContainsJID:(id)arg1;
-(void)xmppConnection:(id)arg1 contactAdded:(id)arg2;
-(void)xmppConnection:(id)arg1 contactRemoved:(id)arg2;
-(void)xmppConnection:(id)arg1 contactsSyncRequest:(id)arg2 timestamp:(id)arg3;
-(void)xmppConnection:(id)arg1 contactUpdated:(id)arg2;
-(void)xmppConnection:(id)arg1 groupRemoved:(id)arg2;
-(void)xmppConnection:(id)arg1 userAdded:(id)arg2 toGroup:(id)arg3;
-(void)xmppConnection:(id)arg1 userRemoved:(id)arg2 fromGroup:(id)arg3 byUser:(id)arg4;
-(void)xmppConnection:(id)arg1 dirtyFlagsReceived:(id)arg2;
-(void)xmppConnection:(id)arg1 presenceChanged:(id)arg2 forJID:(id)arg3;
-(void)startChatThread;
-(void)loadStatusMessages;
-(void)menuControllerDidShowMenu:(id)arg1;
-(void)currentLocaleDidChange:(id)arg1;
-(id)fullPhoneNumber:(BOOL)arg1;
-(id)serviceExpirationDate;
-(id)sizeStringFromLongLong:(long long)arg1 numberFormatter:(id)arg2;
-(id)dateTimeFormatter;
-(id)dateFormatterMediumStyleNoYear;
-(void)initiateCallWithURL:(id)arg1;
-(void)abThreadMain;
-(void)initializeIPod;
-(void*)workerAddressBook;
-(void)internalReloadFavorites;
-(void)chatThreadMain;
-(void)dummyTimerRountine:(id)arg1;
-(void)internalReset;
-(BOOL)findContactInContext:(id)arg1 forChatSession:(id)arg2;
-(BOOL)findContactInContext:(id)arg1 forGroupMember:(id)arg2;
-(void)refreshChatSessionsForKnownContactsWithContext:(id)arg1;
-(void)refreshChatSessionsForUnknownContactsWithContext:(id)arg1;
-(void)dataRefreshContextDidSave:(id)arg1;
-(void)chatStorage:(id)arg1 didUpdateParticipantsOfChatSession:(id)arg2;
-(id)sameDeviceCheckURL;
-(id)requiredString;
-(void)fetcher:(id)arg1 finishedWithJSONData:(id)arg2 error:(id)arg3;
-(void)sameDeviceCheckForPhone:(id)arg1 countryCode:(id)arg2 rcToken:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6;
-(id)codeRequestURL;
-(id)registrationURL;
-(id)colorListFilePath;
-(id)statusListFilePath;
-(void)setCallWarningShown:(BOOL)arg1;
-(id)incomingSoundEffect;
-(void)failedUploadNotifyForMessage:(id)arg1;
-(void)chatStorageDidUpdateBroadcasts:(id)arg1;
-(void)chatStorageDidStartHistoryImport:(id)arg1;
-(void)chatStorageDidReportImportProgress:(id)arg1;
-(void)chatStorageDidFinishHistoryImport:(id)arg1;
-(void)requestLastSeenForJID:(id)arg1;
-(void)refreshChats;
-(void)showNetworkUnavailableAlert;
-(void)receivedMessageCompoundMessageId:(id)arg1;
-(void)networkStatusChanged:(id)arg1;
-(void)changeNumberFinishedWithUserInfo:(id)arg1;
-(void)changeNumberFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)changeRecoveryTokenFinishedWithUserData:(id)arg1;
-(void)changeRecoveryTokenFailedWithError:(id)arg1 withUserData:(id)arg2;
-(void)propertiesQuerySucceeded:(id)arg1;
-(void)propertiesQueryFailedWithError:(id)arg1;
-(void)getStatusSucceeded:(id)arg1 userData:(id)arg2;
-(void)getStatusDidFailWithError:(id)arg1 userData:(id)arg2;
-(void)reportCloudBackupStatsWithInfo:(id)arg1;
-(void)reportSilentPushStatsValues;
-(void)reportMissedSilentPushStatsValues;
-(void)getNewPasswordFinishedWithResult:(id)arg1;
-(id)outgoingSoundEffect;
-(BOOL)messageShouldBeMuted:(id)arg1;
-(void)saveNotificationTimeForMessage:(id)arg1;
-(void)reloadUnknownChatsWithWAContact:(id)arg1;
-(void)requestInteractiveDeltaSync;
-(id)addressBookThread;
-(void)contactsStorage:(id)arg1 didUpdatePictureForJID:(id)arg2;
-(id)localizedServicePrice;
-(id)localizedServiceExpirationDate;
-(BOOL)allowServicePurchase;
-(void)setNeedReloadAddressBook:(BOOL)arg1;
-(id)backupSizeStringFromLongLong:(long long)arg1;
-(id)dateTimeStringFromDate:(id)arg1;
-(id)messageDateStringFromDate:(id)arg1;
-(id)lastSeenStringFromDate:(id)arg1;
-(id)mapsURLsForAddress:(id)arg1;
-(void)setUserInteractionEnabled;
-(BOOL)validateProfilePicture:(id)arg1 errorMessage:(id)arg2;
-(void)getNewPasswordFailedWithError:(id)arg1;
-(id)colorForJID:(id)arg1;
-(id)placeCache;
-(id)placeIconCache;
-(void)reportMediaPickerStatsWithInfo:(id)arg1;
-(void)reportSilentPushStatsValue:(int)arg1;
-(void)disconnectAndUnloadChatDatabaseWithCompletionHandler:(id)arg1;
-(void)reconnectAndLoadChatDatabaseWithCompletionHandler:(id)arg1;
-(void)setGOverQueryLimitDate:(id)arg1;
-(void)setLastKnownLocation:(id)arg1;
-(id)weekdaySymbols;
-(id)shortWeekdaySymbols;
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)reset;
-(id)pushSettings;
-(void)registerDelegate:(id)arg1;
-(void)unregisterDelegate:(id)arg1;
-(int)serviceType;
-(id)timeFormatter;
-(id)numberFormatter;
-(id)dateFormatterMediumStyle;
-(id)dateFormatterShortStyle;
-(int)accountType;
@end