/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ChatHeaderView : MultilineHeaderView {
	NSString* _secondLineText; 
	UIFont* _firstLineFont; 
}
@property (nonatomic,retain) UIFont* firstLineFont; 				//@synthesize firstLineFont=_firstLineFont - In the implementation block
-(void)setFirstLineText:(id)arg1;
-(id)firstLineFontForLayout:(int)arg1 orientation:(int)arg2;
-(id)secondLineFontForLayout:(int)arg1 orientation:(int)arg2;
-(void)setFirstLineFont:(id)arg1;
-(id)initWithFrame:(CGRect)arg1 orientation:(int)arg2;
-(void)setOrientation:(int)arg1;
-(void).cxx_destruct;
-(void)setSecondLineText:(id)arg1;
-(id)secondLineText;
-(void)setLayoutType:(int)arg1;
@end