/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:52 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ChatSettingsViewController : UITableViewController {
	UISwitch* _switchMessageTimestamp; 
	UISwitch* _switchSaveReceivedMedia; 
	BOOL _showEmojiSection; 
	BOOL _showBackupSection; 
	BOOL _showAdvancedSection; 
}
-(void)fontSizeDidChange:(id)arg1;
-(void)switchMessageTimestampAction:(id)arg1;
-(void)switchSaveReceivedAction:(id)arg1;
-(void)selectWallpaperAction;
-(void)showFontSizePicker;
-(void)showBackupViewController;
-(void)showAdvancedSettings;
-(void)updateTableViewCell:(id)arg1 withBlockedCount:(int)arg2;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)initWithStyle:(int)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end