/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <GroupViewControllerDelegate.h>

@interface ContactsNavigationController : WAImageToImageTransitionNavigationController <GroupViewControllerDelegate> {
	GroupViewController* _groupController; 
	NSMutableDictionary* _contactViewControllers; 
}
-(void)popToContactsViewControllerAnimated:(BOOL)arg1;
-(void)loadGroupViewController;
-(void)groupViewController:(id)arg1 didSelectGroupWithID:(id)arg2;
-(void)loadContactsViewController:(int)arg1;
-(void)reloadViewControllers;
-(id)init;
-(void).cxx_destruct;
@end