/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ContactTableViewCell : UITableViewCell {
	UIImageView* _imageViewContact; 
	WAContactNameLabel* _nameLabel; 
	UILabel* _statusLabel; 
	UILabel* _detailLabel; 
	WAGroupMember* _groupMember; 
	BOOL _alwaysShowsPicture; 
	NSString* _jid; 
	float _accessoryViewInset; 
}
@property (nonatomic,copy) UIImageView* imageViewContact; 				//@synthesize imageViewContact=_imageViewContact - In the implementation block
@property (nonatomic,copy) WAContactNameLabel* nameLabel; 				//@synthesize nameLabel=_nameLabel - In the implementation block
@property (nonatomic,copy) UILabel* statusLabel; 				//@synthesize statusLabel=_statusLabel - In the implementation block
@property (nonatomic,copy) UILabel* detailLabel; 				//@synthesize detailLabel=_detailLabel - In the implementation block
@property (nonatomic,retain) NSString* jid; 				//@synthesize jid=_jid - In the implementation block
@property (assign,nonatomic) BOOL alwaysShowsPicture; 				//@synthesize alwaysShowsPicture=_alwaysShowsPicture - In the implementation block
@property (assign,nonatomic) float accessoryViewInset; 				//@synthesize accessoryViewInset=_accessoryViewInset - In the implementation block
-(void)setAlwaysShowsPicture:(BOOL)arg1;
-(void)setJid:(id)arg1;
-(void)configureWithGroupMember:(id)arg1;
-(void)setAccessoryViewInset:(float)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(id)accessibilityLabel;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void)didTransitionToState:(unsigned)arg1;
-(void)willTransitionToState:(unsigned)arg1;
-(id)accessibilityValue;
-(BOOL)isAccessibilityElement;
-(void).cxx_destruct;
@end