/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CountryInfo : NSObject {
	NSString* _iso; 
	NSString* _name; 
	NSString* _localizedName; 
	NSString* _cc; 
	NSArray* _mcc; 
	NSArray* _lengths; 
	NSArray* _trims; 
	NSString* _regex; 
	NSArray* _formats; 
	NSMutableSet* _searchTokens; 
}
@property (nonatomic,retain) NSString* iso; 				//@synthesize iso=_iso - In the implementation block
@property (nonatomic,retain) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSString* localizedName; 				//@synthesize localizedName=_localizedName - In the implementation block
@property (nonatomic,retain) NSString* cc; 				//@synthesize cc=_cc - In the implementation block
@property (nonatomic,retain) NSArray* mcc; 				//@synthesize mcc=_mcc - In the implementation block
@property (nonatomic,retain) NSArray* lengths; 				//@synthesize lengths=_lengths - In the implementation block
@property (nonatomic,retain) NSArray* trims; 				//@synthesize trims=_trims - In the implementation block
@property (nonatomic,retain) NSString* regex; 				//@synthesize regex=_regex - In the implementation block
@property (nonatomic,retain) NSArray* formats; 				//@synthesize formats=_formats - In the implementation block
@property (nonatomic,@dynamic,copy) NSSet* searchTokens; 
-(void)setIso:(id)arg1;
-(void)setMcc:(id)arg1;
-(void)setLengths:(id)arg1;
-(void)setTrims:(id)arg1;
-(void)setRegex:(id)arg1;
-(void)setFormats:(id)arg1;
-(id)description;
-(void)setName:(id)arg1;
-(void).cxx_destruct;
-(void)setCc:(id)arg1;
-(void)setLocalizedName:(id)arg1;
@end