/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:30 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CrashReport : NSObject {
}
+(void)initializeHandlers;
+(void)logCriticalEventWithName:(id)arg1 useActiveLog:(BOOL)arg2;
+(void)logCriticalEventWithName:(id)arg1;
+(id)crashInfoWithName:(id)arg1 reason:(id)arg2 addresses:(id)arg3 symbols:(id)arg4;
+(id)signalNumberToString:(int)arg1;
@end