/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol CustomLabelInputViewContollerDelegate
@required
-(void)labelInputViewController(id):arg1 didSaveLabel(id):arg2 ;
-(void)labelInputViewControllerDidCancel(id):arg1 ;
-(void)labelInputViewController(id):arg1 didSaveLabel(id):arg2 ;
-(void)labelInputViewControllerDidCancel(id):arg1 ;
@end
