/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:18 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PhoneConfirmationControllerDelegate.h>
#import <FeedbackInputControllerDelegate.h>
#import <DeleteConfirmationControllerDelegate.h>

@interface DeleteAccountContoller : WAModalNavigationController <PhoneConfirmationControllerDelegate, FeedbackInputControllerDelegate, DeleteConfirmationControllerDelegate> {
}
@property (assign,nonatomic,@dynamic) id<UINavigationControllerDelegate><DeleteAccountControllerDelegate> delegate; 
-(void)phoneConfirmationControllerDidFinish:(id)arg1;
-(void)phoneConfirmationControllerDidCancel:(id)arg1;
-(void)feedbackInputController:(id)arg1 didFinishWithFeedbackText:(id)arg2;
-(void)feedbackInputControllerDidCancel:(id)arg1;
-(void)deleteConfirmationControllerDidFinish:(id)arg1;
-(void)deleteConfirmationControllerDidCancel:(id)arg1;
-(id)initWithDelegate:(id)arg1;
@end