/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:33 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DeleteConfirmationController : UIViewController {
	id<DeleteConfirmationControllerDelegate> _delegate; 
	WAProgressHUD* _progressHUD; 
	NSString* _feedbackText; 
	UITableView* _tableView; 
	UIView* _viewThankYou; 
	UILabel* _labelThankYou; 
	UIView* _viewDeleteButton; 
	UIButton* _buttonDelete; 
	UITableViewCell* _cellConfirmation; 
	UILabel* _labelTitle; 
	UILabel* _labelHelperText; 
	UIImageView* _imageSadPhone; 
}
@property (nonatomic,copy) NSString* feedbackText; 				//@synthesize feedbackText=_feedbackText - In the implementation block
@property (nonatomic,retain) UITableView* tableView; 				//@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) UIView* viewThankYou; 				//@synthesize viewThankYou=_viewThankYou - In the implementation block
@property (nonatomic,retain) UILabel* labelThankYou; 				//@synthesize labelThankYou=_labelThankYou - In the implementation block
@property (nonatomic,retain) UIView* viewDeleteButton; 				//@synthesize viewDeleteButton=_viewDeleteButton - In the implementation block
@property (nonatomic,retain) UIButton* buttonDelete; 				//@synthesize buttonDelete=_buttonDelete - In the implementation block
@property (nonatomic,retain) UITableViewCell* cellConfirmation; 				//@synthesize cellConfirmation=_cellConfirmation - In the implementation block
@property (nonatomic,retain) UILabel* labelTitle; 				//@synthesize labelTitle=_labelTitle - In the implementation block
@property (nonatomic,retain) UILabel* labelHelperText; 				//@synthesize labelHelperText=_labelHelperText - In the implementation block
@property (nonatomic,retain) UIImageView* imageSadPhone; 				//@synthesize imageSadPhone=_imageSadPhone - In the implementation block
-(void)showHUD:(id)arg1;
-(void)removeHUD;
-(void)cancelAction:(id)arg1;
-(void)setLabelHelperText:(id)arg1;
-(void)setButtonDelete:(id)arg1;
-(void)setFeedbackText:(id)arg1;
-(void)deleteFinishedWithUserData:(id)arg1;
-(void)deleteFailedWithError:(id)arg1 withUserData:(id)arg2;
-(void)setViewDeleteButton:(id)arg1;
-(void)setViewThankYou:(id)arg1;
-(void)setLabelThankYou:(id)arg1;
-(void)setCellConfirmation:(id)arg1;
-(void)setLabelTitle:(id)arg1;
-(void)setImageSadPhone:(id)arg1;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)setTableView:(id)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
-(void)deleteAction;
@end