/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EmojiConverter : NSObject {
	NSMutableDictionary* _dictAppleToStandard; 
	NSMutableDictionary* _dictStandardToApple; 
	BOOL _convertEmoji; 
	NSCharacterSet* _privateEmojiCharacterSet; 
}
+(id)sharedConverter;
-(id)convertOutgoingEmojiString:(id)arg1;
-(id)convertIncomingEmojiString:(id)arg1;
-(BOOL)stringIsRegionalIndicatorSymbol:(id)arg1;
-(id)appleToStandard:(id)arg1;
-(id)standardToApple:(id)arg1;
-(id)stripEmoji:(id)arg1;
-(id)stringWithoutCustomEmoji:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end