/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:26 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ExecutionTimeProfiler : NSObject {
	NSMutableDictionary* beginDates; 
	NSMutableDictionary* endDates; 
	NSDate* beginDate; 
	NSDate* endDate; 
}
@property (nonatomic,retain) NSDate* beginDate; 
@property (nonatomic,retain) NSDate* endDate; 
-(void)endTask:(id)arg1;
-(void)beginTask:(id)arg1;
-(void)setBeginDate:(id)arg1;
-(id)init;
-(void).cxx_destruct;
-(id)result;
-(void)setEndDate:(id)arg1;
@end