/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:36 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextViewDelegate.h>

@interface FeedbackInputViewController : UIViewController <UITextViewDelegate> {
	id<FeedbackInputControllerDelegate> _delegate; 
	float _keyboardHeight; 
	UITableView* _tableViewFeedback; 
	UITableViewCell* _cellFeedbackInput; 
	UITextView* _textViewFeedback; 
	UILabel* _labelPlaceholder; 
}
@property (nonatomic,retain) UITableView* tableViewFeedback; 				//@synthesize tableViewFeedback=_tableViewFeedback - In the implementation block
@property (nonatomic,retain) UITableViewCell* cellFeedbackInput; 				//@synthesize cellFeedbackInput=_cellFeedbackInput - In the implementation block
@property (nonatomic,retain) UITextView* textViewFeedback; 				//@synthesize textViewFeedback=_textViewFeedback - In the implementation block
@property (nonatomic,retain) UILabel* labelPlaceholder; 				//@synthesize labelPlaceholder=_labelPlaceholder - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)nextAction:(id)arg1;
-(void)setTableViewFeedback:(id)arg1;
-(void)setCellFeedbackInput:(id)arg1;
-(void)setTextViewFeedback:(id)arg1;
-(void)setLabelPlaceholder:(id)arg1;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
-(void)textViewDidChange:(id)arg1;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
-(void)keyboardWillShow:(id)arg1;
@end