/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:30 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SoundPickerDelegate.h>

@interface GroupSettingsViewController : UITableViewController <SoundPickerDelegate> {
	UISwitch* _switchOnOff; 
	UISwitch* _switchAlerts; 
	WAActivityLabel* _activityLabel; 
	NSManagedObjectID* _chatSessionID; 
	NSString* _tempSound; 
	int _tag; 
	int _iPodPlaybackState; 
	BOOL _activityInProgress; 
	id<GroupSettingsViewControllerDelegate> _delegate; 
}
@property (nonatomic,copy) BOOL activityInProgress; 				//@synthesize activityInProgress=_activityInProgress - In the implementation block
@property (assign,nonatomic) id<GroupSettingsViewControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
+(id)controllerWithChatSessionID:(id)arg1 delegate:(id)arg2;
-(id)chatSession;
-(void)hideActivity;
-(void)soundPicker:(id)arg1 didFinishWithSound:(id)arg2;
-(void)soundPickerDidCancel:(id)arg1;
-(void)settingUpdateFinished:(id)arg1;
-(void)settingUpdateFailedWithError:(id)arg1 userData:(id)arg2;
-(void)showActivity:(id)arg1;
-(id)initWithChatSessionID:(id)arg1 delegate:(id)arg2;
-(void)updateSettingsOnServer:(int)arg1;
-(void)switchOnOffAction:(id)arg1;
-(void)switchAlertsAction:(id)arg1;
-(void)showSoundPickerController;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end