/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:03 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol GroupViewControllerDelegate
@optional
-(void)groupViewControllerDidCancel(id):arg1 ;
@required
-(void)groupViewController(id):arg1 didSelectGroupWithID(id):arg2 ;
-(void)groupViewController(id):arg1 didSelectGroupWithID(id):arg2 ;
@end
