/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UISearchBarDelegate.h>

@interface ImageSearchController : UIViewController <UISearchBarDelegate> {
	UIActivityIndicatorView* _activityIndicator; 
	UILabel* _labelNoResults; 
	UIButton* _buttonLoadMore; 
	UIView* _overlayView; 
	NSMutableArray* _imageURLs; 
	NSMutableArray* _thumbnailViews; 
	UIImageView* _highlightedImageView; 
	int _searchOffset; 
	int _resultsCount; 
	UISearchBar* _searchBar; 
	ImageListScrollView* _scrollView; 
	NSString* _preloadedSearchText; 
	id<ImageSearchControllerDelegate> _delegate; 
}
@property (nonatomic,retain) UISearchBar* searchBar; 				//@synthesize searchBar=_searchBar - In the implementation block
@property (nonatomic,retain) ImageListScrollView* scrollView; 				//@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) NSString* preloadedSearchText; 				//@synthesize preloadedSearchText=_preloadedSearchText - In the implementation block
@property (assign,nonatomic) id<ImageSearchControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)showActivity:(BOOL)arg1;
-(void)setPreloadedSearchText:(id)arg1;
-(void)fetcher:(id)arg1 finishedWithData:(id)arg2 error:(id)arg3;
-(void)loadMoreAction:(id)arg1;
-(void)doSearch:(id)arg1;
-(void)updateLayoutForCurrentOrientation;
-(void)selectMediaAtIndex:(id)arg1;
-(void)resetSearchResults;
-(void)addSearchResults:(id)arg1;
-(void)showOverlay;
-(void)hideOverlay;
-(void)clearAction:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)setScrollView:(id)arg1;
-(int)positionForBar:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2;
-(void)searchBarCancelButtonClicked:(id)arg1;
-(void)searchBarTextDidBeginEditing:(id)arg1;
-(void)searchBarTextDidEndEditing:(id)arg1;
-(void)searchBarSearchButtonClicked:(id)arg1;
-(void)setSearchBar:(id)arg1;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
@end