/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:19 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface JSONDecoder : NSObject {
	struct JKParseState* parseState; 
}
+(id)decoder;
+(id)decoderWithParseOptions:(unsigned)arg1;
-(id)objectWithData:(id)arg1 error:(id*)arg2;
-(id)initWithParseOptions:(unsigned)arg1;
-(id)objectWithUTF8String:(r*)arg1 length:(unsigned)arg2 error:(id*)arg3;
-(id)mutableObjectWithUTF8String:(r*)arg1 length:(unsigned)arg2 error:(id*)arg3;
-(id)mutableObjectWithData:(id)arg1 error:(id*)arg2;
-(id)objectWithUTF8String:(r*)arg1 length:(unsigned)arg2;
-(id)objectWithData:(id)arg1;
-(id)mutableObjectWithUTF8String:(r*)arg1 length:(unsigned)arg2;
-(id)mutableObjectWithData:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)clearCache;
@end