/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Logger : NSObject {
	unsigned _counter; 
	NSDateFormatter* _dateFormatter; 
	NSFileHandle* _fileHandle; 
	NSDate* _creationDate; 
	NSLock* _backgroundPurgeLock; 
	NSString* _activeLog; 
	NSString* _previousLog; 
}
@property (nonatomic,retain) NSString* activeLog; 				//@synthesize activeLog=_activeLog - In the implementation block
@property (nonatomic,retain) NSString* previousLog; 				//@synthesize previousLog=_previousLog - In the implementation block
+(id)sharedLogger;
-(void)write:(int)arg1 format:(id)arg2;
-(void)setPreviousLog:(id)arg1;
-(id)logsDirectory;
-(void)setActiveLog:(id)arg1;
-(id)levelFormat:(int)arg1;
-(void)createLogFile;
-(id)searchLogsAtPath:(id)arg1 fileManager:(id)arg2;
-(id)collect;
-(id)init;
-(void)flush;
-(void)purge;
-(void).cxx_destruct;
@end