/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MultilineHeaderView : UIView {
	UILabel* _labelFirstLine; 
	UILabel* _labelSecondLine; 
	UILabel* _labelActivity; 
	WADimmableButton* _buttonImage; 
	UIButton* _buttonAllView; 
	UIActivityIndicatorView* _activityIndicator; 
	int _orientation; 
	int _layoutType; 
	BOOL _showsActivity; 
	BOOL _showImage; 
	BOOL _tapable; 
	id<MultilineHeaderViewDelegate> _delegate; 
}
@property (nonatomic,retain) NSString* firstLineText; 
@property (nonatomic,retain) NSString* secondLineText; 
@property (nonatomic,retain) NSString* activityText; 
@property (nonatomic,retain) UIImage* contactImage; 
@property (assign,nonatomic) int orientation; 
@property (assign,nonatomic) int layoutType; 				//@synthesize layoutType=_layoutType - In the implementation block
@property (assign,nonatomic) BOOL showsActivity; 				//@synthesize showsActivity=_showsActivity - In the implementation block
@property (assign,nonatomic) BOOL showImage; 				//@synthesize showImage=_showImage - In the implementation block
@property (assign,nonatomic) BOOL tapable; 				//@synthesize tapable=_tapable - In the implementation block
@property (assign,nonatomic) id<MultilineHeaderViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)setFirstLineText:(id)arg1;
-(void)setShowsActivity:(BOOL)arg1;
-(void)setActivityText:(id)arg1;
-(id)firstLineFontForLayout:(int)arg1 orientation:(int)arg2;
-(id)secondLineFontForLayout:(int)arg1 orientation:(int)arg2;
-(void)buttonAllViewAnyTouch:(id)arg1;
-(void)buttonAllViewTouchUp:(id)arg1;
-(void)contactImageTapAction:(id)arg1;
-(void)setShowImage:(BOOL)arg1;
-(void)setTapable:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1 orientation:(int)arg2;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(void)setOrientation:(int)arg1;
-(id)accessibilityValue;
-(unsigned long long)accessibilityTraits;
-(BOOL)isAccessibilityElement;
-(void).cxx_destruct;
-(void)setContactImage:(id)arg1;
-(void)setSecondLineText:(id)arg1;
-(void)setLayoutType:(int)arg1;
@end