/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:53 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NoNetwokViewController : UIViewController {
	UILabel* _labelWarning; 
}
@property (nonatomic,retain) UILabel* labelWarning; 				//@synthesize labelWarning=_labelWarning - In the implementation block
-(void)setLabelWarning:(id)arg1;
-(id)init;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end