/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActionSheetDelegate.h>
#import <SoundPickerDelegate.h>

@interface NotificationsViewController : UITableViewController <UIActionSheetDelegate, SoundPickerDelegate> {
	BOOL _alertIsOn; 
	BOOL _groupAlertIsOn; 
	BOOL _showPreviewIsOn; 
	BOOL _vibrateIsOn; 
	BOOL _vibrateSwitchDisabled; 
	BOOL _soundsIsOn; 
	BOOL _soundsSwitchDisabled; 
	BOOL _popupsIsOn; 
	BOOL _popupsSwitchDisabled; 
	WAActivityLabel* _activityLabel; 
	UIView* _headerView; 
	UILabel* _headerLabel; 
	NSString* _tempSound; 
	int _pendingRequestCounter; 
	int _iPodPlaybackState; 
}
+(id)controller;
-(void)hideActivity;
-(void)soundPicker:(id)arg1 didFinishWithSound:(id)arg2;
-(void)soundPickerDidCancel:(id)arg1;
-(void)settingUpdateFinished:(id)arg1;
-(void)settingUpdateFailedWithError:(id)arg1 userData:(id)arg2;
-(void)showActivity:(id)arg1;
-(void)alertsAction:(id)arg1;
-(void)groupAlertsAction:(id)arg1;
-(void)vibrateAction:(id)arg1;
-(void)soundsAction:(id)arg1;
-(void)popupsAction:(id)arg1;
-(void)showPreviewAction:(id)arg1;
-(void)showSoundPickerController:(int)arg1;
-(void)askToResetNotificationSettigs;
-(void)resetNotificationSettings;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
-(void)applicationWillEnterForeground:(id)arg1;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void).cxx_destruct;
-(void)updateUI;
@end