/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NSKVONotifying_WAInputTextView : WAInputTextView {
}
-(void)setContentSize:(CGSize)arg1;
-(Class)class;
-(void)dealloc;
-(BOOL)_isKVOA;
@end