/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:21 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSCopying
@required
-(id)copyWithZone(*):arg1 ;
-(id)copyWithZone(*):arg1 ;
@end

@protocol NSMutableCopying
@required
-(id)mutableCopyWithZone(*):arg1 ;
-(id)mutableCopyWithZone(*):arg1 ;
@end
