/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:45 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NSStreamDelegate
@optional
-(void)stream(id):arg1 handleEvent(unsigned):arg2 ;
@end

@protocol NSURLConnectionDelegate
@optional
-(void)connection(id):arg1 didFailWithError(id):arg2 ;
-(BOOL)connectionShouldUseCredentialStorage(id):arg1 ;
-(void)connection(id):arg1 willSendRequestForAuthenticationChallenge(id):arg2 ;
-(BOOL)connection(id):arg1 canAuthenticateAgainstProtectionSpace(id):arg2 ;
-(void)connection(id):arg1 didReceiveAuthenticationChallenge(id):arg2 ;
-(void)connection(id):arg1 didCancelAuthenticationChallenge(id):arg2 ;
@end
