/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WALinkLabelDelegate.h>
#import <UIAlertViewDelegate.h>

@interface PaymentEduViewController : UIViewController <WALinkLabelDelegate, UIAlertViewDelegate> {
	UIImageView* _imageViewWallpaper; 
	UIImageView* _imageServiceInfo; 
	UILabel* _labelGreetingTop; 
	UILabel* _labelGreetingBottom; 
	WALinkLabel* _blogPostLink; 
	UIButton* _buttonContinue; 
	UIButton* _buttonPayNow; 
	UIButton* _buttonPayLater; 
	id<PaymentEduControllerDelegate> _delegate; 
}
-(void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
-(void)payNowAction:(id)arg1;
-(void)payLaterAction:(id)arg1;
-(void)continueAction:(id)arg1;
-(void)reloadServiceInfo;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
@end