/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIAlertViewDelegate.h>
#import <WALinkLabelDelegate.h>

@interface PaymentInfoViewController : UITableViewController <UIAlertViewDelegate, WALinkLabelDelegate> {
	UIView* _viewTableFooter; 
	WALinkLabel* _blogPostLink; 
	UILabel* _labelHelperText; 
}
@property (nonatomic,retain) UIView* viewTableFooter; 				//@synthesize viewTableFooter=_viewTableFooter - In the implementation block
@property (nonatomic,retain) WALinkLabel* blogPostLink; 				//@synthesize blogPostLink=_blogPostLink - In the implementation block
@property (nonatomic,retain) UILabel* labelHelperText; 				//@synthesize labelHelperText=_labelHelperText - In the implementation block
-(void)setViewTableFooter:(id)arg1;
-(void)setLabelHelperText:(id)arg1;
-(void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
-(void)setBlogPostLink:(id)arg1;
-(void)layoutTableFooter;
-(void)purchaseServiceAction;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void).cxx_destruct;
@end