/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WACountryPickerControllerDelegate.h>
#import <ProblemInputControllerDelegate.h>
#import <MFMailComposeViewControllerDelegate.h>
#import <WAPhoneNumberTextFieldDelegate.h>

@interface PhoneInputViewController : UITableViewController <WACountryPickerControllerDelegate, ProblemInputControllerDelegate, MFMailComposeViewControllerDelegate, WAPhoneNumberTextFieldDelegate> {
	CountryInfo* _selectedCountry; 
	NSMutableString* _actualPhoneNumber; 
	NSDictionary* _urlParameters; 
	UIAlertView* _phoneConfirmAlert; 
	NSString* _contextFailReason; 
	WAOverlayView* _overlayView; 
	id<PhoneInputViewControllerDelegate> _delegate; 
	BOOL _registrationUI; 
	UIView* _headerView; 
	UILabel* _labelHeaderText; 
	UIView* _footerView; 
	UILabel* _labelFooterText; 
	UIView* _viewInputFieldsContainer; 
	UIView* _viewCCodeContainer; 
	UILabel* _labelPlusSign; 
	UILabel* _labelCCode; 
	UITextField* _textFieldCode; 
	UIImageView* _imageCodeBg; 
	UIView* _viewPhoneNumberContainer; 
	WAPhoneNumberTextField* _phoneNumberTextField; 
	UIImageView* _imagePhoneBg; 
}
@property (assign,nonatomic) BOOL registrationUI; 				//@synthesize registrationUI=_registrationUI - In the implementation block
@property (nonatomic,retain) UIView* headerView; 				//@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,retain) UILabel* labelHeaderText; 				//@synthesize labelHeaderText=_labelHeaderText - In the implementation block
@property (nonatomic,retain) UIView* footerView; 				//@synthesize footerView=_footerView - In the implementation block
@property (nonatomic,retain) UILabel* labelFooterText; 				//@synthesize labelFooterText=_labelFooterText - In the implementation block
@property (nonatomic,retain) UIView* viewInputFieldsContainer; 				//@synthesize viewInputFieldsContainer=_viewInputFieldsContainer - In the implementation block
@property (nonatomic,retain) UIView* viewCCodeContainer; 				//@synthesize viewCCodeContainer=_viewCCodeContainer - In the implementation block
@property (nonatomic,retain) UILabel* labelPlusSign; 				//@synthesize labelPlusSign=_labelPlusSign - In the implementation block
@property (nonatomic,retain) UILabel* labelCCode; 				//@synthesize labelCCode=_labelCCode - In the implementation block
@property (nonatomic,retain) UITextField* textFieldCode; 				//@synthesize textFieldCode=_textFieldCode - In the implementation block
@property (nonatomic,retain) UIImageView* imageCodeBg; 				//@synthesize imageCodeBg=_imageCodeBg - In the implementation block
@property (nonatomic,retain) UIView* viewPhoneNumberContainer; 				//@synthesize viewPhoneNumberContainer=_viewPhoneNumberContainer - In the implementation block
@property (nonatomic,retain) WAPhoneNumberTextField* phoneNumberTextField; 				//@synthesize phoneNumberTextField=_phoneNumberTextField - In the implementation block
@property (nonatomic,retain) UIImageView* imagePhoneBg; 				//@synthesize imagePhoneBg=_imagePhoneBg - In the implementation block
-(void)launchedFromUrl:(id)arg1;
-(void)cancelAction:(id)arg1;
-(void)showOverlay:(id)arg1;
-(void)deviceCheckFinishedWithResult:(id)arg1;
-(void)deviceCheckFailedWithError:(id)arg1;
-(void)doneAction:(id)arg1;
-(void)setImageCodeBg:(id)arg1;
-(void)setImagePhoneBg:(id)arg1;
-(void)setLabelFooterText:(id)arg1;
-(void)codeChangedAction:(id)arg1;
-(void)formatCodeField;
-(void)formatTitle;
-(void)validateUserInput;
-(void)resizeHelperTextLabels;
-(void)performSameDeviceCheck;
-(void)confirmNewChat;
-(void)composeEmail:(id)arg1;
-(void)requestAuthCode;
-(void)showAppStoreAlert:(id)arg1;
-(void)showContactSupportAlert:(id)arg1;
-(void)countryPicker:(id)arg1 didSelectCountry:(id)arg2;
-(void)problemInputController:(id)arg1 didFinishWithText:(id)arg2 attachment:(id)arg3;
-(void)probleminputControllerDidCancel:(id)arg1;
-(void)phoneNumberTextFieldDidChange:(id)arg1;
-(void)resetPhoneNumber;
-(id)verificationCodeFromUrl;
-(void)setRegistrationUI:(BOOL)arg1;
-(void)setLabelHeaderText:(id)arg1;
-(void)setViewInputFieldsContainer:(id)arg1;
-(void)setViewCCodeContainer:(id)arg1;
-(void)setLabelPlusSign:(id)arg1;
-(void)setLabelCCode:(id)arg1;
-(void)setTextFieldCode:(id)arg1;
-(void)setViewPhoneNumberContainer:(id)arg1;
-(void)setPhoneNumberTextField:(id)arg1;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)setHeaderView:(id)arg1;
-(void).cxx_destruct;
-(void)setFooterView:(id)arg1;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
-(id)initWithDelegate:(id)arg1;
@end