/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:07 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)actionSheet(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)actionSheet(id):arg1 didDismissWithButtonIndex(int):arg2 ;
@end

@protocol UINavigationControllerDelegate
@optional
-(void)navigationController(id):arg1 willShowViewController(id):arg2 animated(BOOL):arg3 ;
-(void)navigationController(id):arg1 didShowViewController(id):arg2 animated(BOOL):arg3 ;
-(id)navigationController(id):arg1 animationControllerForOperation(int):arg2 fromViewController(id):arg3 toViewController(id):arg4 ;
-(id)navigationController(id):arg1 interactionControllerForAnimationController(id):arg2 ;
-(unsigned)navigationControllerSupportedInterfaceOrientations(id):arg1 ;
-(int)navigationControllerPreferredInterfaceOrientationForPresentation(id):arg1 ;
@end

@protocol MFMailComposeViewControllerDelegate
@optional
-(void)mailComposeController(id):arg1 didFinishWithResult(int):arg2 error(id):arg3 ;
@end

@protocol MFMessageComposeViewControllerDelegate
@required
-(void)messageComposeViewController(id):arg1 didFinishWithResult(int):arg2 ;
-(void)messageComposeViewController(id):arg1 didFinishWithResult(int):arg2 ;
@end

@protocol PeopleMultiPickerNavigationControllerDelegate
@required
-(void)peopleMultiPickerNavigationController(id):arg1 didSelectContacts(id):arg2 ;
-(void)peopleMultiPickerNavigationControllerDidCancel(id):arg1 ;
-(void)peopleMultiPickerNavigationController(id):arg1 didSelectContacts(id):arg2 ;
-(void)peopleMultiPickerNavigationControllerDidCancel(id):arg1 ;
@end

@protocol PhoneConfirmationControllerDelegate
@required
-(void)phoneConfirmationControllerDidFinish(id):arg1 ;
-(void)phoneConfirmationControllerDidCancel(id):arg1 ;
-(void)phoneConfirmationControllerDidFinish(id):arg1 ;
-(void)phoneConfirmationControllerDidCancel(id):arg1 ;
@end
