/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PhoneNumberFormatter : NSObject {
}
+(void)initializeFormatter;
+(id)countryInfoByMCC:(id)arg1;
+(id)countryInfoByIsoCode:(id)arg1;
+(id)countryInfoByCountryCode:(id)arg1;
+(id)preferredCountries;
+(id)clearNumber:(id)arg1;
+(id)formatNumber:(id)arg1;
+(id)isoCodeFromCountryCode:(id)arg1;
+(id)formatNumber:(id)arg1 withIsoCode:(id)arg2;
+(id)countryInfoFromRawNumber:(id)arg1;
+(BOOL)nationalNumber:(id)arg1 containsLeadingDigits:(id)arg2;
+(id)formatNationalNumber:(id)arg1 withCountryInfo:(id)arg2;
+(BOOL)phoneNumber:(id)arg1 meetsMinimumLengthRequirementOfCountry:(id)arg2;
+(id)removeDigits:(int)arg1 atEndOfString:(id)arg2;
+(id)countryInfoFromNumber:(id)arg1;
+(id)allCountries;
@end