/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:20 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAPhoneNumberTextFieldDelegate.h>
#import <WACountryPickerControllerDelegate.h>

@interface PhoneConfirmationController : UIViewController <WAPhoneNumberTextFieldDelegate, WACountryPickerControllerDelegate> {
	id<PhoneConfirmationControllerDelegate> _delegate; 
	WAOverlayView* _overlayView; 
	CountryInfo* _selectedCountry; 
	UITableView* _tableView; 
	UIView* _footerView; 
	UIView* _viewInputFieldsContainer; 
	UIView* _viewCCodeContainer; 
	UILabel* _labelPlusSign; 
	UILabel* _labelCCode; 
	UITextField* _textFieldCode; 
	UIImageView* _imageCodeBg; 
	UIView* _viewPhoneNumberContainer; 
	WAPhoneNumberTextField* _phoneNumberTextField; 
	UIImageView* _imagePhoneBG; 
	UIButton* _buttonDelete; 
	UIView* _viewWarning; 
}
@property (nonatomic,retain) UITableView* tableView; 				//@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) UIView* footerView; 				//@synthesize footerView=_footerView - In the implementation block
@property (nonatomic,retain) UIView* viewInputFieldsContainer; 				//@synthesize viewInputFieldsContainer=_viewInputFieldsContainer - In the implementation block
@property (nonatomic,retain) UIView* viewCCodeContainer; 				//@synthesize viewCCodeContainer=_viewCCodeContainer - In the implementation block
@property (nonatomic,retain) UILabel* labelPlusSign; 				//@synthesize labelPlusSign=_labelPlusSign - In the implementation block
@property (nonatomic,retain) UILabel* labelCCode; 				//@synthesize labelCCode=_labelCCode - In the implementation block
@property (nonatomic,retain) UITextField* textFieldCode; 				//@synthesize textFieldCode=_textFieldCode - In the implementation block
@property (nonatomic,retain) UIImageView* imageCodeBg; 				//@synthesize imageCodeBg=_imageCodeBg - In the implementation block
@property (nonatomic,retain) UIView* viewPhoneNumberContainer; 				//@synthesize viewPhoneNumberContainer=_viewPhoneNumberContainer - In the implementation block
@property (nonatomic,retain) WAPhoneNumberTextField* phoneNumberTextField; 				//@synthesize phoneNumberTextField=_phoneNumberTextField - In the implementation block
@property (nonatomic,retain) UIImageView* imagePhoneBG; 				//@synthesize imagePhoneBG=_imagePhoneBG - In the implementation block
@property (nonatomic,retain) UIButton* buttonDelete; 				//@synthesize buttonDelete=_buttonDelete - In the implementation block
@property (nonatomic,retain) UIView* viewWarning; 				//@synthesize viewWarning=_viewWarning - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)showOverlay:(id)arg1;
-(void)setImageCodeBg:(id)arg1;
-(void)codeChangedAction:(id)arg1;
-(void)formatCodeField;
-(void)countryPicker:(id)arg1 didSelectCountry:(id)arg2;
-(void)phoneNumberTextFieldDidChange:(id)arg1;
-(void)setViewInputFieldsContainer:(id)arg1;
-(void)setViewCCodeContainer:(id)arg1;
-(void)setLabelPlusSign:(id)arg1;
-(void)setLabelCCode:(id)arg1;
-(void)setTextFieldCode:(id)arg1;
-(void)setViewPhoneNumberContainer:(id)arg1;
-(void)setPhoneNumberTextField:(id)arg1;
-(void)phoneNumberNormalized:(id)arg1 userInfo:(id)arg2;
-(void)phoneNumberNormalizationFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)validatePhoneNumber:(id)arg1;
-(void)setImagePhoneBG:(id)arg1;
-(void)setButtonDelete:(id)arg1;
-(id)warningText;
-(id)warningBulletPoints;
-(void)setViewWarning:(id)arg1;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)title;
-(void)setTableView:(id)arg1;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setFooterView:(id)arg1;
-(id)buttonTitle;
-(id)initWithDelegate:(id)arg1;
-(void)deleteAction;
-(void)keyboardWillShow:(id)arg1;
-(void)keyboardWillHide:(id)arg1;
@end