/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:27 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextViewDelegate.h>

@interface ProblemInputController : UITableViewController <UITextViewDelegate> {
	UITableViewCell* _faqCell; 
	UITableViewCell* _textViewCell; 
	UITextView* _textView; 
	WADoneWithSpinnerBarButtonItem* _doneButton; 
	struct dispatch_group_s* _logsGatheringDispatchGroup; 
	NSString* _gzippedLogs; 
	float _keyboardHeight; 
	id<ProblemInputControllerDelegate> _delegate; 
	NSString* _initialText; 
}
@property (assign,nonatomic) id<ProblemInputControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString* initialText; 				//@synthesize initialText=_initialText - In the implementation block
+(void)showControllerWithDelegate:(id)arg1 afterCheckingServerStatus:(id)arg2;
-(void)cancelAction:(id)arg1;
-(void)doneAction:(id)arg1;
-(void)updateButtonState;
-(void)viewHelpSection;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(id)initWithStyle:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)textViewDidBeginEditing:(id)arg1;
-(void)textViewDidChange:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void).cxx_destruct;
-(void)setInitialText:(id)arg1;
-(void)keyboardWillShow:(id)arg1;
@end