/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WACountryPickerControllerDelegate
@required
-(void)countryPicker(id):arg1 didSelectCountry(id):arg2 ;
-(void)countryPicker(id):arg1 didSelectCountry(id):arg2 ;
@end

@protocol ProblemInputControllerDelegate
@required
-(void)problemInputController(id):arg1 didFinishWithText(id):arg2 attachment(id):arg3 ;
-(void)probleminputControllerDidCancel(id):arg1 ;
-(void)problemInputController(id):arg1 didFinishWithText(id):arg2 attachment(id):arg3 ;
-(void)probleminputControllerDidCancel(id):arg1 ;
@end
