/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PropertyTableViewCell : UITableViewCell {
	UILabel* _labelLabel; 
	UILabel* _labelValue; 
	UILabel* _labelComment; 
	UIImageView* _imageViewStar; 
	BOOL _isFavorite; 
	BOOL _valueHighlighted; 
	BOOL _popupActive; 
	NSTimer* _popupTimer; 
}
@property (nonatomic,copy) UILabel* labelLabel; 				//@synthesize labelLabel=_labelLabel - In the implementation block
@property (nonatomic,copy) UILabel* labelValue; 				//@synthesize labelValue=_labelValue - In the implementation block
@property (nonatomic,copy) UILabel* labelComment; 				//@synthesize labelComment=_labelComment - In the implementation block
@property (assign,nonatomic) BOOL isFavorite; 
@property (assign,nonatomic) BOOL valueHighlighted; 				//@synthesize valueHighlighted=_valueHighlighted - In the implementation block
@property (nonatomic,copy) BOOL popupActive; 				//@synthesize popupActive=_popupActive - In the implementation block
+(float)heightForText:(id)arg1 withFont:(id)arg2 hasComment:(BOOL)arg3 hasStar:(BOOL)arg4 cellWidth:(float)arg5;
+(id)labelTextColorNormal;
+(id)valueTextColorNormal;
+(id)commentFont;
+(id)commentTextColorNormal;
+(id)labelTextColorSelected;
+(id)valueTextColorSelected;
+(id)commentTextColorSelected;
+(id)valueTextColorHighlighted;
+(id)valueFont;
+(id)labelFont;
-(void)setValueHighlighted:(BOOL)arg1;
-(void)showCopyPasteView:(id)arg1;
-(void)didHideMenu;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(BOOL)canBecomeFirstResponder;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void)copy:(id)arg1;
-(void).cxx_destruct;
-(void)setIsFavorite:(BOOL)arg1;
@end