/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:07 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActionSheetDelegate.h>
#import <UINavigationControllerDelegate.h>
#import <MFMailComposeViewControllerDelegate.h>
#import <MFMessageComposeViewControllerDelegate.h>
#import <PeopleMultiPickerNavigationControllerDelegate.h>
#import <PhoneConfirmationControllerDelegate.h>

@interface SettingsViewController : UITableViewController <UIActionSheetDelegate, UINavigationControllerDelegate, MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, PeopleMultiPickerNavigationControllerDelegate, PhoneConfirmationControllerDelegate> {
	NotificationsViewController* _notificationsController; 
	NSArray* _inviteMethodNames; 
	BOOL _enableClearButton; 
	BOOL _isAnimating; 
	UIActivityIndicatorView* _aiConnectionStatus; 
	UIView* _viewConnectionStatus; 
	UILabel* _labelConnectionStatus; 
}
@property (nonatomic,retain) UIActivityIndicatorView* aiConnectionStatus; 				//@synthesize aiConnectionStatus=_aiConnectionStatus - In the implementation block
@property (nonatomic,retain) UIView* viewConnectionStatus; 				//@synthesize viewConnectionStatus=_viewConnectionStatus - In the implementation block
@property (nonatomic,retain) UILabel* labelConnectionStatus; 				//@synthesize labelConnectionStatus=_labelConnectionStatus - In the implementation block
-(void)chatStorageDidDeleteChatSessions:(id)arg1;
-(void)inviteAction;
-(void)adjustConnectionStatusLabelWidth;
-(void)sendSMSInvitationTo:(id)arg1;
-(void)sendEmailInvitationTo:(id)arg1;
-(void)deselectActiveCell;
-(void)updateConnectionStatus;
-(void)setAiConnectionStatus:(id)arg1;
-(void)setViewConnectionStatus:(id)arg1;
-(void)setLabelConnectionStatus:(id)arg1;
-(void)aboutAction;
-(void)viewProfileAction;
-(void)viewAccountAction;
-(void)chatSettingsAction;
-(void)notificationsAction;
-(void)systemStatusAction;
-(void)clearChatHistoryAction;
-(void)inviteViaEmail;
-(void)inviteViaSMS;
-(void)inviteViaTwitter;
-(void)inviteViaFacebook;
-(void)inviteViaSinaWeibo;
-(void)peopleMultiPickerNavigationController:(id)arg1 didSelectContacts:(id)arg2;
-(void)peopleMultiPickerNavigationControllerDidCancel:(id)arg1;
-(void)phoneConfirmationControllerDidFinish:(id)arg1;
-(void)phoneConfirmationControllerDidCancel:(id)arg1;
-(void)xmppConnectionDidBeginConnect:(id)arg1;
-(void)xmppConnectionDidConnect:(id)arg1;
-(void)xmppConnectionDidDisconnect:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
-(void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
@end