/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:51 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SinglePersonPicker : UIViewController {
	id<SinglePersonPickerDelegate> _delegate; 
	NSArray* _sections; 
	NSArray* _searchResults; 
	NSDictionary* _selectedContact; 
	int _numberOfContacts; 
	BOOL _dataAvailable; 
	BOOL _showActionCells; 
	int _pickerMode; 
	int _tag; 
	UITableView* _tableView; 
	UILabel* _labelLoading; 
	UITableViewCell* _cellLoading; 
	UILabel* _labelNoContacts; 
	UITableViewCell* _cellNoContacts; 
}
@property (assign,nonatomic) int pickerMode; 				//@synthesize pickerMode=_pickerMode - In the implementation block
@property (assign,nonatomic) BOOL showActionCells; 				//@synthesize showActionCells=_showActionCells - In the implementation block
@property (assign,nonatomic) int tag; 				//@synthesize tag=_tag - In the implementation block
@property (nonatomic,retain) UITableView* tableView; 				//@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) UILabel* labelLoading; 				//@synthesize labelLoading=_labelLoading - In the implementation block
@property (nonatomic,retain) UITableViewCell* cellLoading; 				//@synthesize cellLoading=_cellLoading - In the implementation block
@property (nonatomic,retain) UILabel* labelNoContacts; 				//@synthesize labelNoContacts=_labelNoContacts - In the implementation block
@property (nonatomic,retain) UITableViewCell* cellNoContacts; 				//@synthesize cellNoContacts=_cellNoContacts - In the implementation block
@property (assign,nonatomic) id<SinglePersonPickerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)searchWithCriteria:(id)arg1;
-(void)saveTableScrollPosition;
-(void)restoreTableScrollPosition;
-(void)contactsStorageDidUpdateStatus:(id)arg1;
-(void)setupDisplayList;
-(void)checkDataAvailability:(id)arg1;
-(void)adjustSearchbarPositionAndTableviewInsets;
-(void)contactsStorageDidUpdateContacts:(id)arg1;
-(void)setCellNoContacts:(id)arg1;
-(void)setLabelNoContacts:(id)arg1;
-(void)setCellLoading:(id)arg1;
-(void)setLabelLoading:(id)arg1;
-(void)setPickerMode:(int)arg1;
-(void)cancelAction:(id)arg1;
-(BOOL)displaySearchBar;
-(void)updateTableHeader;
-(BOOL)displayActionButtons;
-(void)setShowActionCells:(BOOL)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(id)sectionIndexTitlesForTableView:(id)arg1;
-(int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)setTag:(int)arg1;
-(void)viewDidLayoutSubviews;
-(void)setTableView:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)searchDisplayControllerDidBeginSearch:(id)arg1;
-(void)searchDisplayControllerDidEndSearch:(id)arg1;
-(void)searchDisplayControllerWillBeginSearch:(id)arg1;
-(void)searchDisplayControllerWillEndSearch:(id)arg1;
-(BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
@end