/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SoundEffect : NSObject {
	unsigned long _soundID; 
}
+(id)soundEffectWithContentsOfFile:(id)arg1;
-(void)play;
-(void)dealloc;
-(id)initWithContentsOfFile:(id)arg1;
@end