/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:52 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextViewDelegate.h>

@interface StatusEditController : UITableViewController <UITextViewDelegate> {
	float _keyboardHeight; 
	UITableViewCell* _textViewCell; 
	UITextView* _textView; 
	id<StatusEditControllerDelegate> _delegate; 
	NSDictionary* _currentStatus; 
	NSString* _preloadedStatusText; 
}
@property (nonatomic,retain) NSDictionary* currentStatus; 				//@synthesize currentStatus=_currentStatus - In the implementation block
@property (nonatomic,retain) NSString* preloadedStatusText; 				//@synthesize preloadedStatusText=_preloadedStatusText - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)setCurrentStatus:(id)arg1;
-(void)setPreloadedStatusText:(id)arg1;
-(void)saveAction:(id)arg1;
-(void)updateNavigationBar;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)textViewDidBeginEditing:(id)arg1;
-(BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
-(void)textViewDidChange:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
-(void)keyboardWillShow:(id)arg1;
@end