/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:54 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol StatusEditControllerDelegate
@required
-(void)statusEditController(id):arg1 didAddStatus(id):arg2 ;
-(void)statusEditController(id):arg1 didSaveStatus(id):arg2 ;
-(void)statusEditControllerDidCancel(id):arg1 ;
-(void)statusEditController(id):arg1 didAddStatus(id):arg2 ;
-(void)statusEditController(id):arg1 didSaveStatus(id):arg2 ;
-(void)statusEditControllerDidCancel(id):arg1 ;
@end
