/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:53 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAStatusListEditViewControllerDelegate.h>
#import <StatusEditControllerDelegate.h>

@interface StatusListViewController : UITableViewController <WAStatusListEditViewControllerDelegate, StatusEditControllerDelegate> {
	WAProgressHUD* _progressHUD; 
	NSString* _newStatus; 
	UIView* _viewEmptyStatusList; 
	UILabel* _labelEmptyStatusList; 
	UIView* _viewTableFooter; 
	UIButton* _buttonClearStatus; 
}
@property (nonatomic,retain) UIView* viewEmptyStatusList; 				//@synthesize viewEmptyStatusList=_viewEmptyStatusList - In the implementation block
@property (nonatomic,retain) UILabel* labelEmptyStatusList; 				//@synthesize labelEmptyStatusList=_labelEmptyStatusList - In the implementation block
@property (nonatomic,retain) UIView* viewTableFooter; 				//@synthesize viewTableFooter=_viewTableFooter - In the implementation block
@property (nonatomic,retain) UIButton* buttonClearStatus; 				//@synthesize buttonClearStatus=_buttonClearStatus - In the implementation block
-(void)leaveEditMode;
-(void)showHUD:(id)arg1;
-(void)removeHUD;
-(void)setStatusSucceededWithUserData:(id)arg1;
-(void)setStatusDidFailWithError:(id)arg1 userData:(id)arg2;
-(void)editAction:(id)arg1;
-(void)addStatusAction:(id)arg1;
-(void)setViewTableFooter:(id)arg1;
-(void)setButtonClearStatus:(id)arg1;
-(void)setViewEmptyStatusList:(id)arg1;
-(void)setLabelEmptyStatusList:(id)arg1;
-(void)clearStatusAction:(id)arg1;
-(void)statusListEditViewViewControllerDidFinish:(id)arg1;
-(void)statusEditController:(id)arg1 didAddStatus:(id)arg2;
-(void)statusEditController:(id)arg1 didSaveStatus:(id)arg2;
-(void)statusEditControllerDidCancel:(id)arg1;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setStatus:(id)arg1;
-(void)updateUI;
@end