/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:10 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TextMessage : NSObject {
	struct __CFAttributedString* _attributedString; 
	struct __CTFramesetter* _framesetter; 
	BOOL _dataDetectionEnabled; 
	unsigned char _alignment; 
	NSString* _text; 
	UIFont* _font; 
	UIColor* _textColor; 
	UIColor* _urlColor; 
	UIColor* _highlightedUrlColor; 
	UIColor* _urlBackgroundColor; 
	UIColor* _shadowColor; 
	NSArray* _textBlocks; 
	CGSize _shadowOffset; 
	CGSize _size; 
}
@property (assign,nonatomic) BOOL dataDetectionEnabled; 				//@synthesize dataDetectionEnabled=_dataDetectionEnabled - In the implementation block
@property (nonatomic,retain) NSString* text; 				//@synthesize text=_text - In the implementation block
@property (nonatomic,retain) UIFont* font; 				//@synthesize font=_font - In the implementation block
@property (nonatomic,retain) UIColor* textColor; 				//@synthesize textColor=_textColor - In the implementation block
@property (nonatomic,retain) UIColor* urlColor; 				//@synthesize urlColor=_urlColor - In the implementation block
@property (nonatomic,retain) UIColor* highlightedUrlColor; 				//@synthesize highlightedUrlColor=_highlightedUrlColor - In the implementation block
@property (nonatomic,retain) UIColor* urlBackgroundColor; 				//@synthesize urlBackgroundColor=_urlBackgroundColor - In the implementation block
@property (assign,nonatomic) unsigned char alignment; 				//@synthesize alignment=_alignment - In the implementation block
@property (nonatomic,retain) UIColor* shadowColor; 				//@synthesize shadowColor=_shadowColor - In the implementation block
@property (assign,nonatomic) CGSize shadowOffset; 				//@synthesize shadowOffset=_shadowOffset - In the implementation block
@property (nonatomic,retain) NSArray* textBlocks; 				//@synthesize textBlocks=_textBlocks - In the implementation block
@property (nonatomic,copy) CGSize size; 				//@synthesize size=_size - In the implementation block
-(void)setDataDetectionEnabled:(BOOL)arg1;
-(void)setHighlightedUrlColor:(id)arg1;
-(void)setUrlColor:(id)arg1;
-(void)setNeedsRedraw;
-(void)setUrlBackgroundColor:(id)arg1;
-(CGSize)sizeThatFits:(CGSize)arg1 lastLineRect:(CGRect*)arg2;
-(void)drawInView:(id)arg1 rect:(CGRect)arg2 context:(struct CGContext*)arg3 lastLineRect:(CGRect*)arg4;
-(id)hitTest:(CGPoint)arg1 withPadding:(float)arg2;
-(BOOL)isStringSafe:(id)arg1;
-(id)matchesInString:(id)arg1;
-(void)prepareTextBlocks;
-(void)prepareFramesetter;
-(CGPoint)lineBoundsWithRange:(struct __CTLine*)arg1 range:(struct )arg2;
-(BOOL)needsRedrawForSetDataDetection:(BOOL)arg1;
-(void)dealloc;
-(void)setTextColor:(id)arg1;
-(void)setFont:(id)arg1;
-(void)setText:(id)arg1;
-(void)setAlignment:(unsigned char)arg1;
-(void)setShadowColor:(id)arg1;
-(void)setShadowOffset:(CGSize)arg1;
-(void).cxx_destruct;
-(id)initWithText:(id)arg1;
-(void)setTextBlocks:(id)arg1;
@end