/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TextRect : NSObject {
	int _line; 
	struct _NSRange _range; 
	CGRect _rect; 
}
@property (assign,nonatomic) CGRect rect; 				//@synthesize rect=_rect - In the implementation block
@property (assign,nonatomic) struct _NSRange range; 				//@synthesize range=_range - In the implementation block
@property (assign,nonatomic) int line; 				//@synthesize line=_line - In the implementation block
+(id)rectWithRect:(CGRect)arg1 range:(struct _NSRange)arg2;
-(id)initWithRect:(CGRect)arg1 range:(struct _NSRange)arg2;
-(void)setRect:(CGRect)arg1;
-(void)setLine:(int)arg1;
-(void)setRange:(struct _NSRange)arg1;
@end