/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TextBlock : NSObject {
	NSMutableArray* _textRects; 
	BOOL _highlighted; 
	NSString* _text; 
	NSString* _url; 
	id _data; 
	struct _NSRange _range; 
	unsigned long long _type; 
}
@property (assign,nonatomic) struct _NSRange range; 				//@synthesize range=_range - In the implementation block
@property (nonatomic,retain) NSString* text; 				//@synthesize text=_text - In the implementation block
@property (nonatomic,retain) NSString* url; 				//@synthesize url=_url - In the implementation block
@property (nonatomic,retain) id data; 				//@synthesize data=_data - In the implementation block
@property (assign,nonatomic) unsigned long long type; 				//@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL highlighted; 				//@synthesize highlighted=_highlighted - In the implementation block
+(id)blockWithRange:(struct _NSRange)arg1 text:(id)arg2;
-(id)initWithRange:(struct _NSRange)arg1 text:(id)arg2;
-(void)addTextRect:(id)arg1;
-(void)deleteAllTextRects;
-(void)setType:(unsigned long long)arg1;
-(void)setText:(id)arg1;
-(void)setData:(id)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)setUrl:(id)arg1;
-(void).cxx_destruct;
-(void)setRange:(struct _NSRange)arg1;
-(id)textRects;
@end