/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TimePeriodFormatter : NSNumberFormatter {
}
+(id)formatWithAppropriateTimeUnit:(long)arg1;
+(id)pluralSeconds:(int)arg1;
+(id)pluralMinutes:(int)arg1;
+(id)pluralHours:(int)arg1;
+(id)pluralDays:(int)arg1;
+(id)pluralMonths:(int)arg1;
+(id)pluralYears:(int)arg1;
-(id)stringFromTimeInterval:(double)arg1;
@end