/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:30 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TwoLineTableViewCell : UITableViewCell {
}
+(float)heightWithText:(id)arg1 textFont:(id)arg2 detailText:(id)arg3 detailTextFont:(id)arg4 forWidth:(float)arg5;
-(void)layoutSubviews;
@end