/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:40 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIActivityItemSource
@optional
-(id)activityViewController(id):arg1 subjectForActivityType(id):arg2 ;
-(id)activityViewController(id):arg1 dataTypeIdentifierForActivityType(id):arg2 ;
-(id)activityViewController(id):arg1 thumbnailImageForActivityType(id):arg2 suggestedSize({):arg3 ;
@required
-(id)activityViewControllerPlaceholderItem(id):arg1 ;
-(id)activityViewController(id):arg1 itemForActivityType(id):arg2 ;
-(id)activityViewControllerPlaceholderItem(id):arg1 ;
-(id)activityViewController(id):arg1 itemForActivityType(id):arg2 ;
@end
