/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:26 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIImagePickerControllerDelegate
@optional
-(void)imagePickerControllerDidCancel(id):arg1 ;
-(void)imagePickerController(id):arg1 didFinishPickingMediaWithInfo(id):arg2 ;
-(void)imagePickerController(id):arg1 didFinishPickingImage(id):arg2 editingInfo(id):arg3 ;
@end
