/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UISearchBarDelegate
@optional
-(void)searchBar(id):arg1 textDidChange(id):arg2 ;
-(void)searchBar(id):arg1 selectedScopeButtonIndexDidChange(int):arg2 ;
-(BOOL)searchBarShouldBeginEditing(id):arg1 ;
-(BOOL)searchBarShouldEndEditing(id):arg1 ;
-(void)searchBarCancelButtonClicked(id):arg1 ;
-(void)searchBarBookmarkButtonClicked(id):arg1 ;
-(void)searchBarResultsListButtonClicked(id):arg1 ;
-(void)searchBarTextDidBeginEditing(id):arg1 ;
-(void)searchBarTextDidEndEditing(id):arg1 ;
-(void)searchBarSearchButtonClicked(id):arg1 ;
-(BOOL)searchBar(id):arg1 shouldChangeTextInRange({):arg2 replacementText(_):arg3 ;
@end
