/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UISearchBarDelegate
@optional
-(void)searchBar(id):arg1 textDidChange(id):arg2 ;
-(void)searchBar(id):arg1 selectedScopeButtonIndexDidChange(int):arg2 ;
-(BOOL)searchBarShouldBeginEditing(id):arg1 ;
-(BOOL)searchBarShouldEndEditing(id):arg1 ;
-(void)searchBarCancelButtonClicked(id):arg1 ;
-(void)searchBarBookmarkButtonClicked(id):arg1 ;
-(void)searchBarResultsListButtonClicked(id):arg1 ;
-(void)searchBarTextDidBeginEditing(id):arg1 ;
-(void)searchBarTextDidEndEditing(id):arg1 ;
-(void)searchBarSearchButtonClicked(id):arg1 ;
-(BOOL)searchBar(id):arg1 shouldChangeTextInRange({):arg2 replacementText(_):arg3 ;
@end

@protocol UISearchDisplayDelegate
@optional
-(void)searchDisplayController(id):arg1 willUnloadSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willHideSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didHideSearchResultsTableView(id):arg2 ;
-(void)searchDisplayControllerDidBeginSearch(id):arg1 ;
-(void)searchDisplayControllerDidEndSearch(id):arg1 ;
-(void)searchDisplayControllerWillBeginSearch(id):arg1 ;
-(void)searchDisplayControllerWillEndSearch(id):arg1 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchString(id):arg2 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchScope(int):arg2 ;
-(void)searchDisplayController(id):arg1 didLoadSearchResultsTableView(id):arg2 ;
@end
