/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIVideoEditorControllerDelegate
@optional
-(void)videoEditorControllerDidCancel(id):arg1 ;
-(void)videoEditorController(id):arg1 didSaveEditedVideoToPath(id):arg2 ;
-(void)videoEditorController(id):arg1 didFailWithError(id):arg2 ;
@end
