/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface URLQueryProcessor : NSObject {
}
+(id)dictionaryFromQueryString:(id)arg1;
+(BOOL)validateRegistrationQueryComponents:(id)arg1;
+(BOOL)isOnlyDigits:(id)arg1;
@end