/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:00 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface UserFSFile : UserFSItem {
}
-(BOOL)isDirectory;
-(id)openStreamWithOptions:(unsigned)arg1 error:(id*)arg2;
@end