/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MKMapViewDelegate.h>
#import <MKReverseGeocoderDelegate.h>
#import <CLLocationManagerDelegate.h>
#import <UIActionSheetDelegate.h>
#import <ABPersonViewControllerDelegate.h>

@interface UserLocationViewController : UIViewController <MKMapViewDelegate, MKReverseGeocoderDelegate, CLLocationManagerDelegate, UIActionSheetDelegate, ABPersonViewControllerDelegate> {
	UISegmentedControl* _segmentedControl; 
	UIBarButtonItem* _barButtonSearch; 
	UIBarButtonItem* _barButtonAction; 
	UIBarButtonItem* _segmentedControlBarItem; 
	UIImageView* _noMediaImage; 
	UILabel* _noMediaLabelTitle; 
	UILabel* _noMediaLabelText; 
	MultilineHeaderView* _headerView; 
	MKReverseGeocoder* _reverseGeocoder; 
	CLLocationManager* _locationManager; 
	CLLocation* _currentLocation; 
	NSMutableArray* _annotations; 
	NSMutableArray* _supportedMapsURLs; 
	int _regionType; 
	int _locationIndex; 
	double _zoomLevel; 
	BOOL _showMyLocation; 
	BOOL _singleLocation; 
	MKMapView* _mapViewMain; 
	UIToolbar* _toolbar; 
	id<WALocationDataSource> _dataSource; 
}
@property (nonatomic,retain) MKMapView* mapViewMain; 				//@synthesize mapViewMain=_mapViewMain - In the implementation block
@property (nonatomic,retain) UIToolbar* toolbar; 				//@synthesize toolbar=_toolbar - In the implementation block
@property (assign,nonatomic) BOOL showMyLocation; 				//@synthesize showMyLocation=_showMyLocation - In the implementation block
@property (assign,nonatomic) BOOL singleLocation; 				//@synthesize singleLocation=_singleLocation - In the implementation block
@property (assign,nonatomic) id<WALocationDataSource> dataSource; 				//@synthesize dataSource=_dataSource - In the implementation block
-(void)updateLayoutToOrientation:(int)arg1;
-(id)findFirstGroupingWithAnnotations:(id)arg1;
-(void)mapAction:(id)arg1;
-(void)searchAction:(id)arg1;
-(void)mapTypeChanged:(id)arg1;
-(void)updateToolbar;
-(void)updateAnnotationsWithCurrentLocation;
-(void)reloadAnnotations;
-(void)updateMapRegion;
-(void)setMapViewMain:(id)arg1;
-(void)directionsToHere;
-(void)addToContacts;
-(id)initWithLocationDataSource:(id)arg1;
-(void)setShowMyLocation:(BOOL)arg1;
-(void)setSingleLocation:(BOOL)arg1;
-(BOOL)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
-(void)reverseGeocoder:(id)arg1 didFailWithError:(id)arg2;
-(void)reverseGeocoder:(id)arg1 didFindPlacemark:(id)arg2;
-(void)setDataSource:(id)arg1;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)setToolbar:(id)arg1;
-(void).cxx_destruct;
-(void)updateNavBar;
-(void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
-(void)locationManager:(id)arg1 didFailWithError:(id)arg2;
-(void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
-(void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
@end