/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PhoneInputViewControllerDelegate.h>
#import <PassInputViewControllerDelegate.h>
#import <ProfileViewControllerDelegate.h>
#import <RestoreBackupViewControllerDelegate.h>
#import <ChangeConfirmationControllerDelegate.h>
#import <ChangeNumberInputControllerDelegate.h>
#import <PaymentEduControllerDelegate.h>
#import <WAAutobackupSettingsViewControllerDelegate.h>

@interface VerificationController : WAModalNavigationController <PhoneInputViewControllerDelegate, PassInputViewControllerDelegate, ProfileViewControllerDelegate, RestoreBackupViewControllerDelegate, ChangeConfirmationControllerDelegate, ChangeNumberInputControllerDelegate, PaymentEduControllerDelegate, WAAutobackupSettingsViewControllerDelegate> {
	PhoneInputViewController* _phoneInputController; 
	PassInputViewController* _passInputController; 
	iPadNoticeViewController* _iPadNoticeController; 
	ProfileViewController* _profileViewController; 
	RestoreBackupViewController* _restoreBackupViewController; 
	PaymentEduViewController* _paymentEduViewController; 
	WAAutobackupSettingsViewController* _autobackupSettingsController; 
	int _mode; 
}
@property (nonatomic,copy) int mode; 				//@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) id<VerificationControllerDelegate><UINavigationControllerDelegate> delegate; 
+(BOOL)validateProfileAndSettingsOnUpgrade;
+(void)updateDefaultsAndKeychain:(id)arg1 password:(id)arg2;
+(BOOL)autobackupOff;
+(BOOL)pushNameAndProfilePhotoAreValid;
+(void)cancelPhoneNumberChange;
-(void)phoneInputViewControllerDidEnterPhone:(id)arg1;
-(void)phoneInputViewControllerDidFinish:(id)arg1;
-(void)resetPhoneNumber;
-(void)passInputViewControllerDidFinish:(id)arg1;
-(void)passInputViewControllerDidCancel:(id)arg1;
-(id)iPadNoticeController;
-(id)restoreBackupViewController;
-(id)paymentEduViewController;
-(id)autobackupSettingsController;
-(id)profileViewController;
-(id)phoneInputController;
-(id)passInputController;
-(void)goToPaymentEducationScreen:(id)arg1;
-(void)goToProfileScreen:(id)arg1;
-(void)verifiedAfterInstallGoToNextScreen:(id)arg1;
-(void)profileViewControllerDidFinish:(id)arg1;
-(void)restoreBackupViewControllerDidFinish:(id)arg1;
-(void)changeConfirmationControllerDidFinish:(id)arg1;
-(void)changeConfirmationControllerDidCancel:(id)arg1;
-(void)changeNumberInputControllerDidFinish:(id)arg1;
-(void)changeNumberInputControllerDidEnterPhone:(id)arg1;
-(void)changeNumberInputControllerDidCancel:(id)arg1;
-(void)paymentEduControllerDidFinish:(id)arg1;
-(void)autobackupSettingsControllerDidFinish:(id)arg1;
-(id)initWithMode:(int)arg1;
-(id)init;
-(id)popViewControllerAnimated:(BOOL)arg1;
-(void)pushViewController:(id)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end