/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VerificationEncrypter : NSObject {
}
+(id)readRecoveryTokenFromKeychain;
+(id)recoveryToken:(id)arg1;
+(BOOL)setRecoveryToken:(id)arg1 phoneNumber:(id)arg2;
+(id)generateRecoveryToken;
+(id)saltAndEncryptData:(id)arg1 saltLength:(int)arg2 encodedSecret:(id)arg3 phoneNumberSecret:(id)arg4;
+(id)decryptData:(id)arg1 saltLength:(int)arg2 encodedSecret:(id)arg3 phoneNumberSecret:(id)arg4;
+(id)recoveryToken;
+(BOOL)setRecoveryToken:(id)arg1;
+(void)removeRecoveryTokenFile;
+(id)randomDataOfLength:(unsigned long)arg1;
+(id)key:(id)arg1 encodedSecret:(id)arg2 phoneNumberSecret:(id)arg3;
+(id)abbreviatedPhoneNumber:(id)arg1;
+(id)recoveryTokenFilePath;
+(id)readRecoveryTokenFromFile:(id)arg1;
+(void)writeRecoveryTokenToKeychain:(id)arg1;
+(BOOL)writeRecoveryTokenToFile:(id)arg1 ccAndPhoneNumber:(id)arg2;
+(void)deleteRecoveryToken;
@end