/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAActivityLabel : UIView {
	UIActivityIndicatorView* _activityIndicator; 
	UILabel* _label; 
}
@property (nonatomic,retain) NSString* text; 
-(id)initWithFrame:(CGRect)arg1 text:(id)arg2;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)setText:(id)arg1;
-(void).cxx_destruct;
@end