/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAAnimatedCancelLabel : UIView {
	UILabel* _label; 
	UIImageView* _slideArrow; 
	BOOL _animating; 
	CALayer* _maskLayer; 
}
@property (nonatomic,copy) NSString* text; 
+(id)labelFontOfSize:(float)arg1;
+(float)defaultFontSize;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)setText:(id)arg1;
-(BOOL)isAnimating;
-(void)stopAnimating;
-(void)startAnimating;
-(void).cxx_destruct;
@end