/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAAnimatedGearsView : UIView {
	BOOL _animating; 
	UIImageView* _gearsBase; 
	UIImageView* _animatedGears; 
	UIImageView* _innerGear; 
	UIImageView* _outerGear; 
	UIImageView* _outerGearShadow; 
}
+(CGSize)baseSize;
-(void)configure;
-(void)configureForLegacyOS;
-(id)initWithFrame:(CGRect)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)awakeFromNib;
-(BOOL)isAnimating;
-(void)stopAnimating;
-(void)startAnimating;
-(void).cxx_destruct;
@end