/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAAutoCropImageView : UIImageView {
	float _cropInset; 
	CGPoint _focusPoint; 
}
@property (assign,nonatomic) CGPoint focusPoint; 				//@synthesize focusPoint=_focusPoint - In the implementation block
@property (assign,nonatomic) float cropInset; 				//@synthesize cropInset=_cropInset - In the implementation block
@property (nonatomic,copy) CGRect contentsRect; 
-(void)setFocusPoint:(CGPoint)arg1;
-(void)setCropInset:(float)arg1;
-(void)updateContentsRect;
-(id)initWithFrame:(CGRect)arg1;
-(void)setImage:(id)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)setBounds:(CGRect)arg1;
-(id)actionForLayer:(id)arg1 forKey:(id)arg2;
@end