/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:48 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAAutobackupSettingsViewController : UITableViewController {
	NSString* _helperTextString; 
	UIFont* _helperTextFont; 
	BOOL _verificationMode; 
	id<WAAutobackupSettingsViewControllerDelegate> _delegate; 
	int _selectedIndex; 
	UIView* _viewTableFooter; 
	UIWebView* _labelBottomHelperText; 
	UIView* _viewTableHeader; 
	UILabel* _labelTopHelperText; 
	UIImageView* _imageBackupLogo; 
}
@property (assign,nonatomic) id<WAAutobackupSettingsViewControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL verificationMode; 				//@synthesize verificationMode=_verificationMode - In the implementation block
@property (assign,nonatomic) int selectedIndex; 				//@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (nonatomic,retain) UIView* viewTableFooter; 				//@synthesize viewTableFooter=_viewTableFooter - In the implementation block
@property (nonatomic,retain) UIWebView* labelBottomHelperText; 				//@synthesize labelBottomHelperText=_labelBottomHelperText - In the implementation block
@property (nonatomic,retain) UIView* viewTableHeader; 				//@synthesize viewTableHeader=_viewTableHeader - In the implementation block
@property (nonatomic,retain) UILabel* labelTopHelperText; 				//@synthesize labelTopHelperText=_labelTopHelperText - In the implementation block
@property (nonatomic,retain) UIImageView* imageBackupLogo; 				//@synthesize imageBackupLogo=_imageBackupLogo - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)doneAction:(id)arg1;
-(void)setViewTableHeader:(id)arg1;
-(void)setViewTableFooter:(id)arg1;
-(void)setVerificationMode:(BOOL)arg1;
-(id)helperTextString;
-(id)topHelperHTMLFromString:(id)arg1 withFont:(id)arg2;
-(void)nextAction:(id)arg1;
-(void)setImageBackupLogo:(id)arg1;
-(void)setLabelTopHelperText:(id)arg1;
-(void)setLabelBottomHelperText:(id)arg1;
-(void)layoutHeaderView;
-(void)layoutFooterView;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)didReceiveMemoryWarning;
-(id)initWithStyle:(int)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)setSelectedIndex:(int)arg1;
-(void).cxx_destruct;
@end