/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:38 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WABackupInfoTableCell : UITableViewCell {
	WAAnimatedGearsView* _gearsView; 
	UILabel* _labelBackupDetails; 
	UILabel* _labelHelperText; 
}
@property (nonatomic,copy) WAAnimatedGearsView* gearsView; 				//@synthesize gearsView=_gearsView - In the implementation block
@property (nonatomic,copy) UILabel* labelBackupDetails; 				//@synthesize labelBackupDetails=_labelBackupDetails - In the implementation block
@property (nonatomic,copy) UILabel* labelHelperText; 				//@synthesize labelHelperText=_labelHelperText - In the implementation block
+(float)hPadding;
+(float)heightForRowInTable:(id)arg1 withHelperText:(id)arg2 withFont:(id)arg3 lineBreakMode:(int)arg4;
+(float)topPadding;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void).cxx_destruct;
@end