/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:26 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIImagePickerControllerDelegate.h>
#import <UINavigationControllerDelegate.h>
#import <ABPeoplePickerNavigationControllerDelegate.h>
#import <ShareLocationControllerDelegate.h>
#import <WAMediaUploaderDelegate.h>

@interface WABCastMessageComposer : UIViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, ShareLocationControllerDelegate, WAMediaUploaderDelegate> {
	id<WABCastMessageComposerDelegate> _delegate; 
	ChatHeaderView* _headerView; 
	float _keyboardHeight; 
	BOOL _disableSendButton; 
	BOOL _hideThumbFrame; 
	BOOL _thumbnailRequestInProgress; 
	BOOL _placeDetailsRequestInProgress; 
	BOOL _locationRequestInProgress; 
	NSMutableDictionary* _mediaInfo; 
	WAMediaUploader* _mediaUploader; 
	UIImage* _thumbnailPortrait; 
	UIImage* _thumbnailLandscape; 
	NSString* _boldFontName; 
	NSString* _regularFontName; 
	UITableView* _tableViewMessage; 
	UITableViewCell* _cellMessageInput; 
	UITextView* _textViewMessage; 
	UIView* _viewMediaPanelPortrait; 
	UIView* _viewButtonsPortrait; 
	UIView* _viewAttachedMediaPortrait; 
	UIImageView* _imageViewThumbFramePortrait; 
	UIImageView* _imageViewThumbnailPortrait; 
	UIActivityIndicatorView* _aiMediaPortrait; 
	UILabel* _labelMediaInfoPortrait; 
	UILabel* _labelMediaDetailsPortrait; 
	UIProgressView* _progressViewPortrait; 
	UIButton* _buttonRemoveAttachmentPortrait; 
	UIView* _viewMediaPanelLandscape; 
	UIView* _viewButtonsLandscape; 
	UIView* _viewAttachedMediaLandscape; 
	UIImageView* _imageViewThumbFrameLandscape; 
	UIImageView* _imageViewThumbnailLandscape; 
	UIActivityIndicatorView* _aiMediaLandscape; 
	UILabel* _labelMediaInfoLandscape; 
	UILabel* _labelMediaDetailsLandscape; 
	UIProgressView* _progressViewLandscape; 
	UIButton* _buttonRemoveAttachmentLandscape; 
	NSString* _recipientsTitle; 
}
@property (nonatomic,retain) UITableView* tableViewMessage; 				//@synthesize tableViewMessage=_tableViewMessage - In the implementation block
@property (nonatomic,retain) UITableViewCell* cellMessageInput; 				//@synthesize cellMessageInput=_cellMessageInput - In the implementation block
@property (nonatomic,retain) UITextView* textViewMessage; 				//@synthesize textViewMessage=_textViewMessage - In the implementation block
@property (nonatomic,retain) UIView* viewMediaPanelPortrait; 				//@synthesize viewMediaPanelPortrait=_viewMediaPanelPortrait - In the implementation block
@property (nonatomic,retain) UIView* viewButtonsPortrait; 				//@synthesize viewButtonsPortrait=_viewButtonsPortrait - In the implementation block
@property (nonatomic,retain) UIView* viewAttachedMediaPortrait; 				//@synthesize viewAttachedMediaPortrait=_viewAttachedMediaPortrait - In the implementation block
@property (nonatomic,retain) UIImageView* imageViewThumbFramePortrait; 				//@synthesize imageViewThumbFramePortrait=_imageViewThumbFramePortrait - In the implementation block
@property (nonatomic,retain) UIImageView* imageViewThumbnailPortrait; 				//@synthesize imageViewThumbnailPortrait=_imageViewThumbnailPortrait - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView* aiMediaPortrait; 				//@synthesize aiMediaPortrait=_aiMediaPortrait - In the implementation block
@property (nonatomic,retain) UILabel* labelMediaInfoPortrait; 				//@synthesize labelMediaInfoPortrait=_labelMediaInfoPortrait - In the implementation block
@property (nonatomic,retain) UILabel* labelMediaDetailsPortrait; 				//@synthesize labelMediaDetailsPortrait=_labelMediaDetailsPortrait - In the implementation block
@property (nonatomic,retain) UIProgressView* progressViewPortrait; 				//@synthesize progressViewPortrait=_progressViewPortrait - In the implementation block
@property (nonatomic,retain) UIButton* buttonRemoveAttachmentPortrait; 				//@synthesize buttonRemoveAttachmentPortrait=_buttonRemoveAttachmentPortrait - In the implementation block
@property (nonatomic,retain) UIView* viewMediaPanelLandscape; 				//@synthesize viewMediaPanelLandscape=_viewMediaPanelLandscape - In the implementation block
@property (nonatomic,retain) UIView* viewButtonsLandscape; 				//@synthesize viewButtonsLandscape=_viewButtonsLandscape - In the implementation block
@property (nonatomic,retain) UIView* viewAttachedMediaLandscape; 				//@synthesize viewAttachedMediaLandscape=_viewAttachedMediaLandscape - In the implementation block
@property (nonatomic,retain) UIImageView* imageViewThumbFrameLandscape; 				//@synthesize imageViewThumbFrameLandscape=_imageViewThumbFrameLandscape - In the implementation block
@property (nonatomic,retain) UIImageView* imageViewThumbnailLandscape; 				//@synthesize imageViewThumbnailLandscape=_imageViewThumbnailLandscape - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView* aiMediaLandscape; 				//@synthesize aiMediaLandscape=_aiMediaLandscape - In the implementation block
@property (nonatomic,retain) UILabel* labelMediaInfoLandscape; 				//@synthesize labelMediaInfoLandscape=_labelMediaInfoLandscape - In the implementation block
@property (nonatomic,retain) UILabel* labelMediaDetailsLandscape; 				//@synthesize labelMediaDetailsLandscape=_labelMediaDetailsLandscape - In the implementation block
@property (nonatomic,retain) UIProgressView* progressViewLandscape; 				//@synthesize progressViewLandscape=_progressViewLandscape - In the implementation block
@property (nonatomic,retain) UIButton* buttonRemoveAttachmentLandscape; 				//@synthesize buttonRemoveAttachmentLandscape=_buttonRemoveAttachmentLandscape - In the implementation block
@property (nonatomic,retain) NSString* recipientsTitle; 				//@synthesize recipientsTitle=_recipientsTitle - In the implementation block
-(void)addContactAction:(id)arg1;
-(void)xmppConnectionDidBeginConnect:(id)arg1;
-(void)xmppConnectionDidConnect:(id)arg1;
-(void)xmppConnectionDidDisconnect:(id)arg1;
-(void)cancelAction:(id)arg1;
-(void)locationRequestFinishedWithLocation:(id)arg1 userInfo:(id)arg2;
-(void)locationRequestFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)mediaUploaderDidFinish:(id)arg1;
-(void)mediaUploaderDidCancel:(id)arg1;
-(void)mediaUploader:(id)arg1 didFailWithError:(id)arg2;
-(void)mediaUploader:(id)arg1 uploadProgressChanged:(float)arg2;
-(void)shareLocationControllerDidSelectWAPlace:(id)arg1;
-(void)updateLayoutForCurrentOrientation;
-(void)shareLocationControllerDidCancel:(id)arg1;
-(void)setRecipientsTitle:(id)arg1;
-(id)boldFontName;
-(id)regularFontName;
-(void)cancelUploadAction:(id)arg1;
-(void)highlightCancelButton;
-(void)showAttachMediaButtons;
-(void)updateButtons;
-(void)layoutAttachedMediaUI;
-(void)reallyAttachVideo:(id)arg1 copyToTempDir:(BOOL)arg2;
-(void)sendAction:(id)arg1;
-(void)setTableViewMessage:(id)arg1;
-(void)setCellMessageInput:(id)arg1;
-(void)setTextViewMessage:(id)arg1;
-(void)setViewMediaPanelPortrait:(id)arg1;
-(void)setViewButtonsPortrait:(id)arg1;
-(void)setViewAttachedMediaPortrait:(id)arg1;
-(void)setImageViewThumbnailPortrait:(id)arg1;
-(void)setAiMediaPortrait:(id)arg1;
-(void)setLabelMediaInfoPortrait:(id)arg1;
-(void)setLabelMediaDetailsPortrait:(id)arg1;
-(void)setProgressViewPortrait:(id)arg1;
-(void)setButtonRemoveAttachmentPortrait:(id)arg1;
-(void)setViewMediaPanelLandscape:(id)arg1;
-(void)setViewAttachedMediaLandscape:(id)arg1;
-(void)setImageViewThumbnailLandscape:(id)arg1;
-(void)setAiMediaLandscape:(id)arg1;
-(void)setLabelMediaInfoLandscape:(id)arg1;
-(void)setLabelMediaDetailsLandscape:(id)arg1;
-(void)setProgressViewLandscape:(id)arg1;
-(void)setButtonRemoveAttachmentLandscape:(id)arg1;
-(void)attachImage:(id)arg1;
-(void)attachVideo:(id)arg1 copyToTempDir:(BOOL)arg2;
-(void)attachContact:(void*)arg1;
-(void)locationThumbnailFetchFinishedWithImage:(id)arg1 userInfo:(id)arg2;
-(void)locationThumbnailFetchFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)placeDetailsFetchFinished:(id)arg1 userInfo:(id)arg2;
-(void)placeDetailsFetchFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)addFromCameraAction:(id)arg1;
-(void)addFromLibraryAction:(id)arg1;
-(void)addLocationAction:(id)arg1;
-(void)shareLocationControllerDidSelectLocation:(id)arg1;
-(void)setImageViewThumbFramePortrait:(id)arg1;
-(void)setViewButtonsLandscape:(id)arg1;
-(void)setImageViewThumbFrameLandscape:(id)arg1;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
-(BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
-(void)textViewDidChange:(id)arg1;
-(void)imagePickerControllerDidCancel:(id)arg1;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
-(void).cxx_destruct;
-(void)peoplePickerNavigationControllerDidCancel:(id)arg1;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
-(id)initWithDelegate:(id)arg1;
-(void)keyboardWillShow:(id)arg1;
@end