/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:22 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WABlacklistItem : NSObject {
	NSString* _name; 
	NSString* _phoneNumber; 
	NSString* _jid; 
	NSString* _label; 
}
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString* phoneNumber; 				//@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,copy) NSString* jid; 				//@synthesize jid=_jid - In the implementation block
@property (nonatomic,copy) NSString* label; 				//@synthesize label=_label - In the implementation block
+(id)itemWithDictionary:(id)arg1;
-(void)setJid:(id)arg1;
-(void)setPhoneNumber:(id)arg1;
-(void)setName:(id)arg1;
-(void)setLabel:(id)arg1;
-(int)compare:(id)arg1;
-(void).cxx_destruct;
@end