/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:25 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WABroadcast : NSManagedObject {
}
@property (nonatomic,@dynamic,retain) NSDate* date; 
@property (nonatomic,@dynamic,retain) NSSet* messages; 
+(id)mostRecentBroadcastDateInManagedObjectContext:(id)arg1;
+(BOOL)managedObjectContextContainsBroadcasts:(id)arg1;
@end