/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:50 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIAlertViewDelegate.h>

@interface WAChatDatabaseMigrationViewController : UIViewController <UIAlertViewDelegate> {
	NSTimer* _progressTimer; 
	double _estimatedMigrationTime; 
	unsigned long long _databaseSize; 
	double _migrationStartTime; 
	WAChatStorage* _chatStorage; 
	id<WAChatDatabaseMigrationViewControllerDelegate> _delegate; 
	UIView* _viewMigrationProgress; 
	UILabel* _labelMigrationProgress; 
	UIProgressView* _progressView; 
	WACircularProgressView* _circularProgressView; 
	UILabel* _labelProgress; 
	UIView* _viewNoSpace; 
	UILabel* _labelNoSpace; 
	UIButton* _buttonTryAgain; 
}
@property (nonatomic,retain) WAChatStorage* chatStorage; 				//@synthesize chatStorage=_chatStorage - In the implementation block
@property (assign,nonatomic) id<WAChatDatabaseMigrationViewControllerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIView* viewMigrationProgress; 				//@synthesize viewMigrationProgress=_viewMigrationProgress - In the implementation block
@property (nonatomic,retain) UILabel* labelMigrationProgress; 				//@synthesize labelMigrationProgress=_labelMigrationProgress - In the implementation block
@property (nonatomic,retain) UIProgressView* progressView; 				//@synthesize progressView=_progressView - In the implementation block
@property (nonatomic,retain) WACircularProgressView* circularProgressView; 				//@synthesize circularProgressView=_circularProgressView - In the implementation block
@property (nonatomic,retain) UILabel* labelProgress; 				//@synthesize labelProgress=_labelProgress - In the implementation block
@property (nonatomic,retain) UIView* viewNoSpace; 				//@synthesize viewNoSpace=_viewNoSpace - In the implementation block
@property (nonatomic,retain) UILabel* labelNoSpace; 				//@synthesize labelNoSpace=_labelNoSpace - In the implementation block
@property (nonatomic,retain) UIButton* buttonTryAgain; 				//@synthesize buttonTryAgain=_buttonTryAgain - In the implementation block
+(id)controller;
-(void)setChatStorage:(id)arg1;
-(void)setViewMigrationProgress:(id)arg1;
-(void)setLabelMigrationProgress:(id)arg1;
-(void)setCircularProgressView:(id)arg1;
-(void)setLabelProgress:(id)arg1;
-(BOOL)hasSufficientDiskSpaceForMigration;
-(void)reallyPerformMigration;
-(void)tryAgain:(id)arg1;
-(void)setViewNoSpace:(id)arg1;
-(void)setLabelNoSpace:(id)arg1;
-(void)setButtonTryAgain:(id)arg1;
-(void)performMigration;
-(void)setDelegate:(id)arg1;
-(int)preferredStatusBarStyle;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
-(void)updateProgress:(id)arg1;
-(void)setProgressView:(id)arg1;
@end