/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:34 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAChatProperties : NSManagedObject {
}
@property (nonatomic,@dynamic,retain) NSNumber* enabled; 
@property (nonatomic,@dynamic,retain) NSString* soundName; 
@property (nonatomic,@dynamic,retain) NSNumber* alerts; 
@property (nonatomic,@dynamic,retain) NSDate* muteDate; 
@property (nonatomic,@dynamic,retain) WAChatSession* chatSession; 
@end