/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:54 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAMediaProgressDelegate.h>

@interface WAChatCellData : NSObject <WAMediaProgressDelegate> {
	NSMutableArray* _textMessages; 
	NSMutableArray* _messages; 
	BOOL _forceReload; 
	BOOL _selected; 
	BOOL _unreadAllVoice; 
	NSDate* _date; 
	int _type; 
	float _progress; 
	float _lastHeight; 
	NSNumber* _unreadCount; 
	int _pttPlayerState; 
	float _pttPlayerProgress; 
	CGSize _lastSize; 
}
@property (assign,nonatomic) BOOL forceReload; 				//@synthesize forceReload=_forceReload - In the implementation block
@property (nonatomic,copy) int type; 				//@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL selected; 				//@synthesize selected=_selected - In the implementation block
@property (assign,nonatomic) float progress; 				//@synthesize progress=_progress - In the implementation block
@property (nonatomic,copy) NSDate* date; 				//@synthesize date=_date - In the implementation block
@property (nonatomic,copy) NSArray* messages; 				//@synthesize messages=_messages - In the implementation block
@property (assign,nonatomic) float lastHeight; 				//@synthesize lastHeight=_lastHeight - In the implementation block
@property (assign,nonatomic) CGSize lastSize; 				//@synthesize lastSize=_lastSize - In the implementation block
@property (nonatomic,retain) NSNumber* unreadCount; 				//@synthesize unreadCount=_unreadCount - In the implementation block
@property (assign,nonatomic) BOOL unreadAllVoice; 				//@synthesize unreadAllVoice=_unreadAllVoice - In the implementation block
@property (assign,nonatomic) int pttPlayerState; 				//@synthesize pttPlayerState=_pttPlayerState - In the implementation block
@property (assign,nonatomic) float pttPlayerProgress; 				//@synthesize pttPlayerProgress=_pttPlayerProgress - In the implementation block
+(id)dataForMessage:(id)arg1;
+(id)divider;
-(void)fontSizeDidChange:(id)arg1;
-(int)mediaOrigin;
-(int)messageStatus;
-(id)messageTimestampString;
-(BOOL)isSenderUnknown;
-(BOOL)needToShowAlert;
-(id)fromName;
-(id)pushName;
-(id)nameColor;
-(BOOL)mediaLoading;
-(id)fullMediaPath;
-(void)uploadProgressChanged:(float)arg1 forMessage:(id)arg2;
-(void)downloadProgressChanged:(float)arg1 forMessage:(id)arg2;
-(id)vCardContactName;
-(void)setForceReload:(BOOL)arg1;
-(void)setPttPlayerProgress:(float)arg1;
-(void)setPttPlayerState:(int)arg1;
-(void)setLastHeight:(float)arg1;
-(id)dividerText;
-(BOOL)isBroadcastMessage;
-(void)addMessage:(id)arg1 addToFront:(BOOL)arg2;
-(id)messageStrings;
-(id)textMessages;
-(BOOL)permanentThumbnailAvailable;
-(id)mediaThumbnailReturningPermanentState:(BOOL*)arg1;
-(id)placeAddress;
-(id)placeURL;
-(struct)locationCoordinate;
-(id)vCardContactImage;
-(id)fullEventText;
-(void)setLastSize:(CGSize)arg1;
-(void)setUnreadAllVoice:(BOOL)arg1;
-(int)messageType;
-(void)dealloc;
-(id)initWithType:(int)arg1;
-(void)setProgress:(float)arg1;
-(void)setSelected:(BOOL)arg1;
-(void).cxx_destruct;
-(BOOL)isFromMe;
-(long long)fileSize;
-(id)shortName;
-(BOOL)isSending;
-(void)setUnreadCount:(id)arg1;
-(id)messageID;
-(id)initWithMessage:(id)arg1;
-(id)placeName;
-(CGSize)thumbnailSize;
-(id)mediaURLString;
-(BOOL)isGroupMessage;
@end