/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAChatButton : UIButton {
	BOOL _backgroundHidden; 
}
@property (assign,nonatomic) BOOL backgroundHidden; 				//@synthesize backgroundHidden=_backgroundHidden - In the implementation block
+(void)initialize;
+(id)button;
-(void)configure;
-(void)configureForLegacyOS;
-(id)initWithFrame:(CGRect)arg1;
-(void)awakeFromNib;
-(void)tintColorDidChange;
-(void)setBackgroundHidden:(BOOL)arg1;
@end