/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAChatStorageDelegate
@required
-(void)chatStorage(id):arg1 didFailWithError(id):arg2 ;
-(void)chatStorage(id):arg1 didReceiveMessage(id):arg2 ;
-(void)chatStorage(id):arg1 didUpdateChatSession(id):arg2 ;
-(void)chatStorageDidUpdateChatSessionList(id):arg1 ;
-(void)chatStorageDidDeleteChatSessions(id):arg1 ;
-(void)chatStorage(id):arg1 didAddMessages(id):arg2 ;
-(void)chatStorageDidUpdateBlacklist(id):arg1 ;
-(void)getPresenseForChatSession(id):arg1 ;
-(void)chatStorage(id):arg1 willDeleteChatSession(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteChatSessionsAtIndexes(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteMessagesInSession(id):arg2 ;
-(void)mediaUploadFailedForMessage(id):arg1 ;
-(id)UIDelegateForMessage(id):arg1 ;
-(void)chatStorage(id):arg1 didUpdateMessage(id):arg2 ;
-(void)mediaDownloadFailedForMessage(id):arg1 withError(id):arg2 autodownload(BOOL):arg3 ;
-(void)updateChatSessionWithContactData(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(id)contactForJID(id):arg1 ;
-(BOOL)isRecipientExists(id):arg1 ;
-(void)disableProfilePics;
-(void)chatStorage(id):arg1 didUpdateParticipantsOfChatSession(id):arg2 ;
-(void)chatStorageDidUpdateBroadcasts(id):arg1 ;
-(id)connection;
-(*);
-(void)chatStorage(id):arg1 didFailWithError(id):arg2 ;
-(void)chatStorage(id):arg1 didReceiveMessage(id):arg2 ;
-(void)chatStorage(id):arg1 didUpdateChatSession(id):arg2 ;
-(void)chatStorageDidUpdateChatSessionList(id):arg1 ;
-(void)chatStorageDidDeleteChatSessions(id):arg1 ;
-(void)chatStorage(id):arg1 didAddMessages(id):arg2 ;
-(void)chatStorageDidUpdateBlacklist(id):arg1 ;
-(void)getPresenseForChatSession(id):arg1 ;
-(void)chatStorage(id):arg1 willDeleteChatSession(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteChatSessionsAtIndexes(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteMessagesInSession(id):arg2 ;
-(void)mediaUploadFailedForMessage(id):arg1 ;
-(id)UIDelegateForMessage(id):arg1 ;
-(void)chatStorage(id):arg1 didUpdateMessage(id):arg2 ;
-(void)mediaDownloadFailedForMessage(id):arg1 withError(id):arg2 autodownload(BOOL):arg3 ;
-(void)updateChatSessionWithContactData(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(id)contactForJID(id):arg1 ;
-(BOOL)isRecipientExists(id):arg1 ;
-(void)disableProfilePics;
-(void)chatStorage(id):arg1 didUpdateParticipantsOfChatSession(id):arg2 ;
-(void)chatStorageDidUpdateBroadcasts(id):arg1 ;
-(id)connection;
-(*);
@end
