/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContact : NSManagedObject {
}
@property (nonatomic,@dynamic,retain) NSNumber* abUserID; 
@property (nonatomic,@dynamic,retain) NSString* fullName; 
@property (nonatomic,@dynamic,retain) NSString* firstName; 
@property (nonatomic,@dynamic,retain) NSString* indexName; 
@property (nonatomic,@dynamic,retain) NSArray* tokens; 
@property (nonatomic,@dynamic,retain) NSString* imageHash; 
@property (nonatomic,@dynamic,retain) NSNumber* sort; 
@property (nonatomic,@dynamic,retain) NSSet* phones; 
@property (nonatomic,@dynamic,retain) WAContactSection* section; 
-(id)copyContactInfo;
@end