/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:17 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfo : NSObject {
	int _addressBookID; 
	NSString* _fullName; 
	NSString* _firstName; 
	NSString* _placeholderName; 
	NSString* _jid; 
}
@property (assign,nonatomic) int addressBookID; 				//@synthesize addressBookID=_addressBookID - In the implementation block
@property (nonatomic,copy) NSString* fullName; 				//@synthesize fullName=_fullName - In the implementation block
@property (nonatomic,copy) NSString* firstName; 				//@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,copy) NSString* placeholderName; 				//@synthesize placeholderName=_placeholderName - In the implementation block
@property (nonatomic,copy) NSString* jid; 				//@synthesize jid=_jid - In the implementation block
+(id)contactInfoWithDictionary:(id)arg1;
-(void)setJid:(id)arg1;
-(void)setPlaceholderName:(id)arg1;
-(void)setAddressBookID:(int)arg1;
-(void).cxx_destruct;
-(void)setFirstName:(id)arg1;
-(void)setFullName:(id)arg1;
@end