/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoPhoneUnit : WAContactInfoUnit {
	NSManagedObjectID* _waStatusID; 
}
@property (nonatomic,copy) WAStatus* waStatus; 
@property (nonatomic,retain) NSManagedObjectID* waStatusID; 				//@synthesize waStatusID=_waStatusID - In the implementation block
+(id)contactInfoPhoneUnitForWAPhone:(id)arg1;
-(id)initWithWAPhone:(id)arg1;
-(void)setWaStatusID:(id)arg1;
-(void).cxx_destruct;
-(id)valueText;
@end