/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoUnit : NSObject {
	BOOL _multipleLines; 
	BOOL _highlighted; 
	id _value; 
	NSString* _label; 
	UIImage* _image; 
	NSString* _detailText; 
	id _action; 
}
@property (nonatomic,copy) id value; 				//@synthesize value=_value - In the implementation block
@property (nonatomic,copy) NSString* valueText; 
@property (nonatomic,copy) NSString* label; 				//@synthesize label=_label - In the implementation block
@property (nonatomic,retain) UIImage* image; 				//@synthesize image=_image - In the implementation block
@property (nonatomic,copy) NSString* detailText; 				//@synthesize detailText=_detailText - In the implementation block
@property (assign,nonatomic) BOOL multipleLines; 				//@synthesize multipleLines=_multipleLines - In the implementation block
@property (assign,nonatomic) BOOL highlighted; 				//@synthesize highlighted=_highlighted - In the implementation block
@property (nonatomic,copy) id action; 				//@synthesize action=_action - In the implementation block
+(id)contactInfoUnitForPropertyValue:(void*)arg1 index:(long)arg2;
+(id)contactInfoUnitForPropertyValue:(void*)arg1;
-(id)initWithPropertyValue:(void*)arg1 index:(long)arg2;
-(void)setMultipleLines:(BOOL)arg1;
-(void)setImage:(id)arg1;
-(void)setValue:(id)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)setAction:(id)arg1;
-(void)setLabel:(id)arg1;
-(void).cxx_destruct;
-(void)setDetailText:(id)arg1;
@end