/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoBirthdayUnit : WAContactInfoUnit {
}
+(id)dateFormatter;
-(id)initWithPropertyValue:(void*)arg1 index:(long)arg2;
-(id)valueText;
@end