/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoPhotoUnit : NSObject {
	UIImage* _image; 
}
@property (nonatomic,copy) UIImage* image; 				//@synthesize image=_image - In the implementation block
+(id)contactInfoPhotoUnitForRecord:(void*)arg1;
-(id)initWithRecord:(void*)arg1;
-(void).cxx_destruct;
@end