/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoStatusUnit : WAContactInfoUnit {
}
+(id)contactInfoStatusUnitForWAStatus:(id)arg1;
+(id)timePeriodFormatter;
-(id)initWithWAStatus:(id)arg1;
@end