/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoTableViewCell : UITableViewCell {
	NSTimer* _popupTimer; 
	BOOL _popupActive; 
	UILabel* _titleLabel; 
	UILabel* _valueLabel; 
	UILabel* _detailLabel; 
	int _cellPosition; 
	NSArray* _accessoryButtons; 
	UIButton* _leftButton; 
	UIView* _bottomEdgeView; 
}
@property (nonatomic,copy) UILabel* titleLabel; 				//@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,copy) UILabel* valueLabel; 				//@synthesize valueLabel=_valueLabel - In the implementation block
@property (nonatomic,copy) UILabel* detailLabel; 				//@synthesize detailLabel=_detailLabel - In the implementation block
@property (assign,nonatomic) int cellPosition; 				//@synthesize cellPosition=_cellPosition - In the implementation block
@property (assign,nonatomic) BOOL popupActive; 				//@synthesize popupActive=_popupActive - In the implementation block
@property (nonatomic,retain) NSArray* accessoryButtons; 				//@synthesize accessoryButtons=_accessoryButtons - In the implementation block
@property (nonatomic,retain) UIButton* leftButton; 				//@synthesize leftButton=_leftButton - In the implementation block
@property (nonatomic,copy) UIView* bottomEdgeView; 				//@synthesize bottomEdgeView=_bottomEdgeView - In the implementation block
+(float)heightForContactFieldValue:(id)arg1 multiline:(BOOL)arg2 cellPosition:(int)arg3 displayWidth:(float)arg4;
+(id)cellWithReuseIdentifier:(id)arg1;
+(id)valueLabelFont;
+(float)topInsetForCellPosition:(int)arg1;
+(float)bottomInsetForCellPosition:(int)arg1;
+(float)heightForContactInfoUnit:(id)arg1 cellPosition:(int)arg2 displayWidth:(float)arg3;
-(void)didHideMenu;
-(void)showCopyMenu:(id)arg1;
-(void)configureWithContactInfoUnit:(id)arg1;
-(void)setAccessoryButtons:(id)arg1;
-(void)setPopupActive:(BOOL)arg1;
-(void)setCellPosition:(int)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(BOOL)canBecomeFirstResponder;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)copy:(id)arg1;
-(void).cxx_destruct;
-(void)setLeftButton:(id)arg1;
@end