/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:02 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoNameUnit : NSObject {
	NSString* _prefix; 
	NSString* _firstName; 
	NSString* _phoneticFirstName; 
	NSString* _middleName; 
	NSString* _phoneticMiddleName; 
	NSString* _lastName; 
	NSString* _phoneticLastName; 
	NSString* _suffix; 
	NSString* _nickname; 
	NSString* _jobTitle; 
	NSString* _department; 
	NSString* _organization; 
	unsigned _nameFormat; 
}
@property (nonatomic,copy) NSString* prefix; 				//@synthesize prefix=_prefix - In the implementation block
@property (nonatomic,copy) NSString* firstName; 				//@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,copy) NSString* phoneticFirstName; 				//@synthesize phoneticFirstName=_phoneticFirstName - In the implementation block
@property (nonatomic,copy) NSString* middleName; 				//@synthesize middleName=_middleName - In the implementation block
@property (nonatomic,copy) NSString* phoneticMiddleName; 				//@synthesize phoneticMiddleName=_phoneticMiddleName - In the implementation block
@property (nonatomic,copy) NSString* lastName; 				//@synthesize lastName=_lastName - In the implementation block
@property (nonatomic,copy) NSString* phoneticLastName; 				//@synthesize phoneticLastName=_phoneticLastName - In the implementation block
@property (nonatomic,copy) NSString* suffix; 				//@synthesize suffix=_suffix - In the implementation block
@property (nonatomic,copy) NSString* nickname; 				//@synthesize nickname=_nickname - In the implementation block
@property (nonatomic,copy) NSString* jobTitle; 				//@synthesize jobTitle=_jobTitle - In the implementation block
@property (nonatomic,copy) NSString* department; 				//@synthesize department=_department - In the implementation block
@property (nonatomic,copy) NSString* organization; 				//@synthesize organization=_organization - In the implementation block
@property (nonatomic,copy) unsigned nameFormat; 				//@synthesize nameFormat=_nameFormat - In the implementation block
+(id)contactInfoNameUnitForRecord:(void*)arg1;
-(id)initWithRecord:(void*)arg1;
-(void).cxx_destruct;
@end