/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactInfoEditCell : UITableViewCell {
	UIView* _verticalSeparator; 
	UIView* _topEdge; 
	UIView* _bottomEdge; 
	UIButton* _buttonLabel; 
	UIImageView* _chevronImage; 
	id<WAContactInfoEditCellDelegate> _delegate; 
	UITextField* _textField; 
}
@property (assign,nonatomic) id<WAContactInfoEditCellDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) UITextField* textField; 				//@synthesize textField=_textField - In the implementation block
@property (nonatomic,copy) NSString* label; 
@property (assign,nonatomic) BOOL hideTopEdge; 
@property (assign,nonatomic) BOOL hideBottomEdge; 
-(void)setHideTopEdge:(BOOL)arg1;
-(void)labelButtonTouchUp:(id)arg1;
-(void)labelButtonTouchDown:(id)arg1;
-(void)labelButtonTouchCancel:(id)arg1;
-(void)setHideBottomEdge:(BOOL)arg1;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setLabel:(id)arg1;
-(void).cxx_destruct;
@end