/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAContactSection_WAContactSection_ : NSManagedObject {
	unsigned[1] _cd_bits_0x16d069a0; 
}
+(BOOL)automaticallyNotifiesObserversOfContacts;
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(void)setContactCount:(id)arg1;
-(id)title;
-(id)contactCount;
-(id)contacts;
-(id)sort;
-(Class)class;
@end