/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:42 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WADividerCell : WATranslucentTableViewCell {
	UIImageView* _imageViewBackground; 
	UIView* _blurredBackgroundTrackingView; 
}
@property (nonatomic,copy) NSString* title; 
+(float)rowHeight;
-(id)blurMaskTrackingView;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setTitle:(id)arg1;
-(BOOL)selectable;
-(void).cxx_destruct;
@end