/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:09 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAPageable.h>

@interface WAEditableImage : NSObject <WAPageable> {
	UIImage* _thumbnailImage; 
	struct dispatch_group_s* _processingGroup; 
	BOOL _renderingInProgress; 
	int _renderID; 
	int _lastCompletedRenderID; 
	NSString* _cacheUUID; 
	NSString* _cachedFullScreenImagePath; 
	NSString* _cachedRenderedImagePath; 
	UIImage* _fullScreenImage; 
	UIImage* _renderedImage; 
	BOOL _savingCachedRenderedImageInProgress; 
	NSURL* _resourceURL; 
	NSDate* _date; 
	int _imageOrientation; 
	CGRect _normalizedCropRect; 
}
@property (nonatomic,copy) NSURL* resourceURL; 				//@synthesize resourceURL=_resourceURL - In the implementation block
@property (nonatomic,copy) UIImage* fullScreenImage; 
@property (nonatomic,copy) UIImage* thumbnailImage; 
@property (nonatomic,copy) UIImage* renderedImage; 
@property (nonatomic,copy) NSDate* date; 				//@synthesize date=_date - In the implementation block
@property (assign,nonatomic) CGRect normalizedCropRect; 				//@synthesize normalizedCropRect=_normalizedCropRect - In the implementation block
@property (assign,nonatomic) int imageOrientation; 				//@synthesize imageOrientation=_imageOrientation - In the implementation block
-(id)initWithResourceURL:(id)arg1 fullScreenImage:(id)arg2;
-(void)renderImageWithCompletionHandler:(id)arg1;
-(void)setNormalizedCropRect:(CGRect)arg1;
-(void)invalidateAll;
-(void)invalidateRenderingOnly;
-(void)saveRenderedImageToDiskAsync;
-(void)dealloc;
-(void)applicationDidReceiveMemoryWarning:(id)arg1;
-(void).cxx_destruct;
-(void)setResourceURL:(id)arg1;
-(void)setImageOrientation:(int)arg1;
@end