/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAEventBubbleView : UIView {
	UIImageView* _imageViewBubble; 
	UILabel* _labelEvent; 
}
@property (nonatomic,copy) NSString* eventText; 
+(CGSize)sizeForEventText:(id)arg1 forWidth:(float)arg2;
-(void)fontSizeDidChange:(id)arg1;
-(void)setEventText:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(id)accessibilityLabel;
-(CGRect)accessibilityFrame;
-(id)accessibilityValue;
-(BOOL)isAccessibilityElement;
-(void).cxx_destruct;
@end