/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAFontSizePicker7 : UIViewController {
	UILabel* _textLabel; 
}
-(void)contentSizeCategoryDidChange:(id)arg1;
-(void)dealloc;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)loadView;
-(void).cxx_destruct;
@end