/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:25 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WARecipientsViewControllerDelegate.h>
#import <WABCastMessageComposerDelegate.h>
#import <WANewGroupViewControllerDelegate.h>

@interface WAGroupComposer : UINavigationController <WARecipientsViewControllerDelegate, WABCastMessageComposerDelegate, WANewGroupViewControllerDelegate> {
	NSArray* _contacts; 
	NSString* _groupSubject; 
	UIImage* _groupPicture; 
	int _mode; 
}
@property (assign,nonatomic) id<UINavigationControllerDelegate><WAGroupComposerDelegate> delegate; 
@property (nonatomic,copy) int mode; 				//@synthesize mode=_mode - In the implementation block
-(void)newGroupViewControllerDidCancel:(id)arg1;
-(void)newGroupViewController:(id)arg1 didFinishWithSubject:(id)arg2 picture:(id)arg3;
-(void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
-(void)recipientsControllerDidCancel:(id)arg1;
-(id)broadcastMessageComposer;
-(id)recipientsViewController;
-(id)initWithMode:(int)arg1 recipients:(id)arg2;
-(void)messageComposer:(id)arg1 didFinishWithMedia:(id)arg2;
-(void)messageComposerDidCancel:(id)arg1;
-(id)initWithMode:(int)arg1;
-(id)init;
-(void).cxx_destruct;
@end