/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:51 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface WAGroupSubjectEditController : UITableViewController <UITextFieldDelegate> {
	UIView* _headerView; 
	UITextField* _textField; 
	UITableViewCell* _textFieldCell; 
	UILabel* _labelCharCount; 
	id<WAGroupSubjectEditControllerDelegate> _delegate; 
	NSString* _preloadedSubjectText; 
}
@property (nonatomic,retain) NSString* preloadedSubjectText; 				//@synthesize preloadedSubjectText=_preloadedSubjectText - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)saveAction:(id)arg1;
-(void)textFieldValueChanged:(id)arg1;
-(void)setPreloadedSubjectText:(id)arg1;
-(void)updateCharCount;
-(void)dealloc;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(id)headerView;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
@end