/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UINavigationControllerDelegate.h>

@interface WAImageToImageTransitionNavigationController : UINavigationController <UINavigationControllerDelegate> {
	_WAImageToImageTransitionDefaultGestureRecognizerDelegate* _defaultGestureRecognizerDelegate; 
}
-(void)dealloc;
-(id)init;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)pushViewController:(id)arg1 animated:(BOOL)arg2;
-(id)navigationController:(id)arg1 animationControllerForOperation:(int)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
-(id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
-(void).cxx_destruct;
@end