/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAImageCropToolViewDelegate
@required
-(void)imageCropToolViewNormalizedCropRectWillBeginChanging(id):arg1 ;
-(void)imageCropToolViewNormalizedCropRectDidChange(id):arg1 ;
-(void)imageCropToolViewNormalizedCropRectDidFinishChanging(id):arg1 ;
-(void)imageCropToolViewNormalizedCropRectWillBeginChanging(id):arg1 ;
-(void)imageCropToolViewNormalizedCropRectDidChange(id):arg1 ;
-(void)imageCropToolViewNormalizedCropRectDidFinishChanging(id):arg1 ;
@end
