/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIScrollViewDelegate
@optional
-(void)scrollViewDidScroll(id):arg1 ;
-(void)scrollViewDidZoom(id):arg1 ;
-(void)scrollViewWillBeginDragging(id):arg1 ;
-(void)scrollViewWillEndDragging(id):arg1 withVelocity({):arg2 targetContentOffset(unsigned char):arg3 ;
-(void)scrollViewDidEndDragging(id):arg1 willDecelerate(BOOL):arg2 ;
-(void)scrollViewWillBeginDecelerating(id):arg1 ;
-(void)scrollViewDidEndDecelerating(id):arg1 ;
-(void)scrollViewDidEndScrollingAnimation(id):arg1 ;
-(id)viewForZoomingInScrollView(id):arg1 ;
-(void)scrollViewWillBeginZooming(id):arg1 withView(id):arg2 ;
-(void)scrollViewDidEndZooming(id):arg1 withView(id):arg2 atScale(float):arg3 ;
-(BOOL)scrollViewShouldScrollToTop(id):arg1 ;
-(void)scrollViewDidScrollToTop(id):arg1 ;
@end

@protocol UIActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)actionSheet(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)actionSheet(id):arg1 didDismissWithButtonIndex(int):arg2 ;
@end

@protocol UINavigationControllerDelegate
@optional
-(void)navigationController(id):arg1 willShowViewController(id):arg2 animated(BOOL):arg3 ;
-(void)navigationController(id):arg1 didShowViewController(id):arg2 animated(BOOL):arg3 ;
-(id)navigationController(id):arg1 animationControllerForOperation(int):arg2 fromViewController(id):arg3 toViewController(id):arg4 ;
-(id)navigationController(id):arg1 interactionControllerForAnimationController(id):arg2 ;
-(unsigned)navigationControllerSupportedInterfaceOrientations(id):arg1 ;
-(int)navigationControllerPreferredInterfaceOrientationForPresentation(id):arg1 ;
@end

@protocol ABPeoplePickerNavigationControllerDelegate
@required
-(void)peoplePickerNavigationControllerDidCancel(id):arg1 ;
-(BOOL)peoplePickerNavigationController(id):arg1 shouldContinueAfterSelectingPerson(*):arg2 ;
-(BOOL)peoplePickerNavigationController(id):arg1 shouldContinueAfterSelectingPerson(*):arg2 property(void):arg3 identifier(int):arg4 ;
-(void)peoplePickerNavigationControllerDidCancel(id):arg1 ;
-(BOOL)peoplePickerNavigationController(id):arg1 shouldContinueAfterSelectingPerson(*):arg2 ;
-(BOOL)peoplePickerNavigationController(id):arg1 shouldContinueAfterSelectingPerson(*):arg2 property(void):arg3 identifier(int):arg4 ;
@end

@protocol ForwardPickerDelegate
@optional
-(id)forwardPicker(id):arg1 confirmationTextForContact(id):arg2 ;
@required
-(void)forwardPicker(id):arg1 didSelectContact(id):arg2 ;
-(void)forwardPickerDidCancel(id):arg1 ;
-(void)forwardPicker(id):arg1 didSelectContact(id):arg2 ;
-(void)forwardPickerDidCancel(id):arg1 ;
@end

@protocol MFMailComposeViewControllerDelegate
@optional
-(void)mailComposeController(id):arg1 didFinishWithResult(int):arg2 error(id):arg3 ;
@end

@protocol WAMediaScrollViewDelegate
@required
-(void)mediaScrollViewDidReceiveSingleTap(id):arg1 ;
-(void)mediaScrollViewDidFinishLongPress(id):arg1 ;
-(void)mediaScrollViewLoadStateDidChange(id):arg1 ;
-(void)mediaScrollViewPlaybackStateDidChange(id):arg1 ;
-(void)mediaScrollViewPlaybackDidFinish(id):arg1 ;
-(void)mediaScrollViewWantsFullscreenTimerInvalidated(id):arg1 ;
-(BOOL)mediaScrollViewCanShowErrorAlertView(id):arg1 ;
-({)mediaScrollViewLayoutInset(U):arg1 ;
-(void)mediaScrollViewDidBeginScrubbing(id):arg1 ;
-(void)mediaScrollViewDidEndScrubbing(id):arg1 ;
-(void)mediaScrollViewDidReceiveSingleTap(id):arg1 ;
-(void)mediaScrollViewDidFinishLongPress(id):arg1 ;
-(void)mediaScrollViewLoadStateDidChange(id):arg1 ;
-(void)mediaScrollViewPlaybackStateDidChange(id):arg1 ;
-(void)mediaScrollViewPlaybackDidFinish(id):arg1 ;
-(void)mediaScrollViewWantsFullscreenTimerInvalidated(id):arg1 ;
-(BOOL)mediaScrollViewCanShowErrorAlertView(id):arg1 ;
-({)mediaScrollViewLayoutInset(U):arg1 ;
-(void)mediaScrollViewDidBeginScrubbing(id):arg1 ;
-(void)mediaScrollViewDidEndScrubbing(id):arg1 ;
@end

@protocol WAThumbsViewControllerDelegate
@required
-(void)thumbsViewController(id):arg1 didSelectMediaAtIndex(int):arg2 ;
-(void)thumbsViewController(id):arg1 didSelectMediaAtIndex(int):arg2 ;
@end

@protocol WAImageToImageTransitioning
@required
-(BOOL)shouldUseImageToImageTransitionForOperation(int):arg1 fromViewController(id):arg2 toViewController(id):arg3 context(id):arg4 ;
-(void)prepareForTransitionWithContext(id):arg1 ;
-(id)viewForTransitionAnimationWithContext(id):arg1 ;
-(void)finishTransitionWithView(id):arg1 context(id):arg2 ;
-(BOOL)shouldUseImageToImageTransitionForOperation(int):arg1 fromViewController(id):arg2 toViewController(id):arg3 context(id):arg4 ;
-(void)prepareForTransitionWithContext(id):arg1 ;
-(id)viewForTransitionAnimationWithContext(id):arg1 ;
-(void)finishTransitionWithView(id):arg1 context(id):arg2 ;
@end
