/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAContactInfoEditCellDelegate.h>
#import <LabelPickerViewControllerDelegate.h>

@interface WAInfoInputViewController : UITableViewController <WAContactInfoEditCellDelegate, LabelPickerViewControllerDelegate> {
	id<WAInfoInputViewControllerDelegate> _delegate; 
	WAContactInfoNameUnit* _contactNameUnit; 
	WAContactInfoPhotoUnit* _contactPhotoUnit; 
	WAContactInfoTableHeaderView* _tableHeader; 
	WAContactInfoEditCell* _textFieldCell; 
	void* _displayedPerson; 
	int _propertyType; 
	NSString* _propertyValue; 
	NSString* _labelValue; 
}
@property (assign,nonatomic) void* displayedPerson; 				//@synthesize displayedPerson=_displayedPerson - In the implementation block
@property (assign,nonatomic) int propertyType; 				//@synthesize propertyType=_propertyType - In the implementation block
@property (nonatomic,copy) NSString* propertyValue; 				//@synthesize propertyValue=_propertyValue - In the implementation block
@property (nonatomic,copy) NSString* labelValue; 				//@synthesize labelValue=_labelValue - In the implementation block
-(void)cancelAction:(id)arg1;
-(void)validateUserInput;
-(void)saveAction:(id)arg1;
-(void)setLabelValue:(id)arg1;
-(void)setPropertyType:(int)arg1;
-(void)labelPickerViewControllerDidCancel:(id)arg1;
-(void)labelPickerViewController:(id)arg1 didSelectLabel:(id)arg2;
-(void)textFieldValueChanged:(id)arg1;
-(void)presentLabelPicker;
-(void)labelButtonTappedInCell:(id)arg1;
-(void)dealloc;
-(id)init;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
-(void)setPropertyValue:(id)arg1;
-(id)initWithDelegate:(id)arg1;
-(void)setDisplayedPerson:(void*)arg1;
@end