/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:22 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAInstantVoiceBubbleView : WABubbleView {
	UIAccessibilityElement* _elemBody; 
	BOOL _allowAction; 
	BOOL _allowLablel; 
	NSString* _buttonHint; 
	UIImage* _thumbnailImage; 
}
@property (nonatomic,retain) UIImage* thumbnailImage; 				//@synthesize thumbnailImage=_thumbnailImage - In the implementation block
+(CGSize)sizeForName:(id)arg1 incoming:(BOOL)arg2 forWidth:(float)arg3;
+(float)heightForName:(id)arg1;
-(id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;
-(void)setButtonHint:(id)arg1 allowVoiceOverLabel:(BOOL)arg2 allowAction:(BOOL)arg3;
-(void)updateAccessibilityLabels;
-(void)drawRect:(CGRect)arg1;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(BOOL)isAccessibilityElement;
-(int)accessibilityElementCount;
-(id)accessibilityElementAtIndex:(int)arg1;
-(int)indexOfAccessibilityElement:(id)arg1;
-(void).cxx_destruct;
-(void)setThumbnailImage:(id)arg1;
@end