/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:35 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAInputTextView : UITextView {
	float _previousContentHeight; 
	BOOL _scrollIndicatorsShown; 
	struct UIEdgeInsets _fixedInsets; 
	WAMessageCell* _popupMenuTargetCell; 
	UITextView* _textViewForMeasuring; 
}
@property (assign,nonatomic) id<WAInputTextViewDelegate> delegate; 
@property (nonatomic,copy) float minimumHeight; 
-(void)copyMessage:(id)arg1;
-(void)forwardMessage:(id)arg1;
-(void)addMessageSenderToContacts:(id)arg1;
-(void)replyMessageSender:(id)arg1;
-(void)menuControllerDidHideMenu:(id)arg1;
-(void)setUserScrollingEnabled:(BOOL)arg1;
-(void)updateTextViewMetrics;
-(float)bestHeightForText:(id)arg1;
-(float)bestHeightForCurrentText;
-(void)scrollToVisibleRangeAfterDelay:(double)arg1;
-(void)scrollToBottomAnimated:(BOOL)arg1;
-(void)logMetrics;
-(void)showPopupMenuForMessageCell:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setFrame:(CGRect)arg1;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(void)setFont:(id)arg1;
-(void)setText:(id)arg1;
-(void)setContentOffset:(CGPoint)arg1;
-(void)setContentSize:(CGSize)arg1;
-(void)setContentInset:(struct UIEdgeInsets)arg1;
-(void)textDidChange:(id)arg1;
-(void)paste:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void).cxx_destruct;
-(void)deleteMessage:(id)arg1;
-(id)shortName;
@end