/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WALargeVideoMessageCell : WALargeMediaMessageCell {
	UIView* _playButtonView; 
	WAAutoCropImageView* _blurBackgroundView; 
	CALayer* _blurMaskLayer; 
	UIImageView* _circleImageView; 
}
+(float)maximumImageWidth;
+(float)maximumParallaxOffset;
+(id)cellReuseIdentifier;
-(void)blurredImageDidBecomeAvailable:(id)arg1;
-(void)setProgressViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)prepareForReuse;
-(void).cxx_destruct;
@end