/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:45 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WADownloadProgressViewDelegate.h>
#import <WAScrollTracking.h>

@interface WALargeMediaMessageCell : WAMessageCell <WADownloadProgressViewDelegate, WAScrollTracking> {
	UIImageView* _bubbleImageView; 
	_WAImageMessageContainerView* _messageContainerView; 
	UIView* _blackView; 
	UIView* _whiteView; 
	float _imageAspectRatio; 
	float _parallaxScaleFactor; 
	UILabel* _timestampLabel; 
	UIImageView* _statusImageView; 
	UIImageView* _broadcastImageView; 
	int _counter; 
	WAGradientView* _gradientView; 
	BOOL _cellDataLoaded; 
	UILabel* _fromNameLabel; 
	UILabel* _pushNameLabel; 
	UIImageView* _topCapImageView; 
	BOOL _showFileSize; 
	WAAutoCropImageView* _messageImageView; 
}
@property (nonatomic,copy) UIView* messageContainerView; 				//@synthesize messageContainerView=_messageContainerView - In the implementation block
@property (nonatomic,copy) WADownloadProgressView* progressView; 				//@synthesize progressView=_progressView - In the implementation block
@property (nonatomic,copy) WAAutoCropImageView* messageImageView; 				//@synthesize messageImageView=_messageImageView - In the implementation block
@property (assign,nonatomic) BOOL showFileSize; 				//@synthesize showFileSize=_showFileSize - In the implementation block
+(struct UIEdgeInsets)edgeInsetsForImage;
+(float)maximumImageWidth;
+(float)maximumParallaxOffset;
+(id)cellReuseIdentifier;
+(float)heightForCellData:(id)arg1 width:(float)arg2 editing:(BOOL)arg3;
+(void)initialize;
-(void)setDidScroll;
-(void)handleSingleTap:(id)arg1;
-(void)configureCellUpdatingAllContents:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setShowsProgressBar:(BOOL)arg1 animated:(BOOL)arg2;
-(void)blurredImageDidBecomeAvailable:(id)arg1;
-(void)configureForAccessibility;
-(void)setWhiteViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setProgressViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setProgressViewHidden:(BOOL)arg1;
-(id)shortNameForPopupMenu;
-(void)copyMessage:(id)arg1;
-(void)forwardMessage:(id)arg1;
-(void)addMessageSenderToContacts:(id)arg1;
-(void)replyMessageSender:(id)arg1;
-(CGRect)targetRectForPopupMenu;
-(id)referenceViewForPopupMenu;
-(void)menuControllerDidHideMenu:(id)arg1;
-(void)downloadProgressViewDidCancel:(id)arg1;
-(BOOL)bubbleView:(id)arg1 canPerformAction:(SEL)arg2 withSender:(id)arg3;
-(void)setBubbleHighlighted:(BOOL)arg1;
-(void)showPopupMenu;
-(void)setShowFileSize:(BOOL)arg1;
-(void)handleLongPress:(id)arg1;
-(void)handleDoubleTap:(id)arg1;
-(void)didMoveToWindow;
-(void)setFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(BOOL)canBecomeFirstResponder;
-(void)setProgress:(float)arg1;
-(void)prepareForReuse;
-(BOOL)isAnimating;
-(BOOL)selectable;
-(void).cxx_destruct;
-(void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
-(void)deleteMessage:(id)arg1;
-(void)setDimmed:(BOOL)arg1;
-(BOOL)isDimmed;
@end