/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSFetchedResultsControllerDelegate.h>
#import <WARecipientsViewControllerDelegate.h>
#import <UITextFieldDelegate.h>
#import <UIGestureRecognizerDelegate.h>

@interface WAListInfoViewController : UITableViewController <NSFetchedResultsControllerDelegate, WARecipientsViewControllerDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate> {
	NSFetchedResultsController* _fetchedResultsController; 
	BOOL _chatStorageAvailable; 
	UITableViewCell* _changeRecipientCell; 
	_WAEditListNameTableViewCell* _editNameCell; 
	NSMutableArray* _groupMembersToUpdate; 
	BOOL _animateListChanges; 
	WAChatSession* _list; 
}
@property (nonatomic,retain) WAChatSession* list; 				//@synthesize list=_list - In the implementation block
-(void)chatStorageDidLoadDatabase:(id)arg1;
-(void)chatStorageWillUnloadDatabase:(id)arg1;
-(void)updateInterface;
-(void)setUpFetchRequest;
-(void)loadStatusMessagesOfGroupMembers:(id)arg1;
-(void)tableViewTapped:(id)arg1;
-(void)changeRecipients;
-(BOOL)showContactInfoForGroupMember:(id)arg1;
-(void)updateRecipientsWithContacts:(id)arg1;
-(void)updateGroupMemberInfoForVisibleCells;
-(void)reloadAll;
-(void)recipientsController:(id)arg1 didFinishWithContacts:(id)arg2;
-(void)recipientsControllerDidCancel:(id)arg1;
-(void)updateGroupMemberAtIndexPath:(id)arg1;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned)arg4 newIndexPath:(id)arg5;
-(void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned)arg3 forChangeType:(unsigned)arg4;
-(void)controllerDidChangeContent:(id)arg1;
-(void)controllerWillChangeContent:(id)arg1;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)textFieldShouldBeginEditing:(id)arg1;
-(void)textFieldDidEndEditing:(id)arg1;
-(BOOL)textFieldShouldReturn:(id)arg1;
-(id)initWithStyle:(int)arg1;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void).cxx_destruct;
-(void)setList:(id)arg1;
@end