/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAListTableViewCell : UITableViewCell {
	UILabel* _nameLabel; 
	UILabel* _participantsLabel; 
}
+(id)cellWithReuseIdentifier:(id)arg1;
-(void)configureWithList:(id)arg1;
-(void)setSystemAccessoryViewHidden:(BOOL)arg1;
-(id)systemAccessoryView;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)willTransitionToState:(unsigned)arg1;
-(void).cxx_destruct;
@end