/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WALocationMessageHelper : WAMessageHelper {
}
-(id)chatThumbnailReturningPermanentState:(BOOL*)arg1;
-(CGSize)chatThumbnailSize;
-(void)internalGenerateChatThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
-(void)internalGenerateXMPPThumbnailFromImageRepresentation:(id)arg1 completion:(id)arg2;
@end