/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MKAnnotation.h>

@interface WALocationData : NSObject <MKAnnotation> {
	CLLocation* _location; 
	UIImage* _contactImage; 
	BOOL _showDistance; 
	BOOL _showTimestamp; 
	CLLocation* _baseLocation; 
	NSString* _contactName; 
	int _contactID; 
	MKPlacemark* _placemark; 
	NSDate* _timestamp; 
	NSManagedObjectID* _messageId; 
}
@property (nonatomic,retain) CLLocation* baseLocation; 				//@synthesize baseLocation=_baseLocation - In the implementation block
@property (nonatomic,retain) NSString* contactName; 				//@synthesize contactName=_contactName - In the implementation block
@property (assign,nonatomic) int contactID; 				//@synthesize contactID=_contactID - In the implementation block
@property (nonatomic,retain) MKPlacemark* placemark; 				//@synthesize placemark=_placemark - In the implementation block
@property (nonatomic,retain) NSDate* timestamp; 				//@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,retain) NSManagedObjectID* messageId; 				//@synthesize messageId=_messageId - In the implementation block
@property (nonatomic,copy) UIImage* contactImage; 
@property (assign,nonatomic) BOOL showDistance; 				//@synthesize showDistance=_showDistance - In the implementation block
@property (assign,nonatomic) BOOL showTimestamp; 				//@synthesize showTimestamp=_showTimestamp - In the implementation block
@property (nonatomic,copy) struct coordinate; 
@property (nonatomic,copy) NSString* title; 
@property (nonatomic,copy) NSString* subtitle; 
+(id)sharedTimePeriodFormatter;
-(void)setBaseLocation:(id)arg1;
-(void)setPlacemark:(id)arg1;
-(void)setShowTimestamp:(BOOL)arg1;
-(void)setShowDistance:(BOOL)arg1;
-(void)setMessageId:(id)arg1;
-(BOOL)isEqual:(id)arg1;
-(void)setTimestamp:(id)arg1;
-(void).cxx_destruct;
-(void)setContactName:(id)arg1;
-(void)setContactID:(int)arg1;
-(id)initWithCoordinate:(struct )arg1;
@end