/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:39 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIGestureRecognizerDelegate.h>
#import <UIActionSheetDelegate.h>

@interface WALocationBubbleView : WABubbleView <UIGestureRecognizerDelegate, UIActionSheetDelegate> {
	UIActivityIndicatorView* _activityIndicator; 
	UIView* _containerView; 
	UIImageView* _thumbnailImageView; 
	UIView* _thumbnailDimmerView; 
	WAGradientView* _gradientView; 
	CGRect _urlRect; 
	BOOL _urlHighlighted; 
	UITapGestureRecognizer* _tapGestureRecognizer; 
	UILongPressGestureRecognizer* _longPressGestureRecognizer; 
	UIImage* _thumbnailImage; 
	NSString* _placeName; 
	NSString* _placeAddress; 
	NSString* _placeURL; 
	CGSize _imageSize; 
	struct {
		double latitude;
		double longitude;
	} _locationCoordinate; 
}
@property (assign,nonatomic) CGSize imageSize; 				//@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,retain) UIImage* thumbnailImage; 				//@synthesize thumbnailImage=_thumbnailImage - In the implementation block
@property (assign,getter=isAnimating,nonatomic) BOOL animating; 
@property (assign,nonatomic) struct locationCoordinate; 				//@synthesize locationCoordinate=_locationCoordinate - In the implementation block
@property (nonatomic,retain) NSString* placeName; 				//@synthesize placeName=_placeName - In the implementation block
@property (nonatomic,retain) NSString* placeAddress; 				//@synthesize placeAddress=_placeAddress - In the implementation block
@property (nonatomic,retain) NSString* placeURL; 				//@synthesize placeURL=_placeURL - In the implementation block
+(CGSize)sizeForPlaceName:(id)arg1 address:(id)arg2 maxWidth:(float)arg3 timestampString:(id)arg4 messageStatus:(int)arg5 fromName:(id)arg6 pushName:(id)arg7 imageSize:(CGSize)arg8 showListIcon:(BOOL)arg9 isIncoming:(BOOL)arg10;
+(float)heightForName:(id)arg1 placeName:(id)arg2 placeAddress:(id)arg3;
-(void)handleTapGesture:(id)arg1;
-(id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;
-(void)setPlaceAddress:(id)arg1;
-(void)setPlaceURL:(id)arg1;
-(void)setLocationCoordinate:(struct )arg1;
-(void)showActionSheet;
-(void)unhighlightURL;
-(void)openURLInGoogleMaps;
-(void)openURLInFoursquare;
-(void)highlightURL;
-(void)drawRect:(CGRect)arg1;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setAnimating:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
-(void)openURL;
-(void)setThumbnailImage:(id)arg1;
-(void)setImageSize:(CGSize)arg1;
-(void)setPlaceName:(id)arg1;
-(void)handleLongPressGesture:(id)arg1;
@end