/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMediaItem : NSManagedObject {
	BOOL _networkActivity; 
	BOOL _mediaSaved; 
}
@property (nonatomic,@dynamic,retain) NSString* vCardString; 
@property (nonatomic,@dynamic,retain) NSNumber* longitude; 
@property (nonatomic,@dynamic,retain) NSString* vCardName; 
@property (nonatomic,@dynamic,retain) NSString* mediaLocalPath; 
@property (nonatomic,@dynamic,retain) NSNumber* latitude; 
@property (nonatomic,@dynamic,retain) NSNumber* fileSize; 
@property (nonatomic,@dynamic,retain) NSString* mediaURL; 
@property (nonatomic,@dynamic,retain) WAMessage* message; 
@property (nonatomic,@dynamic,retain) NSString* thumbnailLocalPath; 
@property (nonatomic,@dynamic,retain) NSString* xmppThumbPath; 
@property (nonatomic,@dynamic,retain) NSNumber* movieDuration; 
@property (nonatomic,@dynamic,retain) NSNumber* mediaOrigin; 
@property (nonatomic,@dynamic,retain) NSString* title; 
@property (nonatomic,@dynamic,retain) NSString* authorName; 
@property (nonatomic,@dynamic,retain) NSString* collectionName; 
@property (nonatomic,@dynamic,retain) NSString* featureInfo; 
@property (assign,nonatomic) BOOL networkActivity; 				//@synthesize networkActivity=_networkActivity - In the implementation block
@property (assign,nonatomic) BOOL mediaSaved; 				//@synthesize mediaSaved=_mediaSaved - In the implementation block
@property (nonatomic,retain) NSString* fileHash; 
@property (nonatomic,copy) NSString* placeDetails; 
-(void)setMediaSaved:(BOOL)arg1;
-(void)setNetworkActivity:(BOOL)arg1;
-(void)setFileHash:(id)arg1;
@end