/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:04 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMediaDownloader : NSObject {
	id<WAMediaDownloaderDelegate> _delegate; 
	XMPPConnection* _connection; 
	GTMHTTPFetcher* _httpFetcher; 
	WAMessage* _message; 
	NSData* _fileData; 
	NSString* _fileName; 
	BOOL _newMMS; 
}
@property (nonatomic,retain) id<WAMediaDownloaderDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) XMPPConnection* connection; 				//@synthesize connection=_connection - In the implementation block
@property (nonatomic,copy) WAMessage* message; 				//@synthesize message=_message - In the implementation block
@property (nonatomic,copy) NSData* fileData; 				//@synthesize fileData=_fileData - In the implementation block
@property (nonatomic,copy) NSString* fileName; 				//@synthesize fileName=_fileName - In the implementation block
-(void)fetcher:(id)arg1 receivedData:(id)arg2;
-(void)ackFinishedWithUserInfo:(id)arg1;
-(void)ackFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)fetcher:(id)arg1 finishedWithFileData:(id)arg2 error:(id)arg3;
-(id)initWithDownloaderDelegate:(id)arg1 connection:(id)arg2;
-(void)downloadMediaForMessage:(id)arg1;
-(void)cancelDownload;
-(void)setDelegate:(id)arg1;
-(void).cxx_destruct;
-(void)setConnection:(id)arg1;
@end