/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:46 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMediaManager : NSObject {
	BOOL _databaseAccessAvailable; 
	BOOL _loadingMedia; 
	BOOL _needsMediaDataReset; 
	BOOL _performFullLoadingOfMediaData; 
	struct dispatch_group_s* _mediaLoadingDispatchGroup; 
	WADatabaseResultsFetcher* _messagesWithMediaFetcher; 
	NSMutableArray* _mediaObjects; 
	unsigned long long _dummyValue; 
	NSString* _title; 
	WAChatSession* _chatSession; 
	int _contactID; 
}
@property (nonatomic,retain) NSString* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSArray* mediaObjects; 				//@synthesize mediaObjects=_mediaObjects - In the implementation block
@property (nonatomic,copy) unsigned numberOfMediaObjects; 
@property (nonatomic,retain) WAChatSession* chatSession; 				//@synthesize chatSession=_chatSession - In the implementation block
@property (assign,nonatomic) int contactID; 				//@synthesize contactID=_contactID - In the implementation block
-(void)chatStorageDidLoadDatabase:(id)arg1;
-(void)loadMedia:(BOOL)arg1 completion:(id)arg2;
-(void)setChatSession:(id)arg1;
-(void)chatStorageWillUnloadDatabase:(id)arg1;
-(void)setNeedsMediaDataReset;
-(void)retrieveMessagesFromMediaFetcher;
-(void)updateWithFetcher:(id)arg1 completion:(id)arg2;
-(BOOL)needsReloading;
-(unsigned)indexOfMediaObjectForMessage:(id)arg1;
-(BOOL)isGroupChatMedia;
-(void)deleteMediaAtIndexes:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setTitle:(id)arg1;
-(void)reset;
-(void).cxx_destruct;
-(void)setContactID:(int)arg1;
@end