/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:21 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAMediaPickerControllerDelegate
@optional
-(void)mediaPickerControllerNeedsRelayoutOfCustomToolbarItems(id):arg1 ;
@required
-(void)mediaPickerControllerDidFinishPresenting(id):arg1 ;
-(void)mediaPickerController(id):arg1 didFinishWithSelectedAssetURLs(id):arg2 ;
-(void)mediaPickerControllerDidFinishPresenting(id):arg1 ;
-(void)mediaPickerController(id):arg1 didFinishWithSelectedAssetURLs(id):arg2 ;
@end
