/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAMediaPlayerTransportControlViewDelegate.h>
#import <UIGestureRecognizerDelegate.h>
#import <UIScrollViewDelegate.h>
#import <WAMediaPlayerDelegate.h>

@interface WAMediaScrollView : UIScrollView <WAMediaPlayerTransportControlViewDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, WAMediaPlayerDelegate> {
	UIImageView* _imageView; 
	float _initialZoomScale; 
	UIImageView* _audioOnlyBackgroundImageView; 
	UIImageView* _audioOnlyLogoImageView; 
	WAMediaObject* _currentMedia; 
	NSString* _errorMessageToShowOnNextPlayAttempt; 
	WAMediaPlayerTransportControlView* _playerTransportBar; 
	UILongPressGestureRecognizer* _longPressGesture; 
	UITapGestureRecognizer* _doubleTapGesture; 
	BOOL _mediaControlsHidden; 
	id<WAMediaScrollViewDelegate> _mediaDelegate; 
	unsigned _index; 
	float _topLayoutEdge; 
	float _offset; 
	WAMediaPlayer* _mediaPlayer; 
}
@property (assign,nonatomic) id<WAMediaScrollViewDelegate> mediaDelegate; 				//@synthesize mediaDelegate=_mediaDelegate - In the implementation block
@property (assign,nonatomic) unsigned index; 				//@synthesize index=_index - In the implementation block
@property (assign,nonatomic) float topLayoutEdge; 				//@synthesize topLayoutEdge=_topLayoutEdge - In the implementation block
@property (assign,nonatomic) float offset; 				//@synthesize offset=_offset - In the implementation block
@property (assign,nonatomic) BOOL mediaControlsHidden; 				//@synthesize mediaControlsHidden=_mediaControlsHidden - In the implementation block
@property (nonatomic,copy) WAMediaPlayer* mediaPlayer; 				//@synthesize mediaPlayer=_mediaPlayer - In the implementation block
@property (getter=isPlayable,nonatomic,copy) BOOL playable; 
@property (nonatomic,copy) BOOL isLongPressing; 
@property (nonatomic,copy) UIView* contentView; 
-(void)handleSingleTap:(id)arg1;
-(void)mediaPlayerDidRequestPlaybackStart:(id)arg1;
-(void)mediaPlayerStatusDidChange:(id)arg1;
-(void)mediaPlayerDidChangeCurrentTime:(id)arg1;
-(void)mediaPlayerDidFinishLoading:(id)arg1;
-(void)mediaPlayerDidPlayToEndTime:(id)arg1;
-(void)mediaPlayerDidBeginScrubbing:(id)arg1;
-(void)mediaPlayerDidEndScrubbing:(id)arg1;
-(void)playInitiatedByAutoPlay:(BOOL)arg1;
-(void)setTopLayoutEdge:(float)arg1;
-(void)configureZooming;
-(void)setMediaControlsHidden:(BOOL)arg1 animationDuration:(double)arg2;
-(void)displayMedia:(id)arg1;
-(void)setMediaDelegate:(id)arg1;
-(void)animateDeletionWithCompletionHandler:(id)arg1;
-(void)animateOutImageView:(id)arg1 completion:(id)arg2;
-(CGRect)zoomRectForScale:(float)arg1 withCenter:(CGPoint)arg2;
-(void)toggleZoomInOutAtPoint:(CGPoint)arg1;
-(void)showPopupMenuAtPoint:(CGPoint)arg1;
-(void)displayQTLogo;
-(void)handlePlaybackError;
-(void)mediaPlayerTransportControlViewDidBeginScrubbing:(id)arg1;
-(void)mediaPlayerTransportControlViewDidEndScrubbing:(id)arg1;
-(void)mediaPlayerTransportControlViewDidChangeCurrentTime:(id)arg1;
-(void)setMediaControlsHidden:(BOOL)arg1;
-(void)handleLongPress:(id)arg1;
-(void)handleDoubleTap:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(void)scrollViewDidZoom:(id)arg1;
-(id)viewForZoomingInScrollView:(id)arg1;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(BOOL)canBecomeFirstResponder;
-(void)prepareForReuse;
-(void)copy:(id)arg1;
-(void)setOffset:(float)arg1;
-(void).cxx_destruct;
-(void)pause;
-(void)setIndex:(unsigned)arg1;
@end