/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:16 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSURLConnectionDelegate.h>

@interface WAMediaDownloadOperation : NSOperation <NSURLConnectionDelegate> {
	XMPPConnection* _connection; 
	id<WAMediaDownloadOperationDelegate> _delegate; 
	NSDate* _startDate; 
	NSURLConnection* _urlConnection; 
	unsigned _expectedContentLength; 
	NSHTTPURLResponse* _response; 
	NSMutableDictionary* _avParams; 
	NSMutableData* _receiveData; 
	NSMutableData* _partialFileData; 
	BOOL _partialDownload; 
	BOOL _isExecuting; 
	BOOL _isFinished; 
	BOOL _autodownload; 
	WAMessage* _message; 
	NSString* _fileName; 
}
@property (nonatomic,copy) WAMessage* message; 				//@synthesize message=_message - In the implementation block
@property (nonatomic,copy) NSString* fileName; 				//@synthesize fileName=_fileName - In the implementation block
@property (nonatomic,copy) BOOL autodownload; 				//@synthesize autodownload=_autodownload - In the implementation block
-(id)initWithDownloadOperationDelegate:(id)arg1 connection:(id)arg2 message:(id)arg3 autodownload:(BOOL)arg4;
-(void)startUrlConnection;
-(void)savePartialData;
-(id)partialUploadFilePath;
-(void)ackFinishedWithUserInfo:(id)arg1;
-(void)ackFailedWithError:(id)arg1 userInfo:(id)arg2;
-(void)performFinalDataCheck;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
-(void)dealloc;
-(void)cancel;
-(void)start;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void).cxx_destruct;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)finish;
@end