/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:40 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActivityItemSource.h>

@interface WAMediaObject : NSObject <UIActivityItemSource> {
	NSString* _fromName; 
	NSManagedObjectID* _messageID; 
	unsigned _type; 
	NSString* _path; 
	NSDate* _date; 
	UIImage* _thumbnail; 
	WAMessage* _message; 
}
@property (nonatomic,copy) unsigned type; 				//@synthesize type=_type - In the implementation block
@property (nonatomic,copy) NSString* path; 				//@synthesize path=_path - In the implementation block
@property (nonatomic,copy) NSDate* date; 				//@synthesize date=_date - In the implementation block
@property (nonatomic,retain) NSString* fromName; 
@property (nonatomic,retain) UIImage* thumbnail; 				//@synthesize thumbnail=_thumbnail - In the implementation block
@property (nonatomic,copy) WAMessage* message; 				//@synthesize message=_message - In the implementation block
-(id)initWithMessage:(id)arg1 path:(id)arg2;
-(void)setFromName:(id)arg1;
-(BOOL)isEligibleForActivitySharing;
-(void).cxx_destruct;
-(id)activityViewControllerPlaceholderItem:(id)arg1;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
-(void)setThumbnail:(id)arg1;
-(id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;
@end