/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIScrollViewDelegate.h>
#import <UIActionSheetDelegate.h>
#import <UINavigationControllerDelegate.h>
#import <ABPeoplePickerNavigationControllerDelegate.h>
#import <ForwardPickerDelegate.h>
#import <MFMailComposeViewControllerDelegate.h>
#import <WAMediaScrollViewDelegate.h>
#import <WAThumbsViewControllerDelegate.h>
#import <WAImageToImageTransitioning.h>

@interface WAMediaViewController : UIViewController <UIScrollViewDelegate, UIActionSheetDelegate, UINavigationControllerDelegate, ABPeoplePickerNavigationControllerDelegate, ForwardPickerDelegate, MFMailComposeViewControllerDelegate, WAMediaScrollViewDelegate, WAThumbsViewControllerDelegate, WAImageToImageTransitioning> {
	NSMutableSet* _recycledPages; 
	NSMutableSet* _visiblePages; 
	BOOL _rotating; 
	BOOL _tiling; 
	NSTimer* _hideBarsTimer; 
	WAProgressHUD* _progressHUD; 
	BOOL _shouldAutoPlay; 
	BOOL _shouldResumePlayback; 
	BOOL _fullScreenMode; 
	float _lastStatusBarHeight; 
	UIBarButtonItem* _showAllButton; 
	UIBarButtonItem* _actionButton; 
	UIBarButtonItem* _trashButton; 
	UIBarButtonItem* _playButton; 
	UIBarButtonItem* _pauseButton; 
	UIBarButtonItem* _previousButton; 
	UIBarButtonItem* _nextButton; 
	NSTimer* _holdingTimer; 
	BOOL _holding; 
	WAMediaManager* _mediaManager; 
	int _currentPageIndex; 
	UIScrollView* _pagingScrollView; 
	UIToolbar* _toolbar; 
	UIView* _viewMediaInfo; 
	UILabel* _labelMediaInfo; 
}
@property (nonatomic,retain) WAMediaManager* mediaManager; 				//@synthesize mediaManager=_mediaManager - In the implementation block
@property (assign,nonatomic) int currentPageIndex; 				//@synthesize currentPageIndex=_currentPageIndex - In the implementation block
@property (nonatomic,retain) UIScrollView* pagingScrollView; 				//@synthesize pagingScrollView=_pagingScrollView - In the implementation block
@property (nonatomic,retain) UIToolbar* toolbar; 				//@synthesize toolbar=_toolbar - In the implementation block
@property (nonatomic,retain) UIView* viewMediaInfo; 				//@synthesize viewMediaInfo=_viewMediaInfo - In the implementation block
@property (nonatomic,retain) UILabel* labelMediaInfo; 				//@synthesize labelMediaInfo=_labelMediaInfo - In the implementation block
-(void)chatStorageDidLoadDatabase:(id)arg1;
-(void)showHUD:(id)arg1;
-(void)removeHUD;
-(void)setMediaManager:(id)arg1;
-(void)updateToolbar;
-(void)groupPictureSet:(id)arg1 withUserData:(id)arg2;
-(void)groupPictureSetFailed:(id)arg1 withUserData:(id)arg2;
-(void)tilePages;
-(void)dismissPickerAndContinueWithPerson:(void*)arg1;
-(void)forwardPicker:(id)arg1 didSelectContact:(id)arg2;
-(void)forwardPickerDidCancel:(id)arg1;
-(id)forwardPicker:(id)arg1 confirmationTextForContact:(id)arg2;
-(void)chatStorageWillUnloadDatabase:(id)arg1;
-(void)showAllMedia:(id)arg1;
-(void)deleteCurrentMedia:(id)arg1;
-(void)showMediaActions:(id)arg1;
-(void)handlePreviousButtonTouchDown:(id)arg1;
-(void)handlePreviousButtonTouchUp:(id)arg1;
-(void)handleNextButtonTouchDown:(id)arg1;
-(void)handleNextButtonTouchUp:(id)arg1;
-(void)reloadMediaViewer;
-(void)recyclePage:(id)arg1;
-(void)updateUIWithOrientation:(int)arg1;
-(CGRect)frameForPagingScrollView;
-(int)mediaCount;
-(id)mediaAtIndex:(unsigned)arg1;
-(float)topLayoutEdge;
-(CGRect)frameForPageAtIndex:(unsigned)arg1;
-(id)currentMedia;
-(id)pageForIndex:(unsigned)arg1;
-(void)setFullScreenMode:(BOOL)arg1 animated:(BOOL)arg2;
-(void)hideBarsTimer:(id)arg1;
-(void)cancelHideBarsTimer;
-(BOOL)fullScreenModeAllowed;
-(void)profilePhotoSet:(id)arg1 withUserData:(id)arg2;
-(void)profilePhotoSetFailed:(id)arg1 withUserData:(id)arg2;
-(void)exitMediaViewer;
-(BOOL)isDisplayingPageForIndex:(unsigned)arg1;
-(id)dequeueRecycledPage;
-(void)configurePage:(id)arg1 forIndex:(unsigned)arg2;
-(void)didMoveToMediaAtIndex:(unsigned)arg1;
-(void)saveCurrentImage;
-(void)saveCurrentVideo;
-(void)assignImageToContact;
-(void)assignCurrentImageToGroup;
-(void)setProfilePhoto;
-(void)forwardMediaViaEmail;
-(void)showPersonPickerForMediaForwardViaWhatsApp;
-(void)navigateToPreviousPage:(id)arg1;
-(void)beginSeekingBackward:(id)arg1;
-(void)navigateToNextPage:(id)arg1;
-(void)beginSeekingForward:(id)arg1;
-(void)reallyDeleteCurrentMedia;
-(void)setViewMediaInfo:(id)arg1;
-(void)detectCurrentPageChange;
-(void)startHideBarsTimer;
-(void)showTransitoryHUDMessage:(id)arg1;
-(void)showFailedToSaveMediaAlertView;
-(void)assignImage:(id)arg1 toContactID:(int)arg2;
-(void)forwardMediaViaWhatsAppToContact:(id)arg1;
-(void)mediaScrollViewDidReceiveSingleTap:(id)arg1;
-(void)mediaScrollViewDidFinishLongPress:(id)arg1;
-(void)mediaScrollViewLoadStateDidChange:(id)arg1;
-(void)mediaScrollViewPlaybackStateDidChange:(id)arg1;
-(void)mediaScrollViewPlaybackDidFinish:(id)arg1;
-(void)mediaScrollViewWantsFullscreenTimerInvalidated:(id)arg1;
-(BOOL)mediaScrollViewCanShowErrorAlertView:(id)arg1;
-(struct UIEdgeInsets)mediaScrollViewLayoutInset:(id)arg1;
-(void)mediaScrollViewDidBeginScrubbing:(id)arg1;
-(void)mediaScrollViewDidEndScrubbing:(id)arg1;
-(void)thumbsViewController:(id)arg1 didSelectMediaAtIndex:(int)arg2;
-(BOOL)shouldUseImageToImageTransitionForOperation:(int)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 context:(id)arg4;
-(void)prepareForTransitionWithContext:(id)arg1;
-(id)viewForTransitionAnimationWithContext:(id)arg1;
-(void)finishTransitionWithView:(id)arg1 context:(id)arg2;
-(void)setFullScreenMode:(BOOL)arg1;
-(void)validatePageIndex;
-(void)setPagingScrollView:(id)arg1;
-(void)setLabelMediaInfo:(id)arg1;
-(void)deviceOrientationDidChange:(id)arg1;
-(void)dealloc;
-(void)scrollViewDidScroll:(id)arg1;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
-(void)scrollViewDidEndDecelerating:(id)arg1;
-(void)applicationDidEnterBackground:(id)arg1;
-(void)applicationWillEnterForeground:(id)arg1;
-(int)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotate;
-(void)viewDidLayoutSubviews;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(id)rotatingFooterView;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)setToolbar:(id)arg1;
-(void).cxx_destruct;
-(void)setCurrentPageIndex:(int)arg1;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
-(void)peoplePickerNavigationControllerDidCancel:(id)arg1;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
-(void)togglePlayPause:(id)arg1;
@end