/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:22 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMediaPlayer : UIView {
	AVPlayer* _player; 
	_WAPlayerView* _playerView; 
	AVPlayerItem* _playerItem; 
	id _timeObserver; 
	float _playerRateBeforeScrubbing; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _desiredSeekTime; 
	BOOL _seekInProgress; 
	UIButton* _playButton; 
	CGRect _frameForPlayButtonSnapshot; 
	UIImage* _snapshotAtTimeZero; 
	BOOL _scrubbingInProgress; 
	unsigned _status; 
	id<WAMediaPlayerDelegate> _delegate; 
	float _playbackRate; 
	NSError* _error; 
	UIImageView* _posterImageView; 
}
@property (assign,nonatomic) unsigned status; 				//@synthesize status=_status - In the implementation block
@property (assign,nonatomic) id<WAMediaPlayerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) float playbackRate; 				//@synthesize playbackRate=_playbackRate - In the implementation block
@property (getter=isPlaying,nonatomic,copy) BOOL playing; 
@property (getter=isReadyToPlay,nonatomic,copy) BOOL readyToPlay; 
@property (nonatomic,copy) NSError* error; 				//@synthesize error=_error - In the implementation block
@property (nonatomic,retain) UIImage* posterImage; 
@property (nonatomic,copy) UIImageView* posterImageView; 				//@synthesize posterImageView=_posterImageView - In the implementation block
@property (nonatomic,copy) CGSize presentationSize; 
@property (nonatomic,copy) struct currentTime; 
@property (nonatomic,copy) struct duration; 
@property (nonatomic,copy) BOOL scrubbingInProgress; 				//@synthesize scrubbingInProgress=_scrubbingInProgress - In the implementation block
-(id)snapshotImage;
-(void)playerItemDidPlayToEndTime:(id)arg1;
-(void)playButtonTapped:(id)arg1;
-(void)setPlayButtonHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)removeTimeObserverFromPlayer;
-(BOOL)playButtonHidden;
-(void)updatePlayButtonImage;
-(void)addTimeObserverToPlayer;
-(void)playerItemDidBecomeReadyToPlay;
-(void)playerDidChangeCurrentTime;
-(id)playButtonImageFromSnapshot:(id)arg1;
-(BOOL)seekToTime:(struct )arg1 tolerance:(struct )arg2;
-(void)playInitiatedByAutoPlay:(BOOL)arg1;
-(id)initWithContentURL:(id)arg1;
-(void)setPosterImage:(id)arg1;
-(void)prepareForPlayback;
-(void)setPlaybackRate:(float)arg1;
-(BOOL)seekToTime:(struct )arg1;
-(void)beginScrubbing;
-(void)endScrubbing;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
-(void)didMoveToWindow;
-(void)layoutSubviews;
-(void)applicationWillResignActive:(id)arg1;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void).cxx_destruct;
-(void)pause;
-(void)setStatus:(unsigned)arg1;
-(void)rewind;
@end