/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMessage : NSManagedObject {
	BOOL _observingSendState; 
	struct dispatch_group_s* _sendDispatchGroup; 
	struct dispatch_group_s* _locationInfoDispatchGroup; 
	BOOL _messageSendInProgress; 
	NSString* _mediaThumbnailCacheKey; 
	struct dispatch_group_s* _thumbnailLoadingDispatchGroup; 
	int _loadRequestsInProgress; 
	UIImage* _loadedThumbnail; 
	WAMessageHelper* _helper; 
	BOOL _offlineStorage; 
	BOOL _sending; 
	int _multiSendMediaIndex; 
	int _multiSendMediaCount; 
	WAMessage* _precedingMessage; 
	NSString* _participantJID; 
	NSData* _xmppThumbnailData; 
}
@property (nonatomic,@dynamic,retain) NSString* fromJID; 
@property (nonatomic,@dynamic,retain) NSString* toJID; 
@property (nonatomic,@dynamic,retain) NSString* stanzaID; 
@property (nonatomic,@dynamic,retain) NSString* text; 
@property (nonatomic,@dynamic,retain) NSDate* messageDate; 
@property (nonatomic,@dynamic,retain) NSNumber* messageType; 
@property (nonatomic,@dynamic,retain) NSNumber* messageStatus; 
@property (nonatomic,@dynamic,retain) NSNumber* isFromMe; 
@property (nonatomic,@dynamic,retain) NSNumber* sort; 
@property (nonatomic,@dynamic,retain) NSSet* words; 
@property (nonatomic,@dynamic,retain) NSNumber* groupEventType; 
@property (nonatomic,@dynamic,retain) NSString* pushName; 
@property (nonatomic,@dynamic,retain) NSNumber* flags; 
@property (nonatomic,@dynamic,retain) WAChatSession* chatSession; 
@property (nonatomic,@dynamic,retain) WAMediaItem* mediaItem; 
@property (nonatomic,@dynamic,retain) WAGroupMember* groupMember; 
@property (nonatomic,@dynamic,retain) WAMessage* parentMessage; 
@property (nonatomic,@dynamic,retain) NSSet* childMessages; 
@property (nonatomic,@dynamic,retain) NSNumber* filteredRecipientCount; 
@property (nonatomic,@dynamic,retain) NSNumber* childMessagesDeliveredCount; 
@property (nonatomic,@dynamic,retain) NSNumber* childMessagesReadCount; 
@property (assign,nonatomic) BOOL offlineStorage; 				//@synthesize offlineStorage=_offlineStorage - In the implementation block
@property (assign,nonatomic) int multiSendMediaIndex; 				//@synthesize multiSendMediaIndex=_multiSendMediaIndex - In the implementation block
@property (assign,nonatomic) int multiSendMediaCount; 				//@synthesize multiSendMediaCount=_multiSendMediaCount - In the implementation block
@property (getter=isValid,nonatomic,copy) BOOL valid; 
@property (assign,getter=isSending,nonatomic) BOOL sending; 				//@synthesize sending=_sending - In the implementation block
@property (nonatomic,copy) NSString* participantJID; 				//@synthesize participantJID=_participantJID - In the implementation block
@property (nonatomic,retain) NSData* xmppThumbnailData; 				//@synthesize xmppThumbnailData=_xmppThumbnailData - In the implementation block
@property (nonatomic,retain) WAMessage* precedingMessage; 				//@synthesize precedingMessage=_precedingMessage - In the implementation block
@property (copy) UIImage* xmppImage; 
@property (copy) UIImage* blurredImage; 
@property (retain) UIImage* imageRepresentation; 
@property (nonatomic,copy) NSString* mediaBrowserThumbnailPath; 
@property (nonatomic,copy) NSString* xmppThumbnailPath; 
@property (nonatomic,copy) NSString* chatThumbnailPath; 
@property (nonatomic,copy) NSString* mediaPath; 
@property (nonatomic,copy) WAMessageHelper* helper; 
+(unsigned)orphanedMessagesCount;
+(void)createNewOutgoingMessageWithImage:(id)arg1 inChatSession:(id)arg2 imageIndex:(int)arg3 totalImageCount:(int)arg4 completion:(id)arg5;
+(void)createNewOutgoingMessageWithAudioTrack:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
+(void)createNewOutgoingMessageWithVideoURL:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
+(void)createNewOutgoingMessageWithPlace:(id)arg1 inChatSession:(id)arg2 completion:(id)arg3;
+(id)chatThumbnailCache;
+(id)relativeLibraryPathFromAbsolutePath:(id)arg1;
+(void)createNewOutgoingMessageWithMedia:(id)arg1 inChatSession:(id)arg2 imageRepresentation:(id)arg3 messageType:(int)arg4 mediaOrigin:(int)arg5 completion:(id)arg6;
+(id)mediaDirectoryForFilename:(id)arg1 JID:(id)arg2;
+(id)mediaThumbnailCache;
+(id)mediaBrowserThumbnailForUnknownMedia;
-(void)repeatedlyFetchBetterThumbnailsWithBlock:(id)arg1;
-(void)setSending:(BOOL)arg1;
-(void)setMessageStatus:(id)arg1;
-(void)fetchRequiredDataForWAPlace:(id)arg1 withCompletion:(id)arg2;
-(void)generateMediaBrowserThumbnailWithCompletionHandler:(id)arg1;
-(void)markSendAsStartedIfNecessary;
-(void)markSendAsCompletedIfNecessary;
-(void)performBlockAfterSendMessageAttempt:(id)arg1;
-(void)setPrecedingMessage:(id)arg1;
-(void)attachIncomingMediaWithFilename:(id)arg1 data:(id)arg2 completion:(id)arg3;
-(void)attachIncomingXMPPThumbnailData:(id)arg1;
-(void)setXmppThumbnailData:(id)arg1;
-(void)fetchRequiredDataForIncomingLocationWithCompletion:(id)arg1;
-(id)addChildMessagesIfNeeded;
-(void)generateMediaThumbnailCacheKey;
-(BOOL)turnMediaItemIntoFaultIfPossible;
-(void)freeCachedData;
-(void)setImageRepresentation:(id)arg1;
-(void)prepareThumbnails:(unsigned)arg1 completion:(id)arg2;
-(void)setMultiSendMediaIndex:(int)arg1;
-(void)setMultiSendMediaCount:(int)arg1;
-(void)populateChildMessage:(id)arg1;
-(void)setOfflineStorage:(BOOL)arg1;
-(id)uniqueMediaPathWithPathExtension:(id)arg1;
-(id)cachedMediaBrowserThumbnail;
-(id)cachedChatThumbnail;
-(id)chatThumbnailReturningPermanentState:(BOOL*)arg1;
-(CGSize)chatThumbnailSize;
-(BOOL)turnIntoFaultIfPossible;
-(BOOL)hasFlag:(int)arg1;
-(void)unsetFlag:(int)arg1;
-(id)mediaPathForIncomingMediaWithFilename:(id)arg1;
-(void)fetchMediaBrowserThumbnailWithCompletionHandler:(id)arg1;
-(void)setParticipantJID:(id)arg1;
-(void)setText:(id)arg1;
-(void)setFlag:(int)arg1;
-(void)awakeFromInsert;
-(void)awakeFromFetch;
-(void)didTurnIntoFault;
@end