/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:15 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAMultiSendThumbnailBrowserItemViewDelegate
@required
-(void)multiSendThumbnailBrowserItemViewCenterDidChange(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewWasTapped(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewWantsToEnterEditMode(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewDidBeginDragging(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewDidEndDragging(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewCenterDidChange(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewWasTapped(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewWantsToEnterEditMode(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewDidBeginDragging(id):arg1 ;
-(void)multiSendThumbnailBrowserItemViewDidEndDragging(id):arg1 ;
@end
