/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:56 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMultiSendEditButton : UIButton {
	UIImage* _originalImage; 
	UIImage* _templateImage; 
	BOOL _activated; 
}
@property (assign,nonatomic) BOOL activated; 				//@synthesize activated=_activated - In the implementation block
+(id)buttonWithImage:(id)arg1;
-(void)setActivated:(BOOL)arg1;
-(void).cxx_destruct;
@end