/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:21 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAMediaPickerControllerDelegate
@optional
-(void)mediaPickerControllerNeedsRelayoutOfCustomToolbarItems(id):arg1 ;
@required
-(void)mediaPickerControllerDidFinishPresenting(id):arg1 ;
-(void)mediaPickerController(id):arg1 didFinishWithSelectedAssetURLs(id):arg2 ;
-(void)mediaPickerControllerDidFinishPresenting(id):arg1 ;
-(void)mediaPickerController(id):arg1 didFinishWithSelectedAssetURLs(id):arg2 ;
@end

@protocol UINavigationControllerDelegate
@optional
-(void)navigationController(id):arg1 willShowViewController(id):arg2 animated(BOOL):arg3 ;
-(void)navigationController(id):arg1 didShowViewController(id):arg2 animated(BOOL):arg3 ;
-(id)navigationController(id):arg1 animationControllerForOperation(int):arg2 fromViewController(id):arg3 toViewController(id):arg4 ;
-(id)navigationController(id):arg1 interactionControllerForAnimationController(id):arg2 ;
-(unsigned)navigationControllerSupportedInterfaceOrientations(id):arg1 ;
-(int)navigationControllerPreferredInterfaceOrientationForPresentation(id):arg1 ;
@end

@protocol WAMultiSendPreviewViewControllerDelegate
@required
-(void)multiSendPreviewViewController(id):arg1 didConfirmImages(id):arg2 ;
-(void)multiSendPreviewViewControllerDidCancel(id):arg1 ;
-(void)multiSendPreviewViewController(id):arg1 didConfirmImages(id):arg2 ;
-(void)multiSendPreviewViewControllerDidCancel(id):arg1 ;
@end
