/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMultiSendThumbnailBrowserAddItemButton : WAMultiSendThumbnailBrowserItemView {
	UIButton* _button; 
	int _buttonType; 
}
@property (assign,getter=isHighlighted,nonatomic) BOOL highlighted; 
@property (assign,nonatomic) int buttonType; 				//@synthesize buttonType=_buttonType - In the implementation block
-(void)updateButtonHighlight:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(void)addTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned)arg3;
-(void)setHighlighted:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setButtonType:(int)arg1;
@end