/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:55 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAMultiSendEditButtonPresenterView : UIView {
	WAMultiSendEditButton* _editButton; 
	NSMutableArray* _buttons; 
	float _expandedStateHorizontalTranslation; 
	BOOL _suppressButtonLayout; 
	BOOL _buttonsHidden; 
	float _imageEdge; 
	id<WAMultiSendEditButtonPresenterViewDelegate> _delegate; 
}
@property (assign,nonatomic) float imageEdge; 				//@synthesize imageEdge=_imageEdge - In the implementation block
@property (assign,nonatomic) BOOL buttonsHidden; 				//@synthesize buttonsHidden=_buttonsHidden - In the implementation block
@property (nonatomic,copy) UIButton* editButton; 				//@synthesize editButton=_editButton - In the implementation block
@property (assign,nonatomic) id<WAMultiSendEditButtonPresenterViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)toggleButtons:(id)arg1;
-(void)setButtonsHidden:(BOOL)arg1;
-(void)resize;
-(float)totalWidthOfButtons;
-(void)setButtonsExpanded:(BOOL)arg1;
-(void)setButtonsHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)collapseButtonsTo:(int)arg1;
-(void)expandButtonsTo:(int)arg1;
-(void)setButtonsExpandedCount:(int)arg1;
-(id)doppelganger;
-(void)setImageEdge:(float)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setDelegate:(id)arg1;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
-(void)layoutSubviews;
-(void).cxx_destruct;
-(void)addButton:(id)arg1;
@end