/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:25 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WARecipientsViewControllerDelegate
@required
-(void)recipientsController(id):arg1 didFinishWithContacts(id):arg2 ;
-(void)recipientsControllerDidCancel(id):arg1 ;
-(void)recipientsController(id):arg1 didFinishWithContacts(id):arg2 ;
-(void)recipientsControllerDidCancel(id):arg1 ;
@end

@protocol WABCastMessageComposerDelegate
@required
-(void)messageComposer(id):arg1 didFinishWithMedia(id):arg2 ;
-(void)messageComposerDidCancel(id):arg1 ;
-(void)messageComposer(id):arg1 didFinishWithMedia(id):arg2 ;
-(void)messageComposerDidCancel(id):arg1 ;
@end

@protocol WANewGroupViewControllerDelegate
@required
-(void)newGroupViewControllerDidCancel(id):arg1 ;
-(void)newGroupViewController(id):arg1 didFinishWithSubject(id):arg2 picture(id):arg3 ;
-(void)newGroupViewControllerDidCancel(id):arg1 ;
-(void)newGroupViewController(id):arg1 didFinishWithSubject(id):arg2 picture(id):arg3 ;
@end
