/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:29 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WANotificationSoundPickerCell : UITableViewCell {
	UIView* _separator; 
	BOOL _soundSelected; 
	BOOL _doubleSeparator; 
}
@property (assign,nonatomic) BOOL soundSelected; 				//@synthesize soundSelected=_soundSelected - In the implementation block
@property (assign,nonatomic) BOOL doubleSeparator; 				//@synthesize doubleSeparator=_doubleSeparator - In the implementation block
-(void)setDoubleSeparator:(BOOL)arg1;
-(void)setSoundSelected:(BOOL)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void).cxx_destruct;
@end