/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:00 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WANotificationWindow : UIWindow {
	UISwipeGestureRecognizer* _swipeGestureRecognizer; 
	UITapGestureRecognizer* _tapGestureRecognizer; 
	BOOL _forcedToHide; 
	BOOL _active; 
	id<WANotificationWindowDelegate> _notificationDelegate; 
	NSString* _contactJID; 
	NSString* _stanzaID; 
	UIView* _backgroundView; 
	NSMutableArray* _messageQueue; 
}
@property (nonatomic,copy) NSString* contactJID; 				//@synthesize contactJID=_contactJID - In the implementation block
@property (nonatomic,copy) NSString* stanzaID; 				//@synthesize stanzaID=_stanzaID - In the implementation block
@property (assign,nonatomic) id<WANotificationWindowDelegate> delegate; 				//@synthesize notificationDelegate=_notificationDelegate - In the implementation block
@property (assign,nonatomic) BOOL forcedToHide; 				//@synthesize forcedToHide=_forcedToHide - In the implementation block
@property (nonatomic,retain) UIView* backgroundView; 				//@synthesize backgroundView=_backgroundView - In the implementation block
@property (getter=isActive) BOOL active; 				//@synthesize active=_active - In the implementation block
@property (nonatomic,retain) NSMutableArray* messageQueue; 				//@synthesize messageQueue=_messageQueue - In the implementation block
+(id)sharedWindow;
+(CGRect)windowFrameForInterfaceOrientation:(int)arg1;
+(CGRect)backgroundViewFrameForInterfaceOrientation:(int)arg1;
+(struct CGAffineTransform)windowTransformForInterfaceOrientation:(int)arg1;
-(void)hideTemporarily;
-(void)postWAMessage:(id)arg1 duration:(double)arg2;
-(void)hideAnimated:(BOOL)arg1;
-(void)closeAction:(id)arg1;
-(void)setContactJID:(id)arg1;
-(void)setStanzaID:(id)arg1;
-(void)handleSwipeGesture:(id)arg1;
-(void)handleTapGesture:(id)arg1;
-(void)didChangeStatusBarFrame:(id)arg1;
-(void)rotateToStatusBarFrame:(id)arg1;
-(id)blurredBackgroundImage;
-(void)postWAMessage:(id)arg1 duration:(double)arg2 animated:(BOOL)arg3;
-(void)showNextMessage;
-(id)addContentViewForWAMessage:(id)arg1 profilePicture:(id)arg2;
-(void)removeContentViewsBelowView:(id)arg1;
-(void)removeContentView:(id)arg1;
-(void)removeContentView:(id)arg1 withAnimationDuration:(double)arg2;
-(void)hideIfEmpty;
-(void)setForcedToHide:(BOOL)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)applicationWillResignActive:(id)arg1;
-(void)show;
-(id)rootViewController;
-(void)setBackgroundView:(id)arg1;
-(void)setActive:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setMessageQueue:(id)arg1;
@end