/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:24 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAOverlayView : UIView {
	UILabel* _textLabel; 
	UIActivityIndicatorView* _activityIndicator; 
	UIImageView* _background; 
	double _startTime; 
}
@property (nonatomic,retain) NSString* text; 
@property (assign,nonatomic) double startTime; 				//@synthesize startTime=_startTime - In the implementation block
+(id)showOverlayInViewController:(id)arg1;
-(void)hideWithCompletion:(id)arg1;
-(void)loadBackground;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)setStartTime:(double)arg1;
-(void)setText:(id)arg1;
-(void).cxx_destruct;
@end