/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:18 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAPageableItemView : UIView {
	BOOL _spotlighted; 
	BOOL _allowsEditing; 
	int _index; 
	Class _pageableItemClass; 
	id<WAPageableItemViewDelegate> _delegate; 
	float _visibility; 
	float _contentWidth; 
}
@property (assign,nonatomic) int index; 				//@synthesize index=_index - In the implementation block
@property (nonatomic,retain) Class pageableItemClass; 				//@synthesize pageableItemClass=_pageableItemClass - In the implementation block
@property (assign,nonatomic) id<WAPageableItemViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) float visibility; 				//@synthesize visibility=_visibility - In the implementation block
@property (assign,nonatomic) BOOL spotlighted; 				//@synthesize spotlighted=_spotlighted - In the implementation block
@property (assign,nonatomic) float contentWidth; 				//@synthesize contentWidth=_contentWidth - In the implementation block
@property (assign,nonatomic) BOOL allowsEditing; 				//@synthesize allowsEditing=_allowsEditing - In the implementation block
-(void)configureWithItem:(id)arg1;
-(void)resetViewStateWithAnimation:(BOOL)arg1;
-(void)setSpotlighted:(BOOL)arg1;
-(void)setPageableItemClass:(Class)arg1;
-(void)setViewState:(id)arg1;
-(id)viewState;
-(void)setDelegate:(id)arg1;
-(void)prepareForReuse;
-(void)setAllowsEditing:(BOOL)arg1;
-(void).cxx_destruct;
-(void)setIndex:(int)arg1;
-(void)setVisibility:(float)arg1;
-(void)setContentWidth:(float)arg1;
@end