/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAImageCropToolViewDelegate.h>
#import <UIGestureRecognizerDelegate.h>
#import <WAMultiSendEditButtonPresenterViewDelegate.h>
#import <UIScrollViewDelegate.h>

@interface WAPageableImageScrollView : UIScrollView <WAImageCropToolViewDelegate, UIGestureRecognizerDelegate, WAMultiSendEditButtonPresenterViewDelegate, UIScrollViewDelegate> {
	WACropAwareImageView* _imageView; 
	float _scaleToRestoreAfterResize; 
	CGPoint _pointToCenterAfterResize; 
	BOOL _zoomingInProgress; 
	BOOL _suppressLayout; 
	WAImageCropToolView* _cropToolView; 
	BOOL _interactiveCroppingInProgress; 
	UITapGestureRecognizer* _singleTapGesture; 
	UITapGestureRecognizer* _doubleTapGesture; 
	CGRect _previousCropRect; 
	WAMultiSendEditButtonPresenterView* _editButtonPresenterView; 
	WAMultiSendEditButton* _rotateEditButton; 
	WAMultiSendEditButton* _cropEditButton; 
	BOOL _allowsEditing; 
	WAEditableImage* _editableImage; 
	UIButton* _deleteButton; 
	float _contentWidth; 
	id<WAPageableImageScrollViewEditingDelegate> _editingDelegate; 
	float _editButtonsAlpha; 
	struct UIEdgeInsets _edgeInsetsForMinimumZoom; 
}
@property (nonatomic,retain) WAEditableImage* editableImage; 				//@synthesize editableImage=_editableImage - In the implementation block
@property (assign,nonatomic) struct UIEdgeInsets edgeInsetsForMinimumZoom; 				//@synthesize edgeInsetsForMinimumZoom=_edgeInsetsForMinimumZoom - In the implementation block
@property (nonatomic,copy) UIButton* deleteButton; 				//@synthesize deleteButton=_deleteButton - In the implementation block
@property (nonatomic,copy) WACropAwareImageView* imageView; 				//@synthesize imageView=_imageView - In the implementation block
@property (assign,nonatomic) float contentWidth; 				//@synthesize contentWidth=_contentWidth - In the implementation block
@property (assign,nonatomic) float visibility; 
@property (assign,nonatomic) BOOL allowsEditing; 				//@synthesize allowsEditing=_allowsEditing - In the implementation block
@property (assign,nonatomic) BOOL interactiveCroppingEnabled; 
@property (assign,nonatomic) id<WAPageableImageScrollViewEditingDelegate> editingDelegate; 				//@synthesize editingDelegate=_editingDelegate - In the implementation block
@property (assign,nonatomic) float editButtonsAlpha; 				//@synthesize editButtonsAlpha=_editButtonsAlpha - In the implementation block
-(void)multiSendEditButtonPresenterViewDidChangeState:(id)arg1;
-(CGRect)zoomRectForScale:(float)arg1 withCenter:(CGPoint)arg2;
-(void)toggleZoomInOutAtPoint:(CGPoint)arg1;
-(void)setEditableImage:(id)arg1;
-(void)setEdgeInsetsForMinimumZoom:(struct UIEdgeInsets)arg1;
-(void)setInteractiveCroppingEnabled:(BOOL)arg1;
-(void)doubleTapReceived:(id)arg1;
-(void)singleTapReceived:(id)arg1;
-(void)toggleCropMode:(id)arg1;
-(void)rotateButtonTapped:(id)arg1;
-(void)setImageOrientation:(int)arg1 animated:(BOOL)arg2 completion:(id)arg3;
-(void)setInteractiveCroppingEnabled:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setEditButtonsAlpha:(float)arg1;
-(void)layoutEditingButtonsAroundRect:(CGRect)arg1;
-(void)updateEditButtonsAlpha;
-(BOOL)shouldShowEditButtons;
-(void)willChangeFrameSize;
-(void)didChangeFrameSize;
-(void)recalculateZoom;
-(void)configureImageViewWithCropping:(BOOL)arg1;
-(void)calculateForImageOfSize:(CGSize)arg1 displaySize:(CGSize*)arg2 minimumZoomScale:(float*)arg3 maximumZoomScale:(float*)arg4 initialZoomScale:(float*)arg5;
-(id)rotatedFullScreenImage;
-(void)rotateView:(id)arg1 byAngle:(float)arg2 aboutCenter:(CGPoint)arg3 scalingBy:(float)arg4;
-(void)rotateViews:(id)arg1 byAngle:(float)arg2 aroundPoint:(CGPoint)arg3 scaleChange:(float)arg4 animationDuration:(double)arg5 animationBlock:(id)arg6 completion:(id)arg7;
-(void)setZoomingEnabled:(BOOL)arg1;
-(void)setUpFullImageView:(id)arg1 croppedImageView:(id)arg2 withReferenceFrame:(CGRect)arg3 referenceFrameIsCropped:(BOOL)arg4;
-(void)imageCropToolViewNormalizedCropRectWillBeginChanging:(id)arg1;
-(void)imageCropToolViewNormalizedCropRectDidChange:(id)arg1;
-(void)imageCropToolViewNormalizedCropRectDidFinishChanging:(id)arg1;
-(id)cloneButtonForRotationAnimation:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(id)viewForZoomingInScrollView:(id)arg1;
-(void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
-(void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(void)setEditingDelegate:(id)arg1;
-(void)setAllowsEditing:(BOOL)arg1;
-(void)reset;
-(void).cxx_destruct;
-(void)deleteButtonTapped:(id)arg1;
-(void)setVisibility:(float)arg1;
-(void)setContentWidth:(float)arg1;
@end