/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:28 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAPhone_WAPhone_ : NSManagedObject {
	unsigned[1] _cd_bits_0x16deb110; 
}
+(BOOL)automaticallyNotifiesObserversOfStatus;
+(BOOL)automaticallyNotifiesObserversOfFavorite;
+(BOOL)automaticallyNotifiesObserversOfContact;
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(void)setWhatsAppID:(id)arg1;
-(void)setLabel:(id)arg1;
-(void)setPhone:(id)arg1;
-(id)whatsAppID;
-(id)status;
-(id)contact;
-(id)label;
-(id)phone;
-(Class)class;
@end