/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:36 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MKAnnotation.h>

@interface WAPlace : NSObject <MKAnnotation> {
	struct dispatch_group_s* _infoLoadingGroup; 
	NSString* _placeId; 
	NSString* _name; 
	NSString* _shortAddress; 
	NSString* _fullAddress; 
	NSString* _urlString; 
	NSString* _iconURLString; 
	CLLocation* _location; 
	UIImage* _loResMapThumbnail; 
	UIImage* _hiResMapThumbnail; 
	int _source; 
	double _distance; 
}
@property (nonatomic,retain) NSString* placeId; 				//@synthesize placeId=_placeId - In the implementation block
@property (nonatomic,retain) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSString* shortAddress; 				//@synthesize shortAddress=_shortAddress - In the implementation block
@property (nonatomic,retain) NSString* fullAddress; 				//@synthesize fullAddress=_fullAddress - In the implementation block
@property (nonatomic,retain) NSString* urlString; 				//@synthesize urlString=_urlString - In the implementation block
@property (nonatomic,retain) NSString* iconURLString; 				//@synthesize iconURLString=_iconURLString - In the implementation block
@property (nonatomic,retain) CLLocation* location; 				//@synthesize location=_location - In the implementation block
@property (assign,nonatomic) double distance; 				//@synthesize distance=_distance - In the implementation block
@property (nonatomic,retain) UIImage* loResMapThumbnail; 				//@synthesize loResMapThumbnail=_loResMapThumbnail - In the implementation block
@property (nonatomic,retain) UIImage* hiResMapThumbnail; 				//@synthesize hiResMapThumbnail=_hiResMapThumbnail - In the implementation block
@property (nonatomic,copy) int source; 				//@synthesize source=_source - In the implementation block
@property (nonatomic,copy) struct coordinate; 
@property (nonatomic,copy) NSString* title; 
@property (nonatomic,copy) NSString* subtitle; 
+(void)fetchAppleMapsThumbnailWithScale:(int)arg1 forLocation:(id)arg2 completion:(id)arg3;
+(void)fetchGoogleMapsThumbnailWithScale:(int)arg1 forLocation:(id)arg2 completion:(id)arg3;
-(BOOL)placeDetailsFetchNeeded;
-(void)fetchGooglePlaceDetailsWithCompletion:(id)arg1;
-(BOOL)loResThumbnailFetchNeeded;
-(void)fetchLoResThumbnailWithCompletion:(id)arg1;
-(BOOL)hiResThumbnailFetchNeeded;
-(void)fetchHiResThumbnailWithCompletion:(id)arg1;
-(void)setShortAddress:(id)arg1;
-(void)setLoResMapThumbnail:(id)arg1;
-(void)setHiResMapThumbnail:(id)arg1;
-(void)setFullAddress:(id)arg1;
-(void)setIconURLString:(id)arg1;
-(id)initWithSource:(int)arg1;
-(BOOL)isEqual:(id)arg1;
-(unsigned)hash;
-(id)description;
-(void)setName:(id)arg1;
-(int)compare:(id)arg1;
-(void).cxx_destruct;
-(void)setUrlString:(id)arg1;
-(void)setDistance:(double)arg1;
-(void)setPlaceId:(id)arg1;
-(void)setLocation:(id)arg1;
@end