/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:49 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WABlacklistViewControllerDelegate.h>
#import <BlacklistViewControllerDelegate.h>

@interface WAPrivacySettingsViewController : WAStaticTableViewController <WABlacklistViewControllerDelegate, BlacklistViewControllerDelegate> {
	WATableRow* _lastSeenRow; 
	WATableRow* _profilePicRow; 
	WATableRow* _statusRow; 
	WATableRow* _blockedRow; 
	WAActivityLabel* _activityLabel; 
	NSDate* _activityStartTime; 
	BOOL _workingWithBlocked; 
	BOOL _needPrivacyRefresh; 
	WAPrivacyPolicy* _privacyPolicy; 
	NSString* _lastSeenTitle; 
	NSString* _profilePhotoTitle; 
	NSString* _statusMessageTitle; 
}
@property (retain) WAPrivacyPolicy* privacyPolicy; 				//@synthesize privacyPolicy=_privacyPolicy - In the implementation block
@property (retain) NSString* lastSeenTitle; 				//@synthesize lastSeenTitle=_lastSeenTitle - In the implementation block
@property (retain) NSString* profilePhotoTitle; 				//@synthesize profilePhotoTitle=_profilePhotoTitle - In the implementation block
@property (retain) NSString* statusMessageTitle; 				//@synthesize statusMessageTitle=_statusMessageTitle - In the implementation block
-(void)updateTableViewCell:(id)arg1 withBlockedCount:(int)arg2;
-(void)chatStorageDidUpdateBlacklist:(id)arg1;
-(void)privacyPolicyDidChange:(id)arg1;
-(void)setLastSeenTitle:(id)arg1;
-(void)setProfilePhotoTitle:(id)arg1;
-(void)setStatusMessageTitle:(id)arg1;
-(void)showBlacklistController;
-(void)updatePrivacyValues;
-(void)blacklistViewController:(id)arg1 didChangeBlacklistSize:(int)arg2;
-(void)blacklistViewControllerDidFinish:(id)arg1;
-(void)blacklistViewControllerDidCancel:(id)arg1;
-(void)setPrivacyPolicy:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)applicationDidEnterBackground:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end