/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAProfileTableViewCell : UITableViewCell {
	UIView* _topSeparator; 
	UIView* _bottomSeparator; 
}
-(void)createSeparators;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)awakeFromNib;
-(void).cxx_destruct;
@end