/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAPushSoundSet : NSObject {
	NSString* _name; 
	NSArray* _sounds; 
}
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSArray* sounds; 				//@synthesize sounds=_sounds - In the implementation block
+(id)setWithName:(id)arg1 sounds:(id)arg2;
-(unsigned)indexOfPushSoundWithFilename:(id)arg1;
-(id)pushSoundAtIndex:(unsigned)arg1;
-(id)initWithName:(id)arg1 sounds:(id)arg2;
-(void).cxx_destruct;
@end