/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:59 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAPushSound : NSObject {
	BOOL _defaultSound; 
	NSString* _name; 
	NSString* _filename; 
}
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString* filename; 				//@synthesize filename=_filename - In the implementation block
@property (assign,getter=isDefaultSound,nonatomic) BOOL defaultSound; 				//@synthesize defaultSound=_defaultSound - In the implementation block
+(id)pushSoundWithName:(id)arg1 filename:(id)arg2;
-(id)initWithName:(id)arg1 filename:(id)arg2;
-(int)compare:(id)arg1;
-(void).cxx_destruct;
-(void)setDefaultSound:(BOOL)arg1;
@end