/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:43 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAPushToTalkCell : WAMessageCell {
	UIButton* _buttonPushToTalkAction; 
	UISlider* _pttPlayerScrubber; 
	UISlider* _pttUploadScrubber; 
	UIImageView* _micIndicator; 
	UIImageView* _personImage; 
	UILabel* _audioDurationLabel; 
	BOOL _playerWasPlaying; 
	NSTimer* _uploadScrubberTimer; 
	int _uploadScrubberPosition; 
}
+(float)heightForCellData:(id)arg1 width:(float)arg2 editing:(BOOL)arg3;
-(void)configureCellUpdatingAllContents:(BOOL)arg1 animated:(BOOL)arg2;
-(void)showPopupMenu;
-(void)setCellData:(id)arg1 delegate:(id)arg2;
-(void)setHighlightState:(BOOL)arg1 forBubbleView:(id)arg2 animated:(BOOL)arg3;
-(void)pttSliderActionStartEditing:(id)arg1;
-(void)pttSliderActionEditDone:(id)arg1;
-(void)uploadScrubberUpdate:(id)arg1;
-(void)updateDurationLabel;
-(void)updatePushToTalkControls;
-(void)updatePlayedIndication;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setProgress:(float)arg1;
-(BOOL)isAnimating;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(BOOL)selectable;
-(void).cxx_destruct;
-(void)setDimmed:(BOOL)arg1;
@end