/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:50 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WASampleChatCellData : WAChatCellData {
	BOOL _incoming; 
}
+(id)cellDataWithText:(id)arg1 isIncoming:(BOOL)arg2;
-(id)initWithText:(id)arg1 isIncoming:(BOOL)arg2;
-(int)mediaOrigin;
-(int)messageStatus;
-(id)messageTimestampString;
-(BOOL)isSenderUnknown;
-(BOOL)needToShowAlert;
-(id)fromName;
-(id)pushName;
-(id)nameColor;
-(int)messageType;
-(id)message;
-(BOOL)isFromMe;
-(id)shortName;
-(BOOL)isSending;
-(id)messageID;
-(BOOL)isGroupMessage;
@end