/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:33 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <AudioSessionDelegate.h>

@interface WASoundSwitcher : UIView <AudioSessionDelegate> {
	AudioSession* _audioSession; 
	UIButton* _buttonSwitcher; 
}
@property (assign) BOOL activated; 
-(void)switcherAction:(id)arg1;
-(void)audioSessionStateChanged:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)drawRect:(CGRect)arg1;
-(void)setActivated:(BOOL)arg1;
-(void).cxx_destruct;
@end