/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAStatus : NSManagedObject {
}
@property (nonatomic,@dynamic,retain) NSDate* date; 
@property (nonatomic,@dynamic,retain) NSString* text; 
@property (nonatomic,@dynamic,retain) NSString* whatsAppID; 
@property (nonatomic,@dynamic,retain) NSString* pictureID; 
@property (nonatomic,@dynamic,retain) NSString* picturePath; 
@property (nonatomic,@dynamic,retain) NSDate* pictureDate; 
@property (nonatomic,@dynamic,retain) WAPhone* phone; 
@end