/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:17 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAStaticTableViewController : WATableViewController {
	NSMutableArray* _sections; 
}
@property (nonatomic,retain) NSArray* sections; 				//@synthesize sections=_sections - In the implementation block
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
-(id)initWithStyle:(int)arg1;
-(void).cxx_destruct;
-(void)setSections:(id)arg1;
-(id)addSection;
-(id)rowAtIndexPath:(id)arg1;
@end