/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:54 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <StatusEditControllerDelegate.h>
#import <UIActionSheetDelegate.h>

@interface WAStatusListEditViewController : UITableViewController <StatusEditControllerDelegate, UIActionSheetDelegate> {
	id<WAStatusListEditViewControllerDelegate> _delegate; 
	UILabel* _labelTitle; 
}
+(id)controllerWithDelegate:(id)arg1;
-(void)deleteAllAction:(id)arg1;
-(void)doneAction:(id)arg1;
-(void)statusEditController:(id)arg1 didAddStatus:(id)arg2;
-(void)statusEditController:(id)arg1 didSaveStatus:(id)arg2;
-(void)statusEditControllerDidCancel:(id)arg1;
-(void)dealloc;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
-(id)initWithDelegate:(id)arg1;
@end