/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:23 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAStatus_WAStatus_ : NSManagedObject {
	unsigned[1] _cd_bits_0x16f9abd0; 
}
+(id)_PFPlaceHolderSingleton;
+(id)_PFMOClassFactoryData;
+(Class)superclass;
+(Class)class;
+(BOOL)_isGeneratedClass;
+(void)release;
+(id)retain;
-(id)whatsAppID;
-(id)pictureID;
-(id)phone;
-(id)pictureDate;
-(id)picturePath;
-(id)text;
-(Class)class;
@end