/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:06 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WASupportEmailComposer : NSObject {
}
+(void)composeEmailWithProblemDescription:(id)arg1 context:(id)arg2 attachment:(id)arg3 parentController:(id)arg4 mailDelegate:(id)arg5;
@end