/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:06:08 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WATabBarController : UITabBarController {
	WANotificationBar* _notificationBar; 
}
@property (nonatomic,retain) WANotificationBar* notificationBar; 				//@synthesize notificationBar=_notificationBar - In the implementation block
-(void)setNotificationBar:(id)arg1;
-(BOOL)shouldAutorotate;
-(void)dismissViewControllerAnimated:(BOOL)arg1 completion:(id)arg2;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)dismissModalViewControllerAnimated:(BOOL)arg1;
-(void).cxx_destruct;
@end