/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:17 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WATableSection : NSObject {
	NSMutableArray* _rows; 
	NSString* _headerText; 
	NSString* _footerText; 
}
@property (nonatomic,retain) NSArray* rows; 				//@synthesize rows=_rows - In the implementation block
@property (nonatomic,retain) NSString* headerText; 				//@synthesize headerText=_headerText - In the implementation block
@property (nonatomic,retain) NSString* footerText; 				//@synthesize footerText=_footerText - In the implementation block
-(void)setFooterText:(id)arg1;
-(id)init;
-(void).cxx_destruct;
-(void)setRows:(id)arg1;
-(void)addRow:(id)arg1;
-(void)setHeaderText:(id)arg1;
@end