/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIActionSheetDelegate.h>
#import <UIAlertViewDelegate.h>
#import <ABNewPersonViewControllerDelegate.h>
#import <ABPeoplePickerNavigationControllerDelegate.h>
#import <AddContactInfoViewControllerDelegate.h>
#import <ABPersonViewControllerDelegate.h>

@interface WATextBubbleView : WABubbleView <UIActionSheetDelegate, UIAlertViewDelegate, ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate, AddContactInfoViewControllerDelegate, ABPersonViewControllerDelegate> {
	NSArray* _accessibleElements; 
	TextBlock* _selectedTextBlock; 
	NSMutableArray* _supportedMapsURLs; 
	BOOL _actionSheetShown; 
	NSArray* _messages; 
}
@property (nonatomic,retain) NSArray* messages; 				//@synthesize messages=_messages - In the implementation block
+(CGSize)sizeForMessages:(id)arg1 maxWidth:(float)arg2 timestampString:(id)arg3 messageStatus:(int)arg4 fromName:(id)arg5 pushName:(id)arg6 showListIcon:(BOOL)arg7 isIncoming:(BOOL)arg8;
+(CGSize)sizeForName:(id)arg1 pushName:(id)arg2 maxWidth:(float)arg3;
-(void)addContactInfoViewControllerDidCancel:(id)arg1;
-(void)addContactInfoViewControllerDidFinish:(id)arg1;
-(void)setMessages:(id)arg1;
-(void)dismissPickerAndContinueWithPerson:(void*)arg1;
-(void)createNewContact;
-(id)initWithIncomingState:(BOOL)arg1 delegate:(id)arg2;
-(void)highlightUrl:(BOOL)arg1;
-(void)setAddressForPerson:(void*)arg1;
-(void)updateAccessibilityInfo;
-(void)launchGmail;
-(void)launchSparrow;
-(void)addFieldToContact;
-(void)launchSkype;
-(void)showActionSheet;
-(void)openUrl;
-(BOOL)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
-(void)newPersonViewController:(id)arg1 didCompleteWithNewPerson:(void*)arg2;
-(id)bubbleText;
-(void)drawRect:(CGRect)arg1;
-(CGSize)sizeThatFits:(CGSize)arg1;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(BOOL)isAccessibilityElement;
-(int)accessibilityElementCount;
-(id)accessibilityElementAtIndex:(int)arg1;
-(int)indexOfAccessibilityElement:(id)arg1;
-(void).cxx_destruct;
-(void)peoplePickerNavigationControllerDidCancel:(id)arg1;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4;
@end