/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:05 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAThumbsTableViewCell : UITableViewCell {
	NSMutableArray* _thumbnailViews; 
	NSBlockOperation* _thumbnailLoadingOp; 
	NSMutableArray* _thumbnails; 
	int _loadingID; 
	NSMutableSet* _selectedIndexes; 
	int _mediaIndex; 
	id<WAThumbsTableViewCellDelegate> _delegate; 
	int _thumbnailCount; 
}
@property (assign,nonatomic) int mediaIndex; 				//@synthesize mediaIndex=_mediaIndex - In the implementation block
@property (assign,nonatomic) id<WAThumbsTableViewCellDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) int thumbnailCount; 				//@synthesize thumbnailCount=_thumbnailCount - In the implementation block
@property (nonatomic,copy) NSArray* thumbnailViews; 				//@synthesize thumbnailViews=_thumbnailViews - In the implementation block
+(int)thumbnailCountForRowOfWidth:(float)arg1;
-(void)setMediaIndex:(int)arg1;
-(void)loadThumbnailsForMessages:(id)arg1 inQueue:(id)arg2;
-(void)setSelectedIndexes:(id)arg1;
-(void)setThumbnailState:(unsigned)arg1 atIndex:(unsigned)arg2;
-(void)cellTapped:(id)arg1;
-(void)cancelThumbnailLoading;
-(void)loadThumbnailsForMessages:(id)arg1 loadingID:(int)arg2 inOperation:(id)arg3;
-(unsigned)thumbnailStateAtIndex:(unsigned)arg1;
-(void)refreshSelectionState;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)prepareForReuse;
-(void).cxx_destruct;
-(void)setThumbnails:(id)arg1;
@end