/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:15 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WATooltipView : UIView {
	UIButton* _buttonClose; 
	NSString* _text; 
	UIFont* _font; 
	BOOL _arrowDown; 
	CGRect _toolTipRect; 
	float _arrowOffset; 
	BOOL _fadingIn; 
	BOOL _fadingOut; 
	BOOL _buttonFired; 
	float _leftRightPadding; 
	float _topBottomPadding; 
}
@property (nonatomic,retain) NSString* text; 				//@synthesize text=_text - In the implementation block
@property (nonatomic,retain) UIFont* font; 				//@synthesize font=_font - In the implementation block
-(void)setTooltipVisible:(BOOL)arg1 animated:(BOOL)arg2;
-(void)closeAction:(id)arg1;
-(void)dismissTooltip;
-(void)drawRectiOS7:(CGRect)arg1;
-(void)drawRectiOS6:(CGRect)arg1;
-(CGRect)mainBubbleRect7;
-(void)drawTextWithDelta:(CGPoint)arg1;
-(void)adjustSizeToContent;
-(void)updateOrientation;
-(id)siblingView;
-(void)fireButton:(id)arg1;
-(void)deviceOrientationDidChange:(id)arg1;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
-(id)init;
-(void)layoutSubviews;
-(void)setFont:(id)arg1;
-(void)setText:(id)arg1;
-(void)setTargetRect:(CGRect)arg1 inView:(id)arg2;
-(void).cxx_destruct;
@end