/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:53 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <WAScrollTracking.h>

@interface WATranslucentTableViewCell : UITableViewCell <WAScrollTracking> {
	UIImageView* _blurMaskImageView; 
	BOOL _blurEnabled; 
	UIImageView* _blurOverlayImageView; 
	id<WATranslucentTableViewCellDelegate> _delegate; 
}
@property (nonatomic,copy) UIImageView* blurOverlayImageView; 				//@synthesize blurOverlayImageView=_blurOverlayImageView - In the implementation block
@property (assign,nonatomic) id<WATranslucentTableViewCellDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) float translucency; 
@property (nonatomic,copy) BOOL blurEnabled; 				//@synthesize blurEnabled=_blurEnabled - In the implementation block
-(id)blurImageMask;
-(id)blurMaskTrackingView;
-(void)updateBlurredBackground;
-(void)setDidScroll;
-(void)setTranslucency:(float)arg1;
-(void)setDelegate:(id)arg1;
-(void)didMoveToWindow;
-(void)setFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)tintColorDidChange;
-(void).cxx_destruct;
@end