/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:41 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAUserProfileInfo : NSObject {
	NSManagedObjectID* _chatSessionID; 
	NSData* _pictureData; 
	NSData* _thumbnailData; 
}
@property (nonatomic,copy) NSManagedObjectID* chatSessionID; 				//@synthesize chatSessionID=_chatSessionID - In the implementation block
@property (nonatomic,retain) NSData* pictureData; 				//@synthesize pictureData=_pictureData - In the implementation block
@property (nonatomic,retain) NSData* thumbnailData; 				//@synthesize thumbnailData=_thumbnailData - In the implementation block
-(void)setChatSessionID:(id)arg1;
-(void)setPictureData:(id)arg1;
-(void).cxx_destruct;
-(void)setThumbnailData:(id)arg1;
@end