/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:50 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAWallpaperImageView : UIImageView {
	UIButton* _button; 
	id<WAWallpaperImageViewDelegate> _delegate; 
	unsigned _wallpaperLibraryImageIndex; 
}
@property (assign,nonatomic) id<WAWallpaperImageViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) unsigned wallpaperLibraryImageIndex; 				//@synthesize wallpaperLibraryImageIndex=_wallpaperLibraryImageIndex - In the implementation block
-(void)imageTapped:(id)arg1;
-(void)loadThumbnailIfNeededAsynchronously;
-(id)initWithWallpaperLibraryImageIndex:(unsigned)arg1;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end