/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:31 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface WAWallpaperLibrary : NSObject {
	NSArray* _imagePaths; 
	NSCache* _fullsizeImages; 
	NSCache* _thumbnails; 
}
+(id)sharedLibrary;
+(CGSize)thumbnailSize;
-(void)fetchThumbnailForImageAtIndex:(unsigned)arg1 completion:(id)arg2;
-(void)fetchFullsizeImageAtIndex:(unsigned)arg1 completion:(id)arg2;
-(id)init;
-(unsigned)numberOfItems;
-(void).cxx_destruct;
-(id)imageAtIndex:(unsigned)arg1;
@end