/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:57 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>

@interface WebContentViewController : UIViewController <UIWebViewDelegate> {
	UIWebView* _webView; 
	WAProgressHUD* _progressHUD; 
	BOOL _shouldGoBack; 
	NSString* _urlString; 
}
@property (nonatomic,retain) NSString* urlString; 				//@synthesize urlString=_urlString - In the implementation block
+(id)controllerWithTitle:(id)arg1 urlString:(id)arg2;
-(void)goBackIfNecessary;
-(void)closeAction:(id)arg1;
-(void)dealloc;
-(void)loadView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidStartLoad:(id)arg1;
-(void)webViewDidFinishLoad:(id)arg1;
-(void).cxx_destruct;
-(void)setUrlString:(id)arg1;
@end