/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:32 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPContactsSyncContext : NSObject {
	int _mode; 
	int _context; 
	NSString* _sid; 
	unsigned _index; 
	NSNumber* _timeout; 
	id _delegate; 
	NSThread* _thread; 
	SEL _finishedSelector; 
	SEL _failedSelector; 
	id _userData; 
	NSMutableArray* _contacts; 
	NSMutableArray* _result; 
}
@property (assign,nonatomic) int mode; 				//@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) int context; 				//@synthesize context=_context - In the implementation block
@property (nonatomic,retain) NSString* sid; 				//@synthesize sid=_sid - In the implementation block
@property (assign,nonatomic) unsigned index; 				//@synthesize index=_index - In the implementation block
@property (nonatomic,retain) NSNumber* timeout; 				//@synthesize timeout=_timeout - In the implementation block
@property (nonatomic,retain) id delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSThread* thread; 				//@synthesize thread=_thread - In the implementation block
@property (assign,nonatomic) SEL finishedSelector; 				//@synthesize finishedSelector=_finishedSelector - In the implementation block
@property (assign,nonatomic) SEL failedSelector; 				//@synthesize failedSelector=_failedSelector - In the implementation block
@property (nonatomic,retain) id userData; 				//@synthesize userData=_userData - In the implementation block
@property (nonatomic,retain) NSMutableArray* contacts; 				//@synthesize contacts=_contacts - In the implementation block
@property (nonatomic,retain) NSMutableArray* result; 				//@synthesize result=_result - In the implementation block
-(void)setSid:(id)arg1;
-(void)setFinishedSelector:(SEL)arg1;
-(void)setFailedSelector:(SEL)arg1;
-(void)setContacts:(id)arg1;
-(void)setTimeout:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)setContext:(int)arg1;
-(void)setMode:(int)arg1;
-(void)setUserData:(id)arg1;
-(void).cxx_destruct;
-(void)setIndex:(unsigned)arg1;
-(void)setResult:(id)arg1;
-(void)setThread:(id)arg1;
@end