/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:36 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPStatus : NSObject {
	NSString* _text; 
	NSString* _jid; 
	NSDate* _timestamp; 
	unsigned _error; 
}
@property (nonatomic,retain) NSString* text; 				//@synthesize text=_text - In the implementation block
@property (nonatomic,retain) NSString* jid; 				//@synthesize jid=_jid - In the implementation block
@property (nonatomic,retain) NSDate* timestamp; 				//@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) unsigned error; 				//@synthesize error=_error - In the implementation block
-(void)setJid:(id)arg1;
-(void)setError:(unsigned)arg1;
-(id)init;
-(void)setTimestamp:(id)arg1;
-(void)setText:(id)arg1;
-(void).cxx_destruct;
@end