/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:11 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPPresenceStanza : XMPPStanza {
}
@property (assign,nonatomic) int type; 
@property (nonatomic,retain) NSString* nickname; 
-(id)initWithFromJID:(id)arg1 toJID:(id)arg2 type:(int)arg3;
-(id)stringsForTypes;
-(void)setType:(int)arg1;
-(id)stringForType:(int)arg1;
-(int)typeForString:(id)arg1;
-(void)setNickname:(id)arg1;
@end