/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:10 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPRC4Coder : NSObject {
	NSData* _key; 
	struct _CCCryptor* _cryptor; 
}
-(void)clean;
-(void)drop:(int)arg1;
-(id)process:(id)arg1;
-(void)reset:(id)arg1;
-(void)dealloc;
-(void).cxx_destruct;
@end