/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <XMPPStreamDelegate.h>
#import <XMPPRequestManagerDelegate.h>
#import <ReachabilityDelegate.h>

@interface XMPPConnection : NSObject <XMPPStreamDelegate, XMPPRequestManagerDelegate, ReachabilityDelegate> {
	XMPPStream* _stream; 
	NSThread* _xmppThread; 
	NSConditionLock* _lock; 
	id<XMPPConnectionDelegate> _delegate; 
	XMPPRequestManager* _requests; 
	NSMutableDictionary* _clientData; 
	NSMutableDictionary* _messageData; 
	Reachability* _hostReach; 
	NSURLConnection* _hostReachConnection; 
	int _lastPresence; 
	BOOL _initialPushConfigSent; 
	BOOL _firstOfflineMessageReceived; 
	EmojiConverter* _emojiConverter; 
	BOOL _convertEmoji; 
	BOOL _waitingForMessages; 
	NSNumber* _state; 
	NSNumber* _type; 
	NSNumber* _network; 
	NSString* _accountType; 
	NSDate* _accountCreation; 
	NSDate* _accountExpiration; 
	NSNumber* _enableConnection; 
	NSNumber* _backgroundConnectionAttempts; 
	int _serverTimeShift; 
	NSNumber* _connecting; 
	NSNumber* _disconnecting; 
	NSNumber* _reconnecting; 
	NSNumber* _connected; 
	NSDate* _dateConnecting; 
	NSDate* _dateConnected; 
}
@property (retain) NSNumber* state; 				//@synthesize state=_state - In the implementation block
@property (retain) NSNumber* type; 				//@synthesize type=_type - In the implementation block
@property (retain) NSNumber* network; 				//@synthesize network=_network - In the implementation block
@property (retain) NSString* accountType; 				//@synthesize accountType=_accountType - In the implementation block
@property (retain) NSDate* accountCreation; 				//@synthesize accountCreation=_accountCreation - In the implementation block
@property (retain) NSDate* accountExpiration; 				//@synthesize accountExpiration=_accountExpiration - In the implementation block
@property (retain) NSString* xmppUser; 
@property (copy) NSData* xmppPassword; 
@property (copy) NSString* myJID; 
@property (copy) NSString* currentIP; 
@property (copy) NSString* currentHost; 
@property (copy) int currentPort; 
@property (retain) NSNumber* enableConnection; 				//@synthesize enableConnection=_enableConnection - In the implementation block
@property (assign) BOOL contactsAccessAllowed; 
@property (copy) BOOL passiveMode; 
@property (retain) NSNumber* backgroundConnectionAttempts; 				//@synthesize backgroundConnectionAttempts=_backgroundConnectionAttempts - In the implementation block
@property (assign) int serverTimeShift; 				//@synthesize serverTimeShift=_serverTimeShift - In the implementation block
@property (retain) NSNumber* connecting; 				//@synthesize connecting=_connecting - In the implementation block
@property (retain) NSNumber* disconnecting; 				//@synthesize disconnecting=_disconnecting - In the implementation block
@property (retain) NSNumber* reconnecting; 				//@synthesize reconnecting=_reconnecting - In the implementation block
@property (retain) NSNumber* connected; 				//@synthesize connected=_connected - In the implementation block
@property (retain) NSDate* dateConnecting; 				//@synthesize dateConnecting=_dateConnecting - In the implementation block
@property (retain) NSDate* dateConnected; 				//@synthesize dateConnected=_dateConnected - In the implementation block
@property (assign) BOOL waitingForMessages; 				//@synthesize waitingForMessages=_waitingForMessages - In the implementation block
+(id)normalizedNumber;
+(id)normalizedNumber:(id)arg1;
-(void)setHint:(id)arg1;
-(void)setEnableConnection:(id)arg1;
-(void)drop;
-(void)updatePresence;
-(void)checkConnectionState;
-(BOOL)isDisconnecting;
-(void)setBackgroundConnectionAttempts:(id)arg1;
-(BOOL)isReconnecting;
-(void)setStatus:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)reachability:(id)arg1 networkStatusChanged:(id)arg2;
-(BOOL)storePassword:(id)arg1;
-(void)reportFieldStatsWithName:(id)arg1 info:(id)arg2;
-(void)getGroupInfo:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)sendMessage:(id)arg1 toRecipients:(id)arg2;
-(void)sendMessages:(id)arg1;
-(void)requestBlacklistWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2 didFailSelector:(SEL)arg3 userData:(id)arg4 withTimeout:(id)arg5;
-(void)createGroup:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)leaveFromGroup:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)participantListForGroup:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)participatingGroupsWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2 didFailSelector:(SEL)arg3 userData:(id)arg4 withTimeout:(id)arg5;
-(void)addParticipantsToGroup:(id)arg1 participants:(id)arg2 name:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)setProfilePicture:(id)arg1 thumbnail:(id)arg2 to:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)cleanDirtyFlags:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 withTimeout:(id)arg5;
-(void)getProfilePictureFrom:(id)arg1 type:(int)arg2 identifier:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)getProfilePictureIDsForJIDs:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)setNotificationsConfig:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)requestAllListsWithUserData:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 withTimeout:(id)arg5;
-(int)lastChatStateForJID:(id)arg1;
-(void)setConnecting:(id)arg1;
-(void)setDisconnecting:(id)arg1;
-(void)setReconnecting:(id)arg1;
-(void)setDateConnecting:(id)arg1;
-(void)setDateConnected:(id)arg1;
-(void)setXmppUser:(id)arg1;
-(void)reloadPassword;
-(void)xmppThread;
-(void)systemTimeChanged:(id)arg1;
-(void)setServerTimeShift:(int)arg1;
-(void)setContactsAccessAllowed:(BOOL)arg1;
-(void)internalClose;
-(void)internalDrop;
-(void)internalCheckConnectionState;
-(id)clientDataForJID:(id)arg1;
-(id)convertOutgoingEmojiString:(id)arg1;
-(void)timeoutForMessage:(id)arg1;
-(void)startMessageTimeout:(id)arg1;
-(void)copyMessageDataFrom:(id)arg1 to:(id)arg2;
-(void)internalSendMessage:(id)arg1;
-(void)internalSendMessage:(id)arg1 toRecipients:(id)arg2;
-(void)internalSendMessages:(id)arg1;
-(void)internalSendPlayedReceiptForMessage:(id)arg1;
-(void)internalAutorizationRequestForJID:(id)arg1;
-(void)internalChangeChatState:(id)arg1 forJID:(id)arg2;
-(id)createPresenceWithType:(int)arg1 nickname:(id)arg2;
-(void)internalSendPresence:(id)arg1;
-(void)internalUpdatePresence;
-(void)internalSendPresenceWithNickname:(id)arg1;
-(void)failedNotConnected:(id)arg1 thread:(id)arg2 selector:(SEL)arg3 userData:(id)arg4;
-(void)internalSetNotificationsConfig:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalSendPushConfig:(id)arg1 notifications:(id)arg2 delegate:(id)arg3 thread:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)sendInitialPushConfigSuccessWithUserData:(id)arg1;
-(void)sendInitialPushConfigFailed:(id)arg1 withUserData:(id)arg2;
-(void)sendInitialPushConfig;
-(void)internalSetProfilePicture:(id)arg1 thumbnail:(id)arg2 to:(id)arg3 delegate:(id)arg4 thread:(id)arg5 didFinishSelector:(SEL)arg6 didFailSelector:(SEL)arg7 userData:(id)arg8 withTimeout:(id)arg9;
-(void)internalGetProfilePictureFrom:(id)arg1 type:(id)arg2 identifier:(id)arg3 delegate:(id)arg4 thread:(id)arg5 didFinishSelector:(SEL)arg6 didFailSelector:(SEL)arg7 userData:(id)arg8 withTimeout:(id)arg9;
-(void)internalGetProfilePictureIDsForJIDs:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalRequestBlacklisWithDelegate:(id)arg1 thread:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)internalSetBlacklist:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalDeleteAccount:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalNormalizeNumber:(id)arg1 countryCode:(id)arg2 delegate:(id)arg3 thread:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)internalChangeNumber:(id)arg1 password:(id)arg2 delegate:(id)arg3 thread:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)internalSetStatus:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalGetStatusForJIDs:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)pingSuccessWithUserData:(id)arg1;
-(void)pingFailed:(id)arg1 withUserData:(id)arg2;
-(void)internalGetLastSeenForJID:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)requestLastActivitySuccess:(id)arg1 withUserData:(id)arg2;
-(void)requestLastActivityFailed:(id)arg1 withUserData:(id)arg2;
-(void)internalRequestUploadUrlForFileHash:(id)arg1 origHash:(id)arg2 filetype:(id)arg3 filesize:(id)arg4 mediaIndex:(id)arg5 totalMediaCount:(id)arg6 delegate:(id)arg7 thread:(id)arg8 didFinishSelector:(SEL)arg9 didFailSelector:(SEL)arg10 userData:(id)arg11 withTimeout:(id)arg12;
-(void)requestUploadUrlForFileHash:(id)arg1 origHash:(id)arg2 filetype:(id)arg3 filesize:(id)arg4 mediaIndex:(int)arg5 totalMediaCount:(int)arg6 delegate:(id)arg7 didFinishSelector:(SEL)arg8 didFailSelector:(SEL)arg9 userData:(id)arg10 withTimeout:(id)arg11;
-(void)internalAckMediaForUrl:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalSendRecoveryToken:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(id)passwordFilePath;
-(void)internalContactsSync:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 withTimeout:(id)arg6;
-(void)contactsSyncSuccess:(id)arg1 wait:(id)arg2 version:(id)arg3 userdata:(id)arg4;
-(void)contactsSyncFail:(id)arg1 backoff:(id)arg2 userdata:(id)arg3;
-(id)contactsSyncModeTypeToString:(int)arg1;
-(id)contactsSyncContextTypeToString:(int)arg1;
-(void)internalSendDeliveryReceiptsForStanzas:(id)arg1;
-(void)sendInitialPushConfigIfNeeded;
-(void)setWaitingForMessages:(BOOL)arg1;
-(void)waitingForMessagesTimeout;
-(void)changeStatus:(int)arg1 forMessageWithStanzaID:(id)arg2 fromJID:(id)arg3 data:(id)arg4;
-(void)setAccountCreation:(id)arg1;
-(void)setAccountExpiration:(id)arg1;
-(void)sendIQResponse:(id)arg1;
-(void)endMessageTimeout:(id)arg1;
-(void)sendDeliveryReceiptAck:(id)arg1;
-(void)setChatState:(int)arg1 forJID:(id)arg2;
-(void)sendDeliveryReceiptForStanza:(id)arg1 addressBookContainsContact:(id)arg2;
-(void)processIncomingErrorMessage:(id)arg1;
-(void)processIncomingMessageStanzas:(id)arg1;
-(void)cancelMessageTimeout:(id)arg1;
-(void)reachabilityHttpCheck;
-(void)checkConnection;
-(id)deliveryReceiptForMessageStanza:(id)arg1;
-(void)internalCreateGroup:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalGetGroupInfo:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalSetGroupSubject:(id)arg1 subject:(id)arg2 name:(id)arg3 delegate:(id)arg4 thread:(id)arg5 didFinishSelector:(SEL)arg6 didFailSelector:(SEL)arg7 userData:(id)arg8 withTimeout:(id)arg9;
-(void)internalAddParticipantsToGroup:(id)arg1 participants:(id)arg2 name:(id)arg3 delegate:(id)arg4 thread:(id)arg5 didFinishSelector:(SEL)arg6 didFailSelector:(SEL)arg7 userData:(id)arg8 withTimeout:(id)arg9;
-(void)internalLeaveFromGroup:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalParticipantListForGroup:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)internalParticipatingGroupsWithDelegate:(id)arg1 thread:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)internalQueryServerPropertiesWithDelegate:(id)arg1 thread:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 withTimeout:(id)arg5;
-(void)internalQueryPrivacySettingsWithDelegate:(id)arg1 thread:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 withTimeout:(id)arg5 userData:(id)arg6;
-(void)internalSetPrivacySettingsWithDelegate:(id)arg1 thread:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 withTimeout:(id)arg5 settings:(id)arg6 userData:(id)arg7;
-(void)internalRemoveParticipantsFromGroup:(id)arg1 participants:(id)arg2 delegate:(id)arg3 thread:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)internalCleanDirtyFlags:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 withTimeout:(id)arg6;
-(void)internalDeleteListFromServer:(id)arg1 userData:(id)arg2 delegate:(id)arg3 thread:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 withTimeout:(id)arg7;
-(void)internalRequestAllListsWithUserData:(id)arg1 delegate:(id)arg2 thread:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 withTimeout:(id)arg6;
-(void)internalReportFieldStatsWithName:(id)arg1 info:(id)arg2;
-(void)passiveMode:(id)arg1;
-(void)xmppStreamDidAuthenticate:(id)arg1 kind:(id)arg2 creation:(id)arg3 expiration:(id)arg4 serverTimeShift:(int)arg5;
-(void)xmppStreamDidNotAuthenticate:(id)arg1;
-(void)xmppStreamDidOpen:(id)arg1;
-(void)xmppStreamDidClose:(id)arg1;
-(void)xmppStream:(id)arg1 didReceiveIQ:(id)arg2;
-(void)xmppStream:(id)arg1 didReceiveMessages:(id)arg2;
-(void)xmppStream:(id)arg1 didReceivePresence:(id)arg2;
-(void)xmppStream:(id)arg1 didReceiveCustomStanza:(id)arg2;
-(void)logStanza:(id)arg1 recv:(BOOL)arg2;
-(void)xmppRequestManager:(id)arg1 timeoutForRequest:(id)arg2;
-(id)initWithConnectionDelegate:(id)arg1;
-(void)waitForState:(int)arg1;
-(BOOL)isOnline:(id)arg1;
-(void)sendPlayedReceiptForMessage:(id)arg1;
-(void)autorizationRequestForJID:(id)arg1;
-(void)changeChatState:(int)arg1 forJID:(id)arg2;
-(int)lastPresenceForJID:(id)arg1;
-(id)lastActivityForJID:(id)arg1;
-(void)sendPresenceWithNickname:(id)arg1;
-(void)sendPushConfig:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)sendPushConfigWithoutNotifications:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)setBlacklist:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)deleteAccount:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)normalizeNumber:(id)arg1 countryCode:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)changeNumber:(id)arg1 password:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)getStatusForJIDs:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)requestLastActivityForJID:(id)arg1;
-(void)requestUploadUrlForFileHash:(id)arg1 origHash:(id)arg2 filetype:(id)arg3 filesize:(id)arg4 delegate:(id)arg5 didFinishSelector:(SEL)arg6 didFailSelector:(SEL)arg7 userData:(id)arg8 withTimeout:(id)arg9;
-(void)ackMediaForUrl:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(void)sendRecoveryToken:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4 userData:(id)arg5 withTimeout:(id)arg6;
-(id)getOrGenerateRecoveryToken:(id)arg1;
-(void)removePasswordFile;
-(void)contactsSync:(id)arg1 mode:(int)arg2 context:(int)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)sendDeliveryReceiptsForChatMessages:(id)arg1;
-(void)cancelReachabilityHttpCheck;
-(void)setGroupSubject:(id)arg1 subject:(id)arg2 name:(id)arg3 delegate:(id)arg4 didFinishSelector:(SEL)arg5 didFailSelector:(SEL)arg6 userData:(id)arg7 withTimeout:(id)arg8;
-(void)queryServerPropertiesWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2 didFailSelector:(SEL)arg3 withTimeout:(id)arg4;
-(void)queryPrivacySettingsWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2 didFailSelector:(SEL)arg3 withTimeout:(id)arg4 userData:(id)arg5;
-(void)setPrivacySettingsWithDelegate:(id)arg1 didFinishSelector:(SEL)arg2 didFailSelector:(SEL)arg3 withTimeout:(id)arg4 settings:(id)arg5 userData:(id)arg6;
-(void)removeParticipantsFromGroup:(id)arg1 participants:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 userData:(id)arg6 withTimeout:(id)arg7;
-(void)deleteListFromServer:(id)arg1 userData:(id)arg2 delegate:(id)arg3 didFinishSelector:(SEL)arg4 didFailSelector:(SEL)arg5 withTimeout:(id)arg6;
-(void)enterPassiveMode;
-(void)leavePassiveMode;
-(id)createPresence:(int)arg1 withNickname:(id)arg2;
-(BOOL)isConnected;
-(id)password;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
-(void)setPassword:(id)arg1;
-(BOOL)isConnecting;
-(void)dealloc;
-(void)setType:(id)arg1;
-(void)setState:(id)arg1;
-(void)close;
-(void)connection:(id)arg1 didFailWithError:(id)arg2;
-(void)connectionDidFinishLoading:(id)arg1;
-(void).cxx_destruct;
-(void)setNetwork:(id)arg1;
-(void)setConnected:(id)arg1;
-(void)setXmppServer:(id)arg1;
-(void)sendMessage:(id)arg1;
-(void)ping;
-(void)updateState:(int)arg1;
-(id)stateToString:(int)arg1;
-(void)closeStream;
-(void)setAccountType:(id)arg1;
@end