/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:12 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPStanza : XMPPStanzaElement {
}
@property (nonatomic,retain) NSString* uniqueIdentifier; 
@property (nonatomic,retain) NSString* fromJID; 
@property (nonatomic,retain) NSString* toJID; 
@property (nonatomic,copy) NSString* errorCode; 
@property (nonatomic,copy) NSError* error; 
+(id)generateUniqueIdentifier;
+(id)generateSID;
-(void)setToJID:(id)arg1;
-(void)setFromJID:(id)arg1;
-(id)initWithName:(id)arg1 fromJID:(id)arg2 toJID:(id)arg3;
-(id)initWithStanzaElement:(id)arg1;
-(void)setUniqueIdentifier:(id)arg1;
@end