/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:37 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPRequestManager : NSObject {
	NSMutableDictionary* _requests; 
	id<XMPPRequestManagerDelegate> _delegate; 
}
@property (assign,nonatomic) id<XMPPRequestManagerDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)addRequest:(id)arg1 timeout:(id)arg2;
-(void)processIQ:(id)arg1;
-(id)getRequest:(id)arg1;
-(void)doneRequest:(id)arg1 withIQStanza:(id)arg2;
-(void)timeoutForRequest:(id)arg1;
-(BOOL)respondsToFinishedSelector:(id)arg1;
-(BOOL)respondsToFailedSelector:(id)arg1;
-(void)requestSuccess:(id)arg1;
-(void)requestFailed:(id)arg1 withStanza:(id)arg2;
-(void)requestSuccess:(id)arg1 withParam:(id)arg2;
-(void)requestSuccess:(id)arg1 withObject:(id)arg2;
-(void)requestFailed:(id)arg1 withObject:(id)arg2;
-(id)listRepresentationsFromStanza:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void).cxx_destruct;
-(void)cancelRequests;
@end