/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPSocket : NSObject {
	BOOL _bindToWWAN; 
	InetAddress* _currentIP; 
	NSString* _currentHost; 
	InetAddress* _hintIP; 
	NSArray* _hosts; 
	int _port; 
	id<XMPPSocketDelegate> _delegate; 
	double _timeout; 
}
@property (assign,nonatomic) BOOL bindToWWAN; 				//@synthesize bindToWWAN=_bindToWWAN - In the implementation block
@property (nonatomic,retain) InetAddress* currentIP; 				//@synthesize currentIP=_currentIP - In the implementation block
@property (nonatomic,retain) NSString* currentHost; 				//@synthesize currentHost=_currentHost - In the implementation block
@property (nonatomic,retain) InetAddress* hintIP; 				//@synthesize hintIP=_hintIP - In the implementation block
@property (nonatomic,retain) NSArray* hosts; 				//@synthesize hosts=_hosts - In the implementation block
@property (assign,nonatomic) int port; 				//@synthesize port=_port - In the implementation block
@property (assign,nonatomic) double timeout; 				//@synthesize timeout=_timeout - In the implementation block
@property (assign,nonatomic) id<XMPPSocketDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)setHintIP:(id)arg1;
-(void)setCurrentIP:(id)arg1;
-(void)setHosts:(id)arg1;
-(void)disconnectAfterReadingAndWriting;
-(void)readDataWithTimeout:(double)arg1 tag:(long)arg2;
-(void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long)arg3;
-(void)setBindToWWAN:(BOOL)arg1;
-(void)setCurrentHost:(id)arg1;
-(BOOL)isConnected;
-(void)setPort:(int)arg1;
-(void)setTimeout:(double)arg1;
-(void)setDelegate:(id)arg1;
-(void)connect;
-(void).cxx_destruct;
-(void)disconnect;
@end