/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:52 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPGroup : NSObject {
	NSString* _groupJID; 
	NSString* _ownerJID; 
	NSString* _subject; 
	NSDate* _creationDate; 
	NSDate* _subjectTimestamp; 
	NSString* _subjectOwnerJID; 
}
@property (nonatomic,retain) NSString* groupJID; 				//@synthesize groupJID=_groupJID - In the implementation block
@property (nonatomic,retain) NSString* ownerJID; 				//@synthesize ownerJID=_ownerJID - In the implementation block
@property (nonatomic,retain) NSString* subject; 				//@synthesize subject=_subject - In the implementation block
@property (nonatomic,retain) NSDate* creationDate; 				//@synthesize creationDate=_creationDate - In the implementation block
@property (nonatomic,retain) NSDate* subjectTimestamp; 				//@synthesize subjectTimestamp=_subjectTimestamp - In the implementation block
@property (nonatomic,retain) NSString* subjectOwnerJID; 				//@synthesize subjectOwnerJID=_subjectOwnerJID - In the implementation block
-(void)setOwnerJID:(id)arg1;
-(void)setSubjectTimestamp:(id)arg1;
-(void)setSubjectOwnerJID:(id)arg1;
-(void)setGroupJID:(id)arg1;
-(id)initWithGroupJID:(id)arg1;
-(void).cxx_destruct;
-(void)setSubject:(id)arg1;
-(void)setCreationDate:(id)arg1;
@end