/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:05:01 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol WAChatStorageDelegate
@required
-(void)chatStorage(id):arg1 didFailWithError(id):arg2 ;
-(void)chatStorage(id):arg1 didReceiveMessage(id):arg2 ;
-(void)chatStorage(id):arg1 didUpdateChatSession(id):arg2 ;
-(void)chatStorageDidUpdateChatSessionList(id):arg1 ;
-(void)chatStorageDidDeleteChatSessions(id):arg1 ;
-(void)chatStorage(id):arg1 didAddMessages(id):arg2 ;
-(void)chatStorageDidUpdateBlacklist(id):arg1 ;
-(void)getPresenseForChatSession(id):arg1 ;
-(void)chatStorage(id):arg1 willDeleteChatSession(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteChatSessionsAtIndexes(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteMessagesInSession(id):arg2 ;
-(void)mediaUploadFailedForMessage(id):arg1 ;
-(id)UIDelegateForMessage(id):arg1 ;
-(void)chatStorage(id):arg1 didUpdateMessage(id):arg2 ;
-(void)mediaDownloadFailedForMessage(id):arg1 withError(id):arg2 autodownload(BOOL):arg3 ;
-(void)updateChatSessionWithContactData(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(id)contactForJID(id):arg1 ;
-(BOOL)isRecipientExists(id):arg1 ;
-(void)disableProfilePics;
-(void)chatStorage(id):arg1 didUpdateParticipantsOfChatSession(id):arg2 ;
-(void)chatStorageDidUpdateBroadcasts(id):arg1 ;
-(id)connection;
-(*);
-(void)chatStorage(id):arg1 didFailWithError(id):arg2 ;
-(void)chatStorage(id):arg1 didReceiveMessage(id):arg2 ;
-(void)chatStorage(id):arg1 didUpdateChatSession(id):arg2 ;
-(void)chatStorageDidUpdateChatSessionList(id):arg1 ;
-(void)chatStorageDidDeleteChatSessions(id):arg1 ;
-(void)chatStorage(id):arg1 didAddMessages(id):arg2 ;
-(void)chatStorageDidUpdateBlacklist(id):arg1 ;
-(void)getPresenseForChatSession(id):arg1 ;
-(void)chatStorage(id):arg1 willDeleteChatSession(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteChatSessionsAtIndexes(id):arg2 ;
-(void)chatStorage(id):arg1 didDeleteMessagesInSession(id):arg2 ;
-(void)mediaUploadFailedForMessage(id):arg1 ;
-(id)UIDelegateForMessage(id):arg1 ;
-(void)chatStorage(id):arg1 didUpdateMessage(id):arg2 ;
-(void)mediaDownloadFailedForMessage(id):arg1 withError(id):arg2 autodownload(BOOL):arg3 ;
-(void)updateChatSessionWithContactData(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(id)contactForJID(id):arg1 ;
-(BOOL)isRecipientExists(id):arg1 ;
-(void)disableProfilePics;
-(void)chatStorage(id):arg1 didUpdateParticipantsOfChatSession(id):arg2 ;
-(void)chatStorageDidUpdateBroadcasts(id):arg1 ;
-(id)connection;
-(*);
@end

@protocol WAContactsStorageDelegate
@required
-(void)contactsStorageDidGenerateFavorites(id):arg1 ;
-(void)contactsStorageDidUpdateFavorites(id):arg1 ;
-(void)contactsStorageDidFailToGenerateFavorites(id):arg1 ;
-(void)contactsStorageDidUpdateStatus(id):arg1 ;
-(void)contactsStorageDidUpdateContacts(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(void)disableProfilePics;
-(id)chatThread;
-(BOOL)verificationInProgress;
-(id)addressBookThread;
-(void)contactsStorage(id):arg1 didUpdatePictureForJID(id):arg2 ;
-(id)connection;
-(void)contactsStorageDidGenerateFavorites(id):arg1 ;
-(void)contactsStorageDidUpdateFavorites(id):arg1 ;
-(void)contactsStorageDidFailToGenerateFavorites(id):arg1 ;
-(void)contactsStorageDidUpdateStatus(id):arg1 ;
-(void)contactsStorageDidUpdateContacts(id):arg1 ;
-(BOOL)profilePicsEnabled;
-(void)disableProfilePics;
-(id)chatThread;
-(BOOL)verificationInProgress;
-(id)addressBookThread;
-(void)contactsStorage(id):arg1 didUpdatePictureForJID(id):arg2 ;
-(id)connection;
@end

@protocol WASyncManagerDelegate
@required
-(void)syncManager(id):arg1 didFinishSyncWithResult(id):arg2 ;
-(void)syncManager(id):arg1 didFinishSyncWithResult(id):arg2 ;
@end

@protocol XMPPConnectionDelegate
@optional
-(void)xmppConnectionDidBeginConnect(id):arg1 ;
-(void)xmppConnectionDidConnect(id):arg1 ;
-(void)xmppConnectionDidDisconnect(id):arg1 ;
-(void)sendLocalNotificationForMessage(id):arg1 fromUser(id):arg2 ;
-(void)xmppConnection(id):arg1 networkStatusChanged(id):arg2 ;
-(void)xmppConnection(id):arg1 chatStateChanged(id):arg2 forJID(id):arg3 ;
-(void)xmppConnection(id):arg1 presenceChanged(id):arg2 ;
-(void)xmppConnection(id):arg1 lastActivityChanged(id):arg2 forJID(id):arg3 ;
-(void)xmppConnection(id):arg1 statusChanged(id):arg2 forMessageWithStanzaID(id):arg3 fromJID(id):arg4 data(id):arg5 ;
-(void)xmppConnection(id):arg1 stateChanged(id):arg2 ;
-(void)xmppConnectionDidAuthenticate(id):arg1 ;
-(void)xmppConnectionDidNotAuthenticate(id):arg1 ;
-(void)xmppConnection(id):arg1 passwordChanged(id):arg2 ;
-(void)xmppConnection(id):arg1 subjectChanged(id):arg2 forGroup(id):arg3 name(id):arg4 ujid(id):arg5 timestamp(id):arg6 offlineStorage(BOOL):arg7 ;
-(void)xmppConnection(id):arg1 profilePictureChangedFor(id):arg2 identifier(id):arg3 author(id):arg4 name(id):arg5 timestamp(id):arg6 ;
-(void)xmppConnection(id):arg1 profilePictureUploadRequestFor(id):arg2 timestamp(id):arg3 ;
-(void)xmppConnection(id):arg1 statusChanged(id):arg2 ;
-(void)xmppConnection(id):arg1 contactAdded(id):arg2 ;
-(void)xmppConnection(id):arg1 contactRemoved(id):arg2 ;
-(void)xmppConnection(id):arg1 contactsSyncRequest(id):arg2 timestamp(id):arg3 ;
-(void)xmppConnection(id):arg1 contactUpdated(id):arg2 ;
-(void)xmppConnection(id):arg1 groupRemoved(id):arg2 ;
-(void)xmppConnection(id):arg1 userAdded(id):arg2 toGroup(id):arg3 ;
-(void)xmppConnection(id):arg1 userRemoved(id):arg2 fromGroup(id):arg3 byUser(id):arg4 ;
-(void)xmppConnection(id):arg1 dirtyFlagsReceived(id):arg2 ;
-(void)xmppConnection(id):arg1 presenceChanged(id):arg2 forJID(id):arg3 ;
@required
-(id)storage;
-(void)receiveChatMessages(id):arg1 ;
-(id)chatThread;
-(id)addressBookContainsJID(id):arg1 ;
-(id)pushSettings;
-(id)storage;
-(void)receiveChatMessages(id):arg1 ;
-(id)chatThread;
-(id)addressBookContainsJID(id):arg1 ;
-(id)pushSettings;
@end
