/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:45 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPStanzaElement : NSObject {
	NSMutableDictionary* _attributes; 
	NSMutableArray* _children; 
	NSString* _name; 
	NSData* _value; 
}
@property (nonatomic,retain) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSData* value; 				//@synthesize value=_value - In the implementation block
-(void)setAttributeWithName:(id)arg1 value:(id)arg2;
-(id)childByName:(id)arg1;
-(id)attributeByName:(id)arg1;
-(id)childArrayByName:(id)arg1;
-(id)childByName:(id)arg1 attribute:(id)arg2 value:(id)arg3;
-(id)childByIndex:(int)arg1;
-(id)description;
-(void)setValue:(id)arg1;
-(void)setName:(id)arg1;
-(void)removeChild:(id)arg1;
-(id)attributes;
-(void).cxx_destruct;
-(id)allAttributes;
-(id)initWithName:(id)arg1;
-(void)addChild:(id)arg1;
-(int)childCount;
-(id)children;
@end