/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:47 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPBinaryCoder : NSObject {
	XMPPTokenizer* _tokenizer; 
	XMPPEncryption* _encryption; 
	NSData* _sessionKeyIn; 
	NSData* _sessionKeyOut; 
	NSData* _sessionKeyMacIn; 
	NSData* _sessionKeyMacOut; 
	NSData* _token; 
	int elementCountOut; 
	int elementCountIn; 
}
-(id)serialize:(id)arg1 encrypted:(BOOL)arg2;
-(void)setToken:(id)arg1 andPassword:(id)arg2;
-(id)authBlobForUser:(id)arg1;
-(id)unserialize:(id)arg1 mustBeEncrypted:(BOOL)arg2 processedBytes:(int*)arg3 streamError:(BOOL*)arg4;
-(void)clean;
-(id)encodeList:(id)arg1;
-(int)isCanRead:(int)arg1 from:(id)arg2 offset:(int)arg3 error:(int*)arg4;
-(id)readList:(id)arg1 offset:(int*)arg2 error:(int*)arg3;
-(id)encodeListHeader:(int)arg1;
-(BOOL)isJID:(id)arg1;
-(id)encodeJID:(id)arg1;
-(id)encodeData:(id)arg1;
-(unsigned char)getToken:(id)arg1 index:(int)arg2;
-(id)readElement:(id)arg1 offset:(int*)arg2 error:(int*)arg3;
-(int)readListLength:(id)arg1 offset:(int*)arg2 error:(int*)arg3;
-(id)readString:(id)arg1 offset:(int*)arg2 error:(int*)arg3;
-(id)keepalive;
-(void)dealloc;
-(id)init;
-(id)version;
-(void).cxx_destruct;
-(id)header;
-(id)encodeString:(id)arg1;
@end