/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:03:14 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <GCDAsyncSocketDelegate.h>

@interface XMPPGCDSocket : XMPPSocket <GCDAsyncSocketDelegate> {
	struct dispatch_queue_s* _queue; 
	GCDAsyncSocket* _socket; 
	unsigned _hostIndex; 
	NSArray* _addrs; 
	unsigned _addrIndex; 
	unsigned _addrOffset; 
	BOOL _retries; 
}
-(void)disconnectAfterReadingAndWriting;
-(void)readDataWithTimeout:(double)arg1 tag:(long)arg2;
-(void)writeData:(id)arg1 withTimeout:(double)arg2 tag:(long)arg3;
-(void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
-(void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
-(void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long)arg3;
-(void)socket:(id)arg1 didWriteDataWithTag:(long)arg2;
-(void)connectToHost:(id)arg1;
-(BOOL)isConnected;
-(void)dealloc;
-(id)init;
-(void)connect;
-(void).cxx_destruct;
-(void)disconnect;
@end