/*
 * This header is generated by weak_classdump 0.2
 * on Thursday, July 10, 2014 at 2:04:58 AM Mountain Daylight Time
 * Operating System: Version 7.1.1 (Build 11D201)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface XMPPRequest : NSObject {
	NSString* _uniqueIdentifier; 
	int _type; 
	XMPPStanza* _stanza; 
	id _delegate; 
	NSThread* _thread; 
	SEL _finishedSelector; 
	SEL _failedSelector; 
	id _userData; 
}
@property (nonatomic,retain) NSString* uniqueIdentifier; 				//@synthesize uniqueIdentifier=_uniqueIdentifier - In the implementation block
@property (assign,nonatomic) int type; 				//@synthesize type=_type - In the implementation block
@property (nonatomic,retain) XMPPStanza* stanza; 				//@synthesize stanza=_stanza - In the implementation block
@property (nonatomic,retain) id delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSThread* thread; 				//@synthesize thread=_thread - In the implementation block
@property (assign,nonatomic) SEL finishedSelector; 				//@synthesize finishedSelector=_finishedSelector - In the implementation block
@property (assign,nonatomic) SEL failedSelector; 				//@synthesize failedSelector=_failedSelector - In the implementation block
@property (nonatomic,retain) id userData; 				//@synthesize userData=_userData - In the implementation block
-(id)initWithUniqueIdentifier:(id)arg1 type:(int)arg2 stanza:(id)arg3 delegate:(id)arg4 thread:(id)arg5 finishedSelector:(SEL)arg6 failedSelector:(SEL)arg7;
-(void)setFinishedSelector:(SEL)arg1;
-(void)setFailedSelector:(SEL)arg1;
-(void)setStanza:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)setType:(int)arg1;
-(void)setUserData:(id)arg1;
-(void).cxx_destruct;
-(void)setUniqueIdentifier:(id)arg1;
-(id)stringForType:(int)arg1;
-(void)setThread:(id)arg1;
@end